/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t fp_from_int(uint64_t n __attribute__((unused)));
uint64_t fp_to_int(uint64_t x __attribute__((unused)));
uint64_t fp_from_ratio(uint64_t num __attribute__((unused)), uint64_t den __attribute__((unused)));
uint64_t fp_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t fp_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t fp_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t fp_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t fp_abs(uint64_t x __attribute__((unused)));
uint64_t fp_min(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t fp_max(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t fp_clamp(uint64_t x __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t fp_sqrt_approx(uint64_t x __attribute__((unused)));
uint64_t fp_lerp(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t t __attribute__((unused)));
int main();

uint64_t fp_from_int(uint64_t n __attribute__((unused))) {
  return (n * 65536);
}

uint64_t fp_to_int(uint64_t x __attribute__((unused))) {
  return (x / 65536);
}

uint64_t fp_from_ratio(uint64_t num __attribute__((unused)), uint64_t den __attribute__((unused))) {
  return ((num * 65536) / den);
}

uint64_t fp_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a + b);
}

uint64_t fp_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a - b);
}

uint64_t fp_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return ((a * b) / 65536);
}

uint64_t fp_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return ((a * 65536) / b);
}

uint64_t fp_abs(uint64_t x __attribute__((unused))) {
  return x;
}

uint64_t fp_min(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t fp_max(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t fp_clamp(uint64_t x __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  if ((x < lo)) {
    return lo;
  } else {
    if ((x > hi)) {
      return hi;
    } else {
      return x;
    }
  }
}

uint64_t fp_sqrt_approx(uint64_t x __attribute__((unused))) {
  uint64_t guess __attribute__((unused)) = x;
  uint64_t prev __attribute__((unused)) = (x + 1);
  {
    while ((guess < prev)) {
      prev = guess;
      guess = ((guess + (x / guess)) / 2);
    }

  }
  return guess;
}

uint64_t fp_lerp(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t t __attribute__((unused))) {
  uint64_t span_val __attribute__((unused)) = (b - a);
  uint64_t frac __attribute__((unused)) = ((span_val * t) / 65536);
  return (a + frac);
}

int main() {
  return (int)(0);

}

