/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Monomorphized generic types */
typedef enum {
  Option_u64_tag_Some = 0,
  Option_u64_tag_None = 1,
} Option_u64_tag_t;
typedef struct Option_u64 {
  Option_u64_tag_t tag;
  union {
    struct {
      uint64_t _v0;
    } Some;
    struct {
      char _dummy;
    } None;
  } data;
} Option_u64;



typedef struct Range {
  uint64_t cur;
  uint64_t end_;
} Range;

/* Forward declarations */
Option_u64 Range__Iterator__next(Range* self __attribute__((unused)));
Range range(uint64_t start __attribute__((unused)), uint64_t end_ __attribute__((unused)));

Option_u64 Range__Iterator__next(Range* self __attribute__((unused))) {
  if (((*self).cur >= (*self).end_)) {
    return (Option_u64){ .tag = Option_u64_tag_None, .data.None = { ._dummy = 0 } };
  } else {
    uint64_t v __attribute__((unused)) = (*self).cur;
    (*self).cur = ((*self).cur + 1);
    return (Option_u64){ .tag = Option_u64_tag_Some, .data.Some = { ._v0 = v } };
  }
}

Range range(uint64_t start __attribute__((unused)), uint64_t end_ __attribute__((unused))) {
  return (Range){ .cur = start, .end_ = end_ };
}

