/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void mat_zeros(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
void mat_fill(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t val __attribute__((unused)));
void mat_identity(forge_span_u64_t m __attribute__((unused)), uint64_t n __attribute__((unused)));
void mat_copy(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
void mat_add(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
void mat_sub(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
void mat_scale(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t scalar __attribute__((unused)));
void mat_mul(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t m_dim __attribute__((unused)), uint64_t k_dim __attribute__((unused)), uint64_t n_dim __attribute__((unused)));
void mat_transpose(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
uint64_t mat_dot_row(forge_span_u64_t a __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row_a __attribute__((unused)), uint64_t row_b __attribute__((unused)));
uint64_t mat_row_sum(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)));
uint64_t mat_col_sum(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t col __attribute__((unused)));
uint64_t mat_frobenius_sq(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
uint64_t mat_max_element(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
uint64_t mat_min_element(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
int main();

void mat_zeros(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      m.data[i] = 0;
      i = (i + 1);
    }

  }
}

void mat_fill(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      m.data[i] = val;
      i = (i + 1);
    }

  }
}

void mat_identity(forge_span_u64_t m __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t total __attribute__((unused)) = (n * n);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < total)) {
      m.data[i] = 0;
      i = (i + 1);
    }

  }
  uint64_t d __attribute__((unused)) = 0;
  {
    while ((d < n)) {
      m.data[((d * n) + d)] = 65536;
      d = (d + 1);
    }

  }
}

void mat_copy(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      dst.data[i] = src.data[i];
      i = (i + 1);
    }

  }
}

void mat_add(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      c.data[i] = (a.data[i] + b.data[i]);
      i = (i + 1);
    }

  }
}

void mat_sub(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      c.data[i] = (a.data[i] - b.data[i]);
      i = (i + 1);
    }

  }
}

void mat_scale(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t scalar __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      m.data[i] = ((m.data[i] * scalar) / 65536);
      i = (i + 1);
    }

  }
}

void mat_mul(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t m_dim __attribute__((unused)), uint64_t k_dim __attribute__((unused)), uint64_t n_dim __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < m_dim)) {
      uint64_t j __attribute__((unused)) = 0;
      {
        while ((j < n_dim)) {
          uint64_t acc __attribute__((unused)) = 0;
          uint64_t p __attribute__((unused)) = 0;
          {
            while ((p < k_dim)) {
              acc = (acc + ((a.data[((i * k_dim) + p)] * b.data[((p * n_dim) + j)]) / 65536));
              p = (p + 1);
            }

          }
          c.data[((i * n_dim) + j)] = acc;
          j = (j + 1);
        }

      }
      i = (i + 1);
    }

  }
}

void mat_transpose(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < rows)) {
      uint64_t j __attribute__((unused)) = 0;
      {
        while ((j < cols)) {
          dst.data[((j * rows) + i)] = src.data[((i * cols) + j)];
          j = (j + 1);
        }

      }
      i = (i + 1);
    }

  }
}

uint64_t mat_dot_row(forge_span_u64_t a __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row_a __attribute__((unused)), uint64_t row_b __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0;
  uint64_t j __attribute__((unused)) = 0;
  {
    while ((j < cols)) {
      acc = (acc + ((a.data[((row_a * cols) + j)] * a.data[((row_b * cols) + j)]) / 65536));
      j = (j + 1);
    }

  }
  return acc;
}

uint64_t mat_row_sum(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0;
  uint64_t j __attribute__((unused)) = 0;
  {
    while ((j < cols)) {
      acc = (acc + m.data[((row * cols) + j)]);
      j = (j + 1);
    }

  }
  return acc;
}

uint64_t mat_col_sum(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t col __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < rows)) {
      acc = (acc + m.data[((i * cols) + col)]);
      i = (i + 1);
    }

  }
  return acc;
}

uint64_t mat_frobenius_sq(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t acc __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      acc = (acc + ((m.data[i] * m.data[i]) / 65536));
      i = (i + 1);
    }

  }
  return acc;
}

uint64_t mat_max_element(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t mx __attribute__((unused)) = m.data[0];
  uint64_t i __attribute__((unused)) = 1;
  {
    while ((i < n)) {
      if ((m.data[i] > mx)) {
        mx = m.data[i];

      }
      i = (i + 1);
    }

  }
  return mx;
}

uint64_t mat_min_element(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (rows * cols);
  uint64_t mn __attribute__((unused)) = m.data[0];
  uint64_t i __attribute__((unused)) = 1;
  {
    while ((i < n)) {
      if ((m.data[i] < mn)) {
        mn = m.data[i];

      }
      i = (i + 1);
    }

  }
  return mn;
}

int main() {
  return (int)(0);

}

