/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#include <math.h>

/* Function pointer typedefs */
typedef double (*forge_fn_f64_ret_f64_t)(double);
typedef float (*forge_fn_f32_ret_f32_t)(float);

/* Forward declarations */
double test_cast(float val __attribute__((unused)), uint8_t scale __attribute__((unused)));
int main();

double test_cast(float val __attribute__((unused)), uint8_t scale __attribute__((unused))) {
  double s __attribute__((unused)) = ((double)scale);
  double v __attribute__((unused)) = ((double)val);
  double bs __attribute__((unused)) = exp2((s - 127));
  return (v * bs);
}

int main() {
  return (int)(0ULL);

}

