/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;

/* Forward declarations */
uint64_t get_version(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)));
uint64_t get_ihl(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)));
uint64_t get_protocol(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)));
uint64_t get_src_ip(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)));
uint64_t get_dst_ip(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)));
uint64_t get_src_port(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)), uint64_t hdr_len __attribute__((unused)));
uint64_t get_dst_port(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)), uint64_t hdr_len __attribute__((unused)));
uint64_t get_tcp_flags(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)), uint64_t hdr_len __attribute__((unused)));
_Bool rule_matches(forge_span_u64_t rules __attribute__((unused)), uint64_t base __attribute__((unused)), uint64_t proto __attribute__((unused)), uint64_t src_ip __attribute__((unused)), uint64_t dst_ip __attribute__((unused)), uint64_t dst_port __attribute__((unused)));
uint64_t match_rules(forge_span_u64_t rules __attribute__((unused)), uint64_t n_rules __attribute__((unused)), uint64_t proto __attribute__((unused)), uint64_t src_ip __attribute__((unused)), uint64_t dst_ip __attribute__((unused)), uint64_t dst_port __attribute__((unused)));
uint64_t conn_state_transition(uint64_t state __attribute__((unused)), uint64_t flags __attribute__((unused)));
uint64_t conntrack_lookup(forge_span_u64_t ct __attribute__((unused)), uint64_t n_entries __attribute__((unused)), uint64_t src_ip __attribute__((unused)), uint64_t dst_ip __attribute__((unused)), uint64_t src_port __attribute__((unused)), uint64_t dst_port __attribute__((unused)));
void conntrack_update(forge_span_u64_t ct __attribute__((unused)), uint64_t n_entries __attribute__((unused)), uint64_t idx __attribute__((unused)), uint64_t flags __attribute__((unused)), uint64_t timestamp __attribute__((unused)));
uint64_t conntrack_insert(forge_span_u64_t ct __attribute__((unused)), uint64_t n_entries __attribute__((unused)), uint64_t src_ip __attribute__((unused)), uint64_t dst_ip __attribute__((unused)), uint64_t src_port __attribute__((unused)), uint64_t dst_port __attribute__((unused)), uint64_t timestamp __attribute__((unused)));
uint64_t filter_packet(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)), forge_span_u64_t rules __attribute__((unused)), uint64_t n_rules __attribute__((unused)), forge_span_u64_t ct __attribute__((unused)), uint64_t n_ct_entries __attribute__((unused)), uint64_t timestamp __attribute__((unused)));
__forge_tuple_u64_u64_t count_verdicts(forge_span_u64_t verdicts __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t get_version(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused))) {
  return ((pkt.data[0] / 16) % 16);
}

uint64_t get_ihl(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused))) {
  return (pkt.data[0] % 16);
}

uint64_t get_protocol(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused))) {
  return (pkt.data[9] % 256);
}

uint64_t get_src_ip(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused))) {
  return ((((pkt.data[12] * 16777216) + (pkt.data[13] * 65536)) + (pkt.data[14] * 256)) + pkt.data[15]);
}

uint64_t get_dst_ip(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused))) {
  return ((((pkt.data[16] * 16777216) + (pkt.data[17] * 65536)) + (pkt.data[18] * 256)) + pkt.data[19]);
}

uint64_t get_src_port(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)), uint64_t hdr_len __attribute__((unused))) {
  return ((pkt.data[hdr_len] * 256) + pkt.data[(hdr_len + 1)]);
}

uint64_t get_dst_port(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)), uint64_t hdr_len __attribute__((unused))) {
  return ((pkt.data[(hdr_len + 2)] * 256) + pkt.data[(hdr_len + 3)]);
}

uint64_t get_tcp_flags(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)), uint64_t hdr_len __attribute__((unused))) {
  return (pkt.data[(hdr_len + 13)] % 64);
}

_Bool rule_matches(forge_span_u64_t rules __attribute__((unused)), uint64_t base __attribute__((unused)), uint64_t proto __attribute__((unused)), uint64_t src_ip __attribute__((unused)), uint64_t dst_ip __attribute__((unused)), uint64_t dst_port __attribute__((unused))) {
  uint64_t wildcard __attribute__((unused)) = -1;
  uint64_t r_proto __attribute__((unused)) = rules.data[base];
  uint64_t r_src __attribute__((unused)) = rules.data[(base + 1)];
  uint64_t r_dst __attribute__((unused)) = rules.data[(base + 2)];
  uint64_t r_port __attribute__((unused)) = rules.data[(base + 3)];
  return (((((r_proto == wildcard) || (r_proto == proto)) && ((r_src == wildcard) || (r_src == src_ip))) && ((r_dst == wildcard) || (r_dst == dst_ip))) && ((r_port == wildcard) || (r_port == dst_port)));
}

uint64_t match_rules(forge_span_u64_t rules __attribute__((unused)), uint64_t n_rules __attribute__((unused)), uint64_t proto __attribute__((unused)), uint64_t src_ip __attribute__((unused)), uint64_t dst_ip __attribute__((unused)), uint64_t dst_port __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  uint64_t verdict __attribute__((unused)) = 0;
  _Bool matched __attribute__((unused)) = 0;
  {
    while ((i < n_rules)) {
      if ((!matched)) {
        uint64_t base __attribute__((unused)) = (i * 5);
        if (((base + 4) < (n_rules * 5))) {
          if (rule_matches(rules, base, proto, src_ip, dst_ip, dst_port)) {
            verdict = ((rules.data[(base + 4)] == 1) ? 1 : 0);
            matched = 1;

          }

        }

      }
      i = (i + 1);
    }

  }
  return verdict;
}

uint64_t conn_state_transition(uint64_t state __attribute__((unused)), uint64_t flags __attribute__((unused))) {
  _Bool syn __attribute__((unused)) = (((flags / 2) % 2) == 1);
  _Bool ack __attribute__((unused)) = (((flags / 16) % 2) == 1);
  _Bool fin __attribute__((unused)) = ((flags % 2) == 1);
  _Bool rst __attribute__((unused)) = (((flags / 4) % 2) == 1);
  uint64_t next __attribute__((unused)) = state;
  if (rst) {
    next = 0;

  } else if ((state == 0)) {
    if ((syn && (!ack))) {
      next = 1;

    }

  } else if ((state == 1)) {
    if ((syn && ack)) {
      next = 2;

    }

  } else if ((state == 2)) {
    if (ack) {
      next = 3;

    }

  } else if ((state == 3)) {
    if (fin) {
      next = 4;

    }

  } else if ((state == 4)) {
    if (ack) {
      next = 5;

    }

  }
  return next;
}

uint64_t conntrack_lookup(forge_span_u64_t ct __attribute__((unused)), uint64_t n_entries __attribute__((unused)), uint64_t src_ip __attribute__((unused)), uint64_t dst_ip __attribute__((unused)), uint64_t src_port __attribute__((unused)), uint64_t dst_port __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  uint64_t found __attribute__((unused)) = n_entries;
  {
    while ((i < n_entries)) {
      uint64_t base __attribute__((unused)) = (i * 6);
      if (((base + 5) < (n_entries * 6))) {
        if ((((((ct.data[base] == src_ip) && (ct.data[(base + 1)] == dst_ip)) && (ct.data[(base + 2)] == src_port)) && (ct.data[(base + 3)] == dst_port)) && (found == n_entries))) {
          found = i;

        }

      }
      i = (i + 1);
    }

  }
  return found;
}

void conntrack_update(forge_span_u64_t ct __attribute__((unused)), uint64_t n_entries __attribute__((unused)), uint64_t idx __attribute__((unused)), uint64_t flags __attribute__((unused)), uint64_t timestamp __attribute__((unused))) {
  uint64_t base __attribute__((unused)) = (idx * 6);
  if (((base + 5) < (n_entries * 6))) {
    uint64_t old_state __attribute__((unused)) = ct.data[(base + 4)];
    if ((old_state < 6)) {
      uint64_t new_state __attribute__((unused)) = conn_state_transition(old_state, flags);
      ct.data[(base + 4)] = new_state;
      ct.data[(base + 5)] = timestamp;

    }

  }
}

uint64_t conntrack_insert(forge_span_u64_t ct __attribute__((unused)), uint64_t n_entries __attribute__((unused)), uint64_t src_ip __attribute__((unused)), uint64_t dst_ip __attribute__((unused)), uint64_t src_port __attribute__((unused)), uint64_t dst_port __attribute__((unused)), uint64_t timestamp __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  uint64_t slot __attribute__((unused)) = n_entries;
  {
    while ((i < n_entries)) {
      uint64_t base __attribute__((unused)) = (i * 6);
      if (((base + 5) < (n_entries * 6))) {
        if (((ct.data[(base + 4)] == 0) && (slot == n_entries))) {
          ct.data[base] = src_ip;
          ct.data[(base + 1)] = dst_ip;
          ct.data[(base + 2)] = src_port;
          ct.data[(base + 3)] = dst_port;
          ct.data[(base + 4)] = 1;
          ct.data[(base + 5)] = timestamp;
          slot = i;

        }

      }
      i = (i + 1);
    }

  }
  return slot;
}

uint64_t filter_packet(forge_span_u64_t pkt __attribute__((unused)), uint64_t pkt_len __attribute__((unused)), forge_span_u64_t rules __attribute__((unused)), uint64_t n_rules __attribute__((unused)), forge_span_u64_t ct __attribute__((unused)), uint64_t n_ct_entries __attribute__((unused)), uint64_t timestamp __attribute__((unused))) {
  uint64_t verdict __attribute__((unused)) = 0;
  if ((pkt_len >= 20)) {
    uint64_t ver __attribute__((unused)) = get_version(pkt, pkt_len);
    uint64_t ihl __attribute__((unused)) = get_ihl(pkt, pkt_len);
    uint64_t hdr_len __attribute__((unused)) = (ihl * 4);
    if ((((ver == 4) && (ihl >= 5)) && (hdr_len <= pkt_len))) {
      uint64_t proto __attribute__((unused)) = get_protocol(pkt, pkt_len);
      uint64_t src_ip __attribute__((unused)) = get_src_ip(pkt, pkt_len);
      uint64_t dst_ip __attribute__((unused)) = get_dst_ip(pkt, pkt_len);
      uint64_t dst_port __attribute__((unused)) = 0;
      uint64_t src_port __attribute__((unused)) = 0;
      uint64_t tcp_flags __attribute__((unused)) = 0;
      if (((hdr_len + 4) <= pkt_len)) {
        src_port = get_src_port(pkt, pkt_len, hdr_len);
        dst_port = get_dst_port(pkt, pkt_len, hdr_len);

      }
      if ((((hdr_len + 14) <= pkt_len) && (proto == 6))) {
        tcp_flags = get_tcp_flags(pkt, pkt_len, hdr_len);

      }
      verdict = match_rules(rules, n_rules, proto, src_ip, dst_ip, dst_port);
      if (((proto == 6) && (verdict == 1))) {
        uint64_t ct_idx __attribute__((unused)) = conntrack_lookup(ct, n_ct_entries, src_ip, dst_ip, src_port, dst_port);
        if ((ct_idx < n_ct_entries)) {
          conntrack_update(ct, n_ct_entries, ct_idx, tcp_flags, timestamp);

        } else {
          _Bool syn __attribute__((unused)) = (((tcp_flags / 2) % 2) == 1);
          _Bool ack __attribute__((unused)) = (((tcp_flags / 16) % 2) == 1);
          if ((syn && (!ack))) {
            uint64_t _new_idx __attribute__((unused)) = conntrack_insert(ct, n_ct_entries, src_ip, dst_ip, src_port, dst_port, timestamp);

          }

        }

      }

    }

  }
  return verdict;
}

__forge_tuple_u64_u64_t count_verdicts(forge_span_u64_t verdicts __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t accept __attribute__((unused)) = 0;
  uint64_t drop __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      if ((verdicts.data[i] == 1)) {
        accept = (accept + 1);

      } else {
        drop = (drop + 1);

      }
      i = (i + 1);
    }

  }
  return (__forge_tuple_u64_u64_t){ ._0 = accept, ._1 = drop };
}

int main() {
  return (int)(0);

}

