/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t binary_search(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t lower_bound(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t upper_bound(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t linear_search(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
_Bool contains(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t min_index(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t max_index(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t search_and_format(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t search_nested_format(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
int main();

uint64_t binary_search(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t lo __attribute__((unused)) = 0ULL;
  uint64_t hi __attribute__((unused)) = n;
  uint64_t ans __attribute__((unused)) = n;
  {
    while ((lo < hi)) {
      uint64_t mid __attribute__((unused)) = (lo + ((hi - lo) / 2ULL));
      if ((s.data[mid] == target)) {
        ans = mid;
        lo = hi;

      } else if ((s.data[mid] < target)) {
        lo = (mid + 1ULL);

      } else {
        hi = mid;

      }
    }

  }
  return ans;
}

uint64_t lower_bound(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t lo __attribute__((unused)) = 0ULL;
  uint64_t hi __attribute__((unused)) = n;
  {
    while ((lo < hi)) {
      uint64_t mid __attribute__((unused)) = (lo + ((hi - lo) / 2ULL));
      if ((s.data[mid] < target)) {
        lo = (mid + 1ULL);

      } else {
        hi = mid;

      }
    }

  }
  return lo;
}

uint64_t upper_bound(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t lo __attribute__((unused)) = 0ULL;
  uint64_t hi __attribute__((unused)) = n;
  {
    while ((lo < hi)) {
      uint64_t mid __attribute__((unused)) = (lo + ((hi - lo) / 2ULL));
      if ((s.data[mid] <= target)) {
        lo = (mid + 1ULL);

      } else {
        hi = mid;

      }
    }

  }
  return lo;
}

uint64_t linear_search(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  uint64_t found __attribute__((unused)) = n;
  {
    while ((i < n)) {
      if (((s.data[i] == target) && (found == n))) {
        found = i;

      }
      i = (i + 1ULL);
    }

  }
  return found;
}

_Bool contains(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t idx __attribute__((unused)) = linear_search(s, n, target);
  return (idx < n);
}

uint64_t min_index(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t best __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      if ((s.data[i] < s.data[best])) {
        best = i;

      }
      i = (i + 1ULL);
    }

  }
  return best;
}

uint64_t max_index(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t best __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      if ((s.data[i] > s.data[best])) {
        best = i;

      }
      i = (i + 1ULL);
    }

  }
  return best;
}

uint64_t search_and_format(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  return binary_search(s, n, target);
}

uint64_t search_nested_format(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  return binary_search(s, n, target);
}

int main() {
  return (int)(0ULL);

}

