/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))


/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint32_t* data; uintptr_t len; } forge_span_u32_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_ptr_u64_u64_ret_u64_t)(uint64_t*, uint64_t);
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef uint64_t (*forge_fn__ret_u64_t)(void);

uint64_t shfl_down_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

uint64_t shfl_xor_sync(uint64_t val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

uint64_t atom_add(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_cas(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_max(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_min(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t ballot_sync(uint64_t pred);  /* extern: forge_gpu */

uint64_t lane_id(void);  /* extern: forge_gpu */

uint64_t warp_id(void);  /* extern: forge_gpu */

/* Tuple typedefs */
typedef struct { uint32_t _0; uint32_t _1; uint32_t _2; uint32_t _3; } __forge_tuple_u32_u32_u32_u32_t;

/* Forward declarations */
uint64_t warp_reduce_sum(uint64_t val __attribute__((unused)));
uint64_t warp_reduce_max(uint64_t val __attribute__((unused)));
uint64_t warp_reduce_min(uint64_t val __attribute__((unused)));
uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused)));
uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused)));
int main();
uint32_t rotr32(uint32_t x __attribute__((unused)), uint32_t n __attribute__((unused)));
__forge_tuple_u32_u32_u32_u32_t blake2s_g(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)), uint32_t c __attribute__((unused)), uint32_t d __attribute__((unused)), uint32_t x __attribute__((unused)), uint32_t y __attribute__((unused)));
void blake2s_round(forge_span_u32_t v __attribute__((unused)), forge_span_u32_t m __attribute__((unused)), uint64_t s0 __attribute__((unused)), uint64_t s1 __attribute__((unused)), uint64_t s2 __attribute__((unused)), uint64_t s3 __attribute__((unused)), uint64_t s4 __attribute__((unused)), uint64_t s5 __attribute__((unused)), uint64_t s6 __attribute__((unused)), uint64_t s7 __attribute__((unused)), uint64_t s8 __attribute__((unused)), uint64_t s9 __attribute__((unused)), uint64_t s10 __attribute__((unused)), uint64_t s11 __attribute__((unused)), uint64_t s12 __attribute__((unused)), uint64_t s13 __attribute__((unused)), uint64_t s14 __attribute__((unused)), uint64_t s15 __attribute__((unused)), forge_span_u32_t out __attribute__((unused)));
__global__ void blake2s_leaf_hash(forge_span_u32_t output __attribute__((unused)), forge_span_u32_t input __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t warp_reduce_sum(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

uint64_t warp_reduce_max(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

uint64_t warp_reduce_min(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused))) {
  return ((block_idx * block_dim) + thread_idx);
}

uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused))) {
  return (block_dim * grid_dim);
}

int main() {
  return (int)(0ULL);

}

uint32_t rotr32(uint32_t x __attribute__((unused)), uint32_t n __attribute__((unused))) {
  return ((x >> n) | (x << (32ULL - n)));
}

__forge_tuple_u32_u32_u32_u32_t blake2s_g(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)), uint32_t c __attribute__((unused)), uint32_t d __attribute__((unused)), uint32_t x __attribute__((unused)), uint32_t y __attribute__((unused))) {
  uint32_t a1 __attribute__((unused)) = ((a + b) + x);
  uint32_t d1 __attribute__((unused)) = rotr32((d ^ a1), 16ULL);
  uint32_t c1 __attribute__((unused)) = (c + d1);
  uint32_t b1 __attribute__((unused)) = rotr32((b ^ c1), 12ULL);
  uint32_t a2 __attribute__((unused)) = ((a1 + b1) + y);
  uint32_t d2 __attribute__((unused)) = rotr32((d1 ^ a2), 8ULL);
  uint32_t c2 __attribute__((unused)) = (c1 + d2);
  uint32_t b2 __attribute__((unused)) = rotr32((b1 ^ c2), 7ULL);
  return (__forge_tuple_u32_u32_u32_u32_t){ ._0 = a2, ._1 = b2, ._2 = c2, ._3 = d2 };
}

void blake2s_round(forge_span_u32_t v __attribute__((unused)), forge_span_u32_t m __attribute__((unused)), uint64_t s0 __attribute__((unused)), uint64_t s1 __attribute__((unused)), uint64_t s2 __attribute__((unused)), uint64_t s3 __attribute__((unused)), uint64_t s4 __attribute__((unused)), uint64_t s5 __attribute__((unused)), uint64_t s6 __attribute__((unused)), uint64_t s7 __attribute__((unused)), uint64_t s8 __attribute__((unused)), uint64_t s9 __attribute__((unused)), uint64_t s10 __attribute__((unused)), uint64_t s11 __attribute__((unused)), uint64_t s12 __attribute__((unused)), uint64_t s13 __attribute__((unused)), uint64_t s14 __attribute__((unused)), uint64_t s15 __attribute__((unused)), forge_span_u32_t out __attribute__((unused))) {
  __forge_tuple_u32_u32_u32_u32_t __tup_77_4 __attribute__((unused)) = blake2s_g(v.data[0ULL], v.data[4ULL], v.data[8ULL], v.data[12ULL], m.data[s0], m.data[s1]);
  uint32_t a0 __attribute__((unused)) = (__tup_77_4)._0;
  uint32_t b0 __attribute__((unused)) = (__tup_77_4)._1;
  uint32_t c0 __attribute__((unused)) = (__tup_77_4)._2;
  uint32_t d0 __attribute__((unused)) = (__tup_77_4)._3;
  __forge_tuple_u32_u32_u32_u32_t __tup_78_4 __attribute__((unused)) = blake2s_g(v.data[1ULL], v.data[5ULL], v.data[9ULL], v.data[13ULL], m.data[s2], m.data[s3]);
  uint32_t a1 __attribute__((unused)) = (__tup_78_4)._0;
  uint32_t b1 __attribute__((unused)) = (__tup_78_4)._1;
  uint32_t c1 __attribute__((unused)) = (__tup_78_4)._2;
  uint32_t d1 __attribute__((unused)) = (__tup_78_4)._3;
  __forge_tuple_u32_u32_u32_u32_t __tup_79_4 __attribute__((unused)) = blake2s_g(v.data[2ULL], v.data[6ULL], v.data[10ULL], v.data[14ULL], m.data[s4], m.data[s5]);
  uint32_t a2 __attribute__((unused)) = (__tup_79_4)._0;
  uint32_t b2 __attribute__((unused)) = (__tup_79_4)._1;
  uint32_t c2 __attribute__((unused)) = (__tup_79_4)._2;
  uint32_t d2 __attribute__((unused)) = (__tup_79_4)._3;
  __forge_tuple_u32_u32_u32_u32_t __tup_80_4 __attribute__((unused)) = blake2s_g(v.data[3ULL], v.data[7ULL], v.data[11ULL], v.data[15ULL], m.data[s6], m.data[s7]);
  uint32_t a3 __attribute__((unused)) = (__tup_80_4)._0;
  uint32_t b3 __attribute__((unused)) = (__tup_80_4)._1;
  uint32_t c3 __attribute__((unused)) = (__tup_80_4)._2;
  uint32_t d3 __attribute__((unused)) = (__tup_80_4)._3;
  __forge_tuple_u32_u32_u32_u32_t __tup_83_4 __attribute__((unused)) = blake2s_g(a0, b1, c2, d3, m.data[s8], m.data[s9]);
  uint32_t a4 __attribute__((unused)) = (__tup_83_4)._0;
  uint32_t b4 __attribute__((unused)) = (__tup_83_4)._1;
  uint32_t c4 __attribute__((unused)) = (__tup_83_4)._2;
  uint32_t d4 __attribute__((unused)) = (__tup_83_4)._3;
  __forge_tuple_u32_u32_u32_u32_t __tup_84_4 __attribute__((unused)) = blake2s_g(a1, b2, c3, d0, m.data[s10], m.data[s11]);
  uint32_t a5 __attribute__((unused)) = (__tup_84_4)._0;
  uint32_t b5 __attribute__((unused)) = (__tup_84_4)._1;
  uint32_t c5 __attribute__((unused)) = (__tup_84_4)._2;
  uint32_t d5 __attribute__((unused)) = (__tup_84_4)._3;
  __forge_tuple_u32_u32_u32_u32_t __tup_85_4 __attribute__((unused)) = blake2s_g(a2, b3, c0, d1, m.data[s12], m.data[s13]);
  uint32_t a6 __attribute__((unused)) = (__tup_85_4)._0;
  uint32_t b6 __attribute__((unused)) = (__tup_85_4)._1;
  uint32_t c6 __attribute__((unused)) = (__tup_85_4)._2;
  uint32_t d6 __attribute__((unused)) = (__tup_85_4)._3;
  __forge_tuple_u32_u32_u32_u32_t __tup_86_4 __attribute__((unused)) = blake2s_g(a3, b0, c1, d2, m.data[s14], m.data[s15]);
  uint32_t a7 __attribute__((unused)) = (__tup_86_4)._0;
  uint32_t b7 __attribute__((unused)) = (__tup_86_4)._1;
  uint32_t c7 __attribute__((unused)) = (__tup_86_4)._2;
  uint32_t d7 __attribute__((unused)) = (__tup_86_4)._3;
  out.data[0ULL] = a4;
  out.data[1ULL] = a5;
  out.data[2ULL] = a6;
  out.data[3ULL] = a7;
  out.data[4ULL] = b7;
  out.data[5ULL] = b4;
  out.data[6ULL] = b5;
  out.data[7ULL] = b6;
  out.data[8ULL] = c6;
  out.data[9ULL] = c7;
  out.data[10ULL] = c4;
  out.data[11ULL] = c5;
  out.data[12ULL] = d5;
  out.data[13ULL] = d6;
  out.data[14ULL] = d7;
  out.data[15ULL] = d4;
}

__global__ void blake2s_leaf_hash(forge_span_u32_t output __attribute__((unused)), forge_span_u32_t input __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t gid __attribute__((unused)) = ((blockIdx_x * blockDim_x) + threadIdx_x);
  if ((gid < n)) {
    /* assert erased */;
    /* assert erased */;

  }
}

int main() {
  return (int)(0ULL);

}

