/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))

#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif
#include <string.h>
#include <stdio.h>
#include <math.h>

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { float* data; uintptr_t len; } forge_span_f32_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef void (*forge_fn_u64_ret_unit_t)(uint64_t);
typedef uint64_t (*forge_fn_u64_u64_ret_u64_t)(uint64_t, uint64_t);
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_u64_i32_u64_ret_u64_t)(uint64_t, int32_t, uint64_t);
typedef int32_t (*forge_fn_u64_u64_u64_ret_i32_t)(uint64_t, uint64_t, uint64_t);
typedef int32_t (*forge_fn_u64_u64_ret_i32_t)(uint64_t, uint64_t);
typedef int32_t (*forge_fn_u64_ret_i32_t)(uint64_t);
typedef int32_t (*forge_fn__ret_i32_t)(void);
typedef uint64_t (*forge_fn_u64_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t, uint64_t);
typedef void (*forge_fn__ret_unit_t)(void);
typedef void (*forge_fn_i32_ret_unit_t)(int32_t);
typedef double (*forge_fn_f64_ret_f64_t)(double);
typedef double (*forge_fn_f64_f64_ret_f64_t)(double, double);
typedef float (*forge_fn_f32_ret_f32_t)(float);
typedef float (*forge_fn_f32_f32_ret_f32_t)(float, float);

/* Forward declarations */
__global__ void sinusoidal_pe(forge_span_f32_t out __attribute__((unused)), uint64_t seq_len __attribute__((unused)));
int main();

__global__ void sinusoidal_pe(forge_span_f32_t out __attribute__((unused)), uint64_t seq_len __attribute__((unused))) {
  uint64_t lane __attribute__((unused)) = threadIdx_x;
  uint64_t pos __attribute__((unused)) = blockIdx_x;
  uint64_t base __attribute__((unused)) = (pos * 32ULL);
  float lane_f __attribute__((unused)) = ((float)lane);
  float pos_f __attribute__((unused)) = ((float)pos);
  float exponent __attribute__((unused)) = (0 - (lane_f * 0.57564627324851148));
  float freq __attribute__((unused)) = expf(exponent);
  float theta __attribute__((unused)) = (pos_f * freq);
  float s __attribute__((unused)) = sinf(theta);
  float c __attribute__((unused)) = cosf(theta);
  uint64_t idx_e __attribute__((unused)) = (base + (lane * 2ULL));
  uint64_t idx_o __attribute__((unused)) = ((base + (lane * 2ULL)) + 1ULL);
  /* assume erased */;
  /* assume erased */;
  out.data[idx_e] = s;
  out.data[idx_o] = c;
}

int main() {
  return (int)(0);

}


/* ---- FORGE ASSUMPTION AUDIT LOG ----
   Total assumptions: 2
   [ASSUME] demos/1142_forge_sinusoidal_pe.fg:44  (< idx_e out__len)
             "pos<seq_len + lane<16 + seq_len*32<=out.len"
   [ASSUME] demos/1142_forge_sinusoidal_pe.fg:45  (< idx_o out__len)
             "same chain (idx_o = idx_e + 1 < base + 32)"
   ---- END AUDIT LOG ---- */
