/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))

#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif
#include <string.h>
#include <stdio.h>
#include <math.h>

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { float* data; uintptr_t len; } forge_span_f32_t;
typedef struct { uint32_t* data; uintptr_t len; } forge_span_u32_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef void (*forge_fn_u64_ret_unit_t)(uint64_t);
typedef uint64_t (*forge_fn_u64_u64_ret_u64_t)(uint64_t, uint64_t);
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_u64_i32_u64_ret_u64_t)(uint64_t, int32_t, uint64_t);
typedef int32_t (*forge_fn_u64_u64_u64_ret_i32_t)(uint64_t, uint64_t, uint64_t);
typedef int32_t (*forge_fn_u64_u64_ret_i32_t)(uint64_t, uint64_t);
typedef int32_t (*forge_fn_u64_ret_i32_t)(uint64_t);
typedef int32_t (*forge_fn__ret_i32_t)(void);
typedef uint64_t (*forge_fn_u64_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t, uint64_t);
typedef void (*forge_fn__ret_unit_t)(void);
typedef void (*forge_fn_i32_ret_unit_t)(int32_t);
typedef double (*forge_fn_f64_ret_f64_t)(double);
typedef double (*forge_fn_f64_f64_ret_f64_t)(double, double);
typedef float (*forge_fn_f32_ret_f32_t)(float);
typedef float (*forge_fn_f32_f32_ret_f32_t)(float, float);
typedef uint64_t (*forge_fn_ptr_u64_u64_ret_u64_t)(uint64_t*, uint64_t);
typedef uint64_t (*forge_fn__ret_u64_t)(void);
typedef float (*forge_fn_f32_u64_u64_ret_f32_t)(float, uint64_t, uint64_t);

uint64_t shfl_down_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

uint64_t shfl_xor_sync(uint64_t val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

uint64_t atom_add(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_cas(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_max(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_min(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t shfl_up_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

uint64_t atom_or(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_xor(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_and(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_sub(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_exch(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t ballot_sync(uint64_t pred);  /* extern: forge_gpu */

uint64_t lane_id(void);  /* extern: forge_gpu */

uint64_t warp_id(void);  /* extern: forge_gpu */

__device__ float shfl_xor_sync_f32(float val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

float shfl_down_sync_f32(float val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

/* Forward declarations */
static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused)));
uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused)));
uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused)));
__global__ void argmax_row(forge_span_f32_t logits __attribute__((unused)), forge_span_u32_t out __attribute__((unused)), uint64_t n_classes __attribute__((unused)));
int main();

static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused))) {
  return ((block_idx * block_dim) + thread_idx);
}

uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused))) {
  return (block_dim * grid_dim);
}

__global__ void argmax_row(forge_span_f32_t logits __attribute__((unused)), forge_span_u32_t out __attribute__((unused)), uint64_t n_classes __attribute__((unused))) {
  uint64_t lane __attribute__((unused)) = threadIdx_x;
  uint64_t row __attribute__((unused)) = blockIdx_x;
  uint64_t base __attribute__((unused)) = (row * n_classes);
  float neg_inf __attribute__((unused)) = (-1e+30);
  float x __attribute__((unused)) = neg_inf;
  if ((lane < n_classes)) {
    /* assume erased */;
    x = logits.data[(base + lane)];

  }
  float row_max __attribute__((unused)) = warp_reduce_max_f32(x);
  float big_idx __attribute__((unused)) = 10000000000;
  float lane_f __attribute__((unused)) = ((float)lane);
  float candidate;
  if ((x == row_max)) {
    candidate = lane_f;
  } else {
    candidate = big_idx;
  }
  float argmax_f __attribute__((unused)) = warp_reduce_min_f32(candidate);
  uint32_t argmax_u __attribute__((unused)) = ((uint32_t)argmax_f);
  if ((lane == 0ULL)) {
    /* assume erased */;
    out.data[row] = argmax_u;

  }
}

int main() {
  return (int)(0);

}


/* ---- FORGE ASSUMPTION AUDIT LOG ----
   Total assumptions: 2
   [ASSUME] demos/1143_forge_argmax_row.fg:35  (< (+ base lane) logits__len)
             "blockIdx_x<gridDim_x + lane<n_classes + gridDim_x*n_classes<=logits.len"
   [ASSUME] demos/1143_forge_argmax_row.fg:53  (< row out__len)
             "row=blockIdx_x < gridDim_x <= out.len"
   ---- END AUDIT LOG ---- */
