/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))

#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif
#include <string.h>
#include <stdio.h>
#include <math.h>

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { float* data; uintptr_t len; } forge_span_f32_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef void (*forge_fn_u64_ret_unit_t)(uint64_t);
typedef uint64_t (*forge_fn_u64_u64_ret_u64_t)(uint64_t, uint64_t);
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_u64_i32_u64_ret_u64_t)(uint64_t, int32_t, uint64_t);
typedef int32_t (*forge_fn_u64_u64_u64_ret_i32_t)(uint64_t, uint64_t, uint64_t);
typedef int32_t (*forge_fn_u64_u64_ret_i32_t)(uint64_t, uint64_t);
typedef int32_t (*forge_fn_u64_ret_i32_t)(uint64_t);
typedef int32_t (*forge_fn__ret_i32_t)(void);
typedef uint64_t (*forge_fn_u64_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t, uint64_t);
typedef void (*forge_fn__ret_unit_t)(void);
typedef void (*forge_fn_i32_ret_unit_t)(int32_t);
typedef double (*forge_fn_f64_ret_f64_t)(double);
typedef double (*forge_fn_f64_f64_ret_f64_t)(double, double);
typedef float (*forge_fn_f32_ret_f32_t)(float);
typedef float (*forge_fn_f32_f32_ret_f32_t)(float, float);

static const uint32_t PHILOX_M2x32 = 3528531795ULL;

static const uint32_t PHILOX_W = 2654435769ULL;

/* Tuple typedefs */
typedef struct { uint32_t _0; uint32_t _1; } __forge_tuple_u32_u32_t;

/* Forward declarations */
static __device__ __forceinline__ float sigmoid(float x __attribute__((unused)));
static __device__ __forceinline__ float silu(float x __attribute__((unused)));
static __device__ __forceinline__ float swiglu(float gate __attribute__((unused)), float up __attribute__((unused)));
static __device__ __forceinline__ float relu(float x __attribute__((unused)));
static __device__ __forceinline__ float leaky_relu(float x __attribute__((unused)), float alpha __attribute__((unused)));
static __device__ __forceinline__ float softplus(float x __attribute__((unused)));
static __device__ __forceinline__ float gelu(float x __attribute__((unused)));
static __device__ __forceinline__ float mish(float x __attribute__((unused)));
static __device__ __forceinline__ float hard_sigmoid(float x __attribute__((unused)));
static __device__ __forceinline__ float hard_silu(float x __attribute__((unused)));
static __device__ __forceinline__ __forge_tuple_u32_u32_t philox_round(uint32_t ctr0 __attribute__((unused)), uint32_t ctr1 __attribute__((unused)), uint32_t key __attribute__((unused)));
static __device__ __forceinline__ uint32_t philox_bump_key(uint32_t key __attribute__((unused)));
static __device__ __forceinline__ __forge_tuple_u32_u32_t philox_2x32_10(uint32_t key0 __attribute__((unused)), uint32_t key1 __attribute__((unused)), uint32_t ctr0 __attribute__((unused)), uint32_t ctr1 __attribute__((unused)));
static __device__ __forceinline__ float philox_to_uniform_f32(uint32_t u __attribute__((unused)));
static __device__ __forceinline__ uint32_t philox_bernoulli_keep_u32(uint32_t u __attribute__((unused)), uint32_t p_threshold_u32 __attribute__((unused)));
__global__ void ffn_swiglu_dropout(forge_span_f32_t gate __attribute__((unused)), forge_span_f32_t up __attribute__((unused)), forge_span_f32_t out __attribute__((unused)), uint64_t n __attribute__((unused)), uint32_t seed_lo __attribute__((unused)), uint32_t seed_hi __attribute__((unused)), uint32_t p_threshold __attribute__((unused)), float keep_scale __attribute__((unused)));
int main();

static __device__ __forceinline__ float sigmoid(float x __attribute__((unused))) {
  float neg_x __attribute__((unused)) = (0 - x);
  float e __attribute__((unused)) = expf(neg_x);
  return (1 / (1 + e));
}

static __device__ __forceinline__ float silu(float x __attribute__((unused))) {
  float neg_x __attribute__((unused)) = (0 - x);
  float e __attribute__((unused)) = expf(neg_x);
  return (x / (1 + e));
}

static __device__ __forceinline__ float swiglu(float gate __attribute__((unused)), float up __attribute__((unused))) {
  return (silu(gate) * up);
}

static __device__ __forceinline__ float relu(float x __attribute__((unused))) {
  if ((x > 0)) {
    return x;
  } else {
    return 0;
  }
}

static __device__ __forceinline__ float leaky_relu(float x __attribute__((unused)), float alpha __attribute__((unused))) {
  if ((x > 0)) {
    return x;
  } else {
    return (alpha * x);
  }
}

static __device__ __forceinline__ float softplus(float x __attribute__((unused))) {
  float e __attribute__((unused)) = expf(x);
  return logf((1 + e));
}

static __device__ __forceinline__ float gelu(float x __attribute__((unused))) {
  float x3 __attribute__((unused)) = ((x * x) * x);
  float inner __attribute__((unused)) = (0.79788456080000003 * (x + (0.044714999999999998 * x3)));
  float t __attribute__((unused)) = tanhf(inner);
  return ((0.5 * x) * (1 + t));
}

static __device__ __forceinline__ float mish(float x __attribute__((unused))) {
  float sp __attribute__((unused)) = softplus(x);
  return (x * tanhf(sp));
}

static __device__ __forceinline__ float hard_sigmoid(float x __attribute__((unused))) {
  float s __attribute__((unused)) = ((x + 3) * 0.16666666999999999);
  if ((s < 0)) {
    return 0;
  } else {
    if ((s > 1)) {
      return 1;
    } else {
      return s;
    }
  }
}

static __device__ __forceinline__ float hard_silu(float x __attribute__((unused))) {
  return (x * hard_sigmoid(x));
}

static __device__ __forceinline__ __forge_tuple_u32_u32_t philox_round(uint32_t ctr0 __attribute__((unused)), uint32_t ctr1 __attribute__((unused)), uint32_t key __attribute__((unused))) {
  uint64_t m64 __attribute__((unused)) = ((uint64_t)PHILOX_M2x32);
  uint64_t c0_64 __attribute__((unused)) = ((uint64_t)ctr0);
  uint64_t prod __attribute__((unused)) = (m64 * c0_64);
  uint32_t hi __attribute__((unused)) = ((uint32_t)(prod >> 32ULL));
  uint32_t lo __attribute__((unused)) = ((uint32_t)(prod & 4294967295ULL));
  uint32_t new_ctr0 __attribute__((unused)) = ((hi ^ key) ^ ctr1);
  return FORGE_AGG(__forge_tuple_u32_u32_t, new_ctr0, lo);
}

static __device__ __forceinline__ uint32_t philox_bump_key(uint32_t key __attribute__((unused))) {
  return (key + PHILOX_W);
}

static __device__ __forceinline__ __forge_tuple_u32_u32_t philox_2x32_10(uint32_t key0 __attribute__((unused)), uint32_t key1 __attribute__((unused)), uint32_t ctr0 __attribute__((unused)), uint32_t ctr1 __attribute__((unused))) {
  (void)(key1);
  uint32_t k __attribute__((unused)) = key0;
  uint32_t c0 __attribute__((unused)) = ctr0;
  uint32_t c1 __attribute__((unused)) = ctr1;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < 10ULL)) {
      __forge_tuple_u32_u32_t __tup_62_8 __attribute__((unused)) = philox_round(c0, c1, k);
      uint32_t n0 __attribute__((unused)) = (__tup_62_8)._0;
      uint32_t n1 __attribute__((unused)) = (__tup_62_8)._1;
      c0 = n0;
      c1 = n1;
      k = philox_bump_key(k);
      i = (i + 1ULL);
    }

  }
  return FORGE_AGG(__forge_tuple_u32_u32_t, c0, c1);
}

static __device__ __forceinline__ float philox_to_uniform_f32(uint32_t u __attribute__((unused))) {
  uint32_t mantissa __attribute__((unused)) = (u >> 8ULL);
  float mant_f __attribute__((unused)) = ((float)mantissa);
  return (mant_f * 5.9604645000000006e-08);
}

static __device__ __forceinline__ uint32_t philox_bernoulli_keep_u32(uint32_t u __attribute__((unused)), uint32_t p_threshold_u32 __attribute__((unused))) {
  if ((u < p_threshold_u32)) {
    return 0ULL;
  } else {
    return 1ULL;
  }
}

__global__ void ffn_swiglu_dropout(forge_span_f32_t gate __attribute__((unused)), forge_span_f32_t up __attribute__((unused)), forge_span_f32_t out __attribute__((unused)), uint64_t n __attribute__((unused)), uint32_t seed_lo __attribute__((unused)), uint32_t seed_hi __attribute__((unused)), uint32_t p_threshold __attribute__((unused)), float keep_scale __attribute__((unused))) {
  uint64_t gid __attribute__((unused)) = ((blockIdx_x * ((uint64_t)blockDim_x)) + ((uint64_t)threadIdx_x));
  if ((gid < n)) {
    float gated __attribute__((unused)) = swiglu(gate.data[gid], up.data[gid]);
    uint32_t gid_lo __attribute__((unused)) = ((uint32_t)gid);
    uint32_t gid_hi __attribute__((unused)) = ((uint32_t)(gid >> 32ULL));
    __forge_tuple_u32_u32_t __tup_36_8 __attribute__((unused)) = philox_2x32_10(seed_lo, seed_hi, gid_lo, gid_hi);
    uint32_t rnd __attribute__((unused)) = (__tup_36_8)._0;
    (void)((__tup_36_8)._1);
    uint32_t keep __attribute__((unused)) = philox_bernoulli_keep_u32(rnd, p_threshold);
    float kept;
    if ((keep == 0ULL)) {
      kept = 0;
    } else {
      kept = (gated * keep_scale);
    }
    out.data[gid] = kept;

  }
}

int main() {
  return (int)(0);

}

