/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t span_sum(forge_span_u64_t s __attribute__((unused)));
uint64_t all_below(forge_span_u64_t s __attribute__((unused)), uint64_t bound __attribute__((unused)));
uint64_t count_equal(forge_span_u64_t s __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t find_first(forge_span_u64_t s __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t span_len(forge_span_u64_t s __attribute__((unused)));
uint64_t span_first(forge_span_u64_t s __attribute__((unused)));
uint64_t span_last(forge_span_u64_t s __attribute__((unused)));
int main();

uint64_t span_sum(forge_span_u64_t s __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < s.len)) {
      acc = (acc + s.data[i]);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t all_below(forge_span_u64_t s __attribute__((unused)), uint64_t bound __attribute__((unused))) {
  uint64_t ok __attribute__((unused)) = 1ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < s.len)) {
      if ((s.data[i] >= bound)) {
        ok = 0ULL;

      }
      i = (i + 1ULL);
    }

  }
  return ok;
}

uint64_t count_equal(forge_span_u64_t s __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < s.len)) {
      if ((s.data[i] == target)) {
        cnt = (cnt + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return cnt;
}

uint64_t find_first(forge_span_u64_t s __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t idx __attribute__((unused)) = s.len;
  uint64_t i __attribute__((unused)) = 0ULL;
  uint64_t found __attribute__((unused)) = 0ULL;
  {
    while ((i < s.len)) {
      if (((s.data[i] == target) && (found == 0ULL))) {
        idx = i;
        found = 1ULL;

      }
      i = (i + 1ULL);
    }

  }
  return idx;
}

uint64_t span_len(forge_span_u64_t s __attribute__((unused))) {
  return s.len;
}

uint64_t span_first(forge_span_u64_t s __attribute__((unused))) {
  return s.data[0ULL];
}

uint64_t span_last(forge_span_u64_t s __attribute__((unused))) {
  return s.data[(s.len - 1ULL)];
}

int main() {
  uint64_t sl __attribute__((unused)) = 5ULL;
  uint64_t sl2 __attribute__((unused)) = 3ULL;
  uint64_t r_sl __attribute__((unused)) = sl;
  return (int)((sl + sl2));

}

