/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void selection_sort(forge_span_u64_t s __attribute__((unused)));
int main();

void selection_sort(forge_span_u64_t s __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = s.len;
  uint64_t k __attribute__((unused)) = 0;
  {
    while ((k < n)) {
      uint64_t min_idx __attribute__((unused)) = k;
      uint64_t m __attribute__((unused)) = s.data[k];
      uint64_t idx __attribute__((unused)) = (k + 1);
      {
        while ((idx < n)) {
          if ((s.data[idx] < m)) {
            min_idx = idx;
            m = s.data[idx];

          }
          idx = (idx + 1);
        }

      }
      uint64_t old_k __attribute__((unused)) = s.data[k];
      s.data[k] = s.data[min_idx];
      s.data[min_idx] = old_k;
      k = (k + 1);
    }

  }
}

int main() {
  return (int)(0);

}

