/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void clamp_array(forge_span_u64_t s __attribute__((unused)), uint64_t max_val __attribute__((unused)));
int main();

void clamp_array(forge_span_u64_t s __attribute__((unused)), uint64_t max_val __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = s.len;
  uint64_t k __attribute__((unused)) = 0;
  {
    while ((k < n)) {
      if ((s.data[k] > max_val)) {
        s.data[k] = max_val;

      }
      k = (k + 1);
    }

  }
}

int main() {
  return (int)(0);

}

