/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void bubble_sort_natural(forge_span_u64_t s __attribute__((unused)));
int main();

void bubble_sort_natural(forge_span_u64_t s __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = s.len;
  uint64_t k __attribute__((unused)) = 0ULL;
  {
    while ((k < n)) {
      uint64_t bound __attribute__((unused)) = ((n - k) - 1ULL);
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j < bound)) {
          if ((s.data[j] > s.data[(j + 1ULL)])) {
            uint64_t tmp __attribute__((unused)) = s.data[j];
            s.data[j] = s.data[(j + 1ULL)];
            s.data[(j + 1ULL)] = tmp;

          }
          j = (j + 1ULL);
        }

      }
      k = (k + 1ULL);
    }

  }
}

int main() {
  return (int)(0ULL);

}

