/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

/* Forward declarations */
uint64_t count_down(uint64_t x __attribute__((unused)));
uint64_t triangular(uint64_t n __attribute__((unused)));
uint64_t count_down_to_zero(uint64_t x __attribute__((unused)));

uint64_t count_down(uint64_t x __attribute__((unused))) {
  uint64_t v = x;
  {
    while ((v > 0)) {
      v = (v - 1);
    }

  }
  return v;
}

uint64_t triangular(uint64_t n __attribute__((unused))) {
  uint64_t acc = 0;
  uint64_t i = 0;
  {
    while ((i <= n)) {
      acc = (acc + i);
      i = (i + 1);
    }

  }
  return acc;
}

uint64_t count_down_to_zero(uint64_t x __attribute__((unused))) {
  uint64_t v = x;
  {
    while ((v > 0)) {
      v = (v - 1);
    }

  }
  return v;
}

