/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
_Bool two_sum_exists(forge_span_u64_t s __attribute__((unused)), uint64_t target __attribute__((unused)));
int main();

_Bool two_sum_exists(forge_span_u64_t s __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = s.len;
  uint64_t i __attribute__((unused)) = 0;
  _Bool found __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      uint64_t j __attribute__((unused)) = (i + 1);
      {
        while ((j < n)) {
          if (((s.data[i] + s.data[j]) == target)) {
            found = 1;

          }
          j = (j + 1);
        }

      }
      i = (i + 1);
    }

  }
  return found;
}

int main() {
  return (int)(0);

}

