/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t running_mean(forge_span_u64_t s __attribute__((unused)), uint64_t max_elem __attribute__((unused)));
int main();

uint64_t running_mean(forge_span_u64_t s __attribute__((unused)), uint64_t max_elem __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = s.len;
  uint64_t gsum __attribute__((unused)) = 0ULL;
  uint64_t k __attribute__((unused)) = 0ULL;
  uint64_t acc __attribute__((unused)) = 0ULL;
  {
    while ((k < n)) {
      acc = (acc + s.data[k]);
      gsum = (gsum + s.data[k]);
      k = (k + 1ULL);
    }

  }
  return (acc / n);
}

int main() {
  return (int)(0ULL);

}

