/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void insertion_sort(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

void insertion_sort(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  {
    for (uint64_t i = 0; i < (uint64_t)(n); i++) {
      uint64_t key __attribute__((unused)) = s.data[i];
      uint64_t j __attribute__((unused)) = i;
      {
        while ((j > 0ULL)) {
          if ((s.data[(j - 1ULL)] > key)) {
            s.data[j] = s.data[(j - 1ULL)];
            j = (j - 1ULL);

          } else {
            j = 0ULL;

          }
        }

      }
      s.data[j] = key;
    }

  }
}

int main() {
  return (int)(0ULL);

}

