/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t bounded_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
int main();

uint64_t bounded_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  /* assert erased */;
  return (a + b);
}

int main() {
  return (int)(0ULL);

}

