/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct BoundedCounter {
  uint64_t count;
  uint64_t max;
} BoundedCounter;

/* Forward declarations */
BoundedCounter make_counter(uint64_t limit __attribute__((unused)));
BoundedCounter increment(BoundedCounter c __attribute__((unused)));
int main();

BoundedCounter make_counter(uint64_t limit __attribute__((unused))) {
  return (BoundedCounter){ .count = 0, .max = limit };
}

BoundedCounter increment(BoundedCounter c __attribute__((unused))) {
  return (BoundedCounter){ .count = (c.count + 1), .max = c.max };
}

int main() {
  return (int)(0);

}

