/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void merge_step(forge_span_u64_t dst __attribute__((unused)), forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t na __attribute__((unused)), uint64_t nb __attribute__((unused)));
int main();

void merge_step(forge_span_u64_t dst __attribute__((unused)), forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t na __attribute__((unused)), uint64_t nb __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  uint64_t j __attribute__((unused)) = 0ULL;
  uint64_t k __attribute__((unused)) = 0ULL;
  {
    for (uint64_t _step = 0; _step < (uint64_t)((na + nb)); _step++) {
      if ((i >= na)) {
        dst.data[k] = b.data[j];
        j = (j + 1ULL);

      } else if ((j >= nb)) {
        dst.data[k] = a.data[i];
        i = (i + 1ULL);

      } else {
        dst.data[k] = a.data[i];
        i = (i + 1ULL);

      }
      k = (k + 1ULL);
    }

  }
}

int main() {
  return (int)(0ULL);

}

