/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
_Bool contains(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
int main();

_Bool contains(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t k __attribute__((unused)) = 0;
  _Bool found __attribute__((unused)) = 0;
  {
    while ((k < n)) {
      if ((s.data[k] == target)) {
        found = 1;

      }
      k = (k + 1);
    }

  }
  return found;
}

int main() {
  return (int)(0);

}

