/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);

/* Forward declarations */
uint64_t clamp_range(uint64_t x __attribute__((unused)));
void map_safe(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_fn_u64_ret_u64_t f __attribute__((unused)));
void demo(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t clamp_range(uint64_t x __attribute__((unused))) {
  if ((x > 255ULL)) {
    return 255ULL;
  } else {
    return x;
  }
}

void map_safe(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_fn_u64_ret_u64_t f __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t v __attribute__((unused)) = f(s.data[i]);
      s.data[i] = v;
      i = (i + 1ULL);
    }

  }
}

void demo(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  map_safe(s, n, clamp_range);
}

int main() {
  return (int)(0ULL);

}

