/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t nibbles(uint64_t x __attribute__((unused)));
uint64_t upper4(uint64_t x __attribute__((unused)));
uint64_t hash_slot(uint64_t key __attribute__((unused)), uint64_t cap __attribute__((unused)));
uint64_t extract_byte_field(uint64_t word __attribute__((unused)));
uint64_t make_u16(uint8_t hi __attribute__((unused)), uint8_t lo __attribute__((unused)));
uint64_t low_byte(uint64_t word __attribute__((unused)));
uint64_t strided_base(uint64_t idx __attribute__((unused)), uint64_t stride __attribute__((unused)));
uint64_t strided_offset(uint64_t idx __attribute__((unused)), uint64_t stride __attribute__((unused)));
int main();

uint64_t nibbles(uint64_t x __attribute__((unused))) {
  return (x % 16ULL);
}

uint64_t upper4(uint64_t x __attribute__((unused))) {
  return (x / 16ULL);
}

uint64_t hash_slot(uint64_t key __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  return (key % cap);
}

uint64_t extract_byte_field(uint64_t word __attribute__((unused))) {
  return (word % 256ULL);
}

uint64_t make_u16(uint8_t hi __attribute__((unused)), uint8_t lo __attribute__((unused))) {
  uint64_t h __attribute__((unused)) = ((uint64_t)hi);
  uint64_t l __attribute__((unused)) = ((uint64_t)lo);
  return ((h * 256ULL) + l);
}

uint64_t low_byte(uint64_t word __attribute__((unused))) {
  return (word % 256ULL);
}

uint64_t strided_base(uint64_t idx __attribute__((unused)), uint64_t stride __attribute__((unused))) {
  return (idx / stride);
}

uint64_t strided_offset(uint64_t idx __attribute__((unused)), uint64_t stride __attribute__((unused))) {
  return (idx % stride);
}

int main() {
  return (int)(0ULL);

}

