/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <stdint.h>
#include <stdbool.h>

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))


/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t sum_n(forge_span_u64_t src , uint64_t n );
void fill_u64(forge_span_u64_t dst , uint64_t val , uint64_t n );
__global__ void reduce_sum(forge_span_u64_t src , forge_span_u64_t dst , uint64_t num_blocks , uint64_t block_size );

uint64_t sum_n(forge_span_u64_t src , uint64_t n ) {
  uint64_t k = 0;
  uint64_t s = 0;
  {
    while ((k < n)) {
      s = (s + src.data[k]);
      k = (k + 1);
    }

  }
  return s;
}

void fill_u64(forge_span_u64_t dst , uint64_t val , uint64_t n ) {
  uint64_t k = 0;
  {
    while ((k < n)) {
      dst.data[k] = val;
      k = (k + 1);
    }

  }
}

__global__ void reduce_sum(forge_span_u64_t src , forge_span_u64_t dst , uint64_t num_blocks , uint64_t block_size ) {
  __shared__ uint64_t smem[block_size];
  uint64_t tid = threadIdx_x;
  uint64_t bid = blockIdx_x;
  uint64_t gid = ((bid * block_size) + tid);
  if ((gid < src.len)) {
    smem[tid] = src.data[gid];

  }
  __syncthreads();
  uint64_t stride = (block_size / 2);
  {
    while ((stride > 0)) {
      if ((tid < stride)) {
        smem[tid] = (smem[tid] + smem[(tid + stride)]);

      }
      __syncthreads();
      stride = (stride / 2);
    }

  }
  if ((tid == 0)) {
    if ((bid < dst.len)) {
      dst.data[bid] = smem[0];

    };
  }
}

