/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct RingBuf {
  uint64_t head;
  uint64_t tail;
  uint64_t count;
  uint64_t cap;
  uint64_t state;
} RingBuf;

/* Forward declarations */
RingBuf rbuf_new(uint64_t cap __attribute__((unused)));
void rbuf_push(RingBuf* b __attribute__((unused)));
void rbuf_pop(RingBuf* b __attribute__((unused)));
uint64_t rbuf_count(RingBuf* b __attribute__((unused)));
uint64_t starts_empty(uint64_t cap __attribute__((unused)));
uint64_t push_one(uint64_t cap __attribute__((unused)));
uint64_t push_pop_count(uint64_t cap __attribute__((unused)));
uint64_t push_pop_state(uint64_t cap __attribute__((unused)));
int main();

RingBuf rbuf_new(uint64_t cap __attribute__((unused))) {
  return (RingBuf){ .head = 0, .tail = 0, .count = 0, .cap = cap, .state = 0 };
}

void rbuf_push(RingBuf* b __attribute__((unused))) {
  (*b).tail = (((*b).tail + 1) % (*b).cap);
  (*b).count = ((*b).count + 1);
  (*b).state = (((*b).count == (*b).cap) ? 2 : 1);
}

void rbuf_pop(RingBuf* b __attribute__((unused))) {
  (*b).head = (((*b).head + 1) % (*b).cap);
  (*b).count = ((*b).count - 1);
  (*b).state = (((*b).count == 0) ? 0 : 1);
}

uint64_t rbuf_count(RingBuf* b __attribute__((unused))) {
  return (*b).count;
}

uint64_t starts_empty(uint64_t cap __attribute__((unused))) {
  RingBuf b __attribute__((unused)) = rbuf_new(cap);
  return b.state;
}

uint64_t push_one(uint64_t cap __attribute__((unused))) {
  RingBuf b __attribute__((unused)) = rbuf_new(cap);
  rbuf_push((&b));
  return b.count;
}

uint64_t push_pop_count(uint64_t cap __attribute__((unused))) {
  RingBuf b __attribute__((unused)) = rbuf_new(cap);
  rbuf_push((&b));
  rbuf_pop((&b));
  return b.count;
}

uint64_t push_pop_state(uint64_t cap __attribute__((unused))) {
  RingBuf b __attribute__((unused)) = rbuf_new(cap);
  rbuf_push((&b));
  rbuf_pop((&b));
  return b.state;
}

int main() {
  return (int)(0);

}

