/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct Interval {
  uint64_t lo;
  uint64_t hi;
} Interval;

/* Forward declarations */
Interval interval_new(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t interval_width(Interval iv __attribute__((unused)));
uint64_t interval_contains(Interval iv __attribute__((unused)), uint64_t x __attribute__((unused)));
uint64_t interval_midpoint(Interval iv __attribute__((unused)));
uint64_t interval_lo_max(Interval a __attribute__((unused)), Interval b __attribute__((unused)));
uint64_t interval_hi_min(Interval a __attribute__((unused)), Interval b __attribute__((unused)));
uint64_t intervals_overlap(Interval a __attribute__((unused)), Interval b __attribute__((unused)));
uint64_t interval_clamp(Interval iv __attribute__((unused)), uint64_t x __attribute__((unused)));
int main();

Interval interval_new(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  return (Interval){ .lo = lo, .hi = hi };
}

uint64_t interval_width(Interval iv __attribute__((unused))) {
  return (iv.hi - iv.lo);
}

uint64_t interval_contains(Interval iv __attribute__((unused)), uint64_t x __attribute__((unused))) {
  if (((iv.lo <= x) && (x <= iv.hi))) {
    return 1;
  } else {
    return 0;
  }
}

uint64_t interval_midpoint(Interval iv __attribute__((unused))) {
  return (iv.lo + ((iv.hi - iv.lo) / 2));
}

uint64_t interval_lo_max(Interval a __attribute__((unused)), Interval b __attribute__((unused))) {
  if ((a.lo >= b.lo)) {
    return a.lo;
  } else {
    return b.lo;
  }
}

uint64_t interval_hi_min(Interval a __attribute__((unused)), Interval b __attribute__((unused))) {
  if ((a.hi <= b.hi)) {
    return a.hi;
  } else {
    return b.hi;
  }
}

uint64_t intervals_overlap(Interval a __attribute__((unused)), Interval b __attribute__((unused))) {
  uint64_t max_lo;
  if ((a.lo >= b.lo)) {
    max_lo = a.lo;
  } else {
    max_lo = b.lo;
  }
  uint64_t min_hi;
  if ((a.hi <= b.hi)) {
    min_hi = a.hi;
  } else {
    min_hi = b.hi;
  }
  if ((max_lo <= min_hi)) {
    return 1;
  } else {
    return 0;
  }
}

uint64_t interval_clamp(Interval iv __attribute__((unused)), uint64_t x __attribute__((unused))) {
  uint64_t y;
  if ((x < iv.lo)) {
    y = iv.lo;
  } else {
    y = x;
  }
  if ((y > iv.hi)) {
    return iv.hi;
  } else {
    return y;
  }
}

int main() {
  return (int)(0);

}

