/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct PingPong {
  uint64_t pings;
  uint64_t pongs;
  uint64_t turn;
} PingPong;

/* Forward declarations */
PingPong pp_new();
void pp_ping(PingPong* p __attribute__((unused)));
void pp_pong(PingPong* p __attribute__((unused)));
uint64_t one_ping_count();
uint64_t one_ping_turn();
uint64_t one_cycle_pings();
uint64_t one_cycle_pongs();
uint64_t one_cycle_turn();
uint64_t three_cycles_pings();
int main();

PingPong pp_new() {
  return (PingPong){ .pings = 0, .pongs = 0, .turn = 0 };
}

void pp_ping(PingPong* p __attribute__((unused))) {
  (*p).pings = ((*p).pings + 1);
  (*p).turn = 1;
}

void pp_pong(PingPong* p __attribute__((unused))) {
  (*p).pongs = ((*p).pongs + 1);
  (*p).turn = 0;
}

uint64_t one_ping_count() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  return p.pings;
}

uint64_t one_ping_turn() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  return p.turn;
}

uint64_t one_cycle_pings() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  pp_pong((&p));
  return p.pings;
}

uint64_t one_cycle_pongs() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  pp_pong((&p));
  return p.pongs;
}

uint64_t one_cycle_turn() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  pp_pong((&p));
  return p.turn;
}

uint64_t three_cycles_pings() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  pp_pong((&p));
  pp_ping((&p));
  pp_pong((&p));
  pp_ping((&p));
  pp_pong((&p));
  return p.pings;
}

int main() {
  return (int)(0);

}

