/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct Chain {
  uint64_t height;
  uint64_t tx_count;
} Chain;

/* Forward declarations */
Chain chain_new();
void chain_append(Chain* c __attribute__((unused)), uint64_t txs __attribute__((unused)));
uint64_t three_blocks_height();
uint64_t three_blocks_txs();
uint64_t varying_txs();
uint64_t height_is_appends();
int main();

Chain chain_new() {
  return (Chain){ .height = 0, .tx_count = 0 };
}

void chain_append(Chain* c __attribute__((unused)), uint64_t txs __attribute__((unused))) {
  (*c).height = ((*c).height + 1);
  (*c).tx_count = ((*c).tx_count + txs);
}

uint64_t three_blocks_height() {
  Chain c __attribute__((unused)) = chain_new();
  chain_append((&c), 1);
  chain_append((&c), 1);
  chain_append((&c), 1);
  return c.height;
}

uint64_t three_blocks_txs() {
  Chain c __attribute__((unused)) = chain_new();
  chain_append((&c), 1);
  chain_append((&c), 1);
  chain_append((&c), 1);
  return c.tx_count;
}

uint64_t varying_txs() {
  Chain c __attribute__((unused)) = chain_new();
  chain_append((&c), 5);
  chain_append((&c), 10);
  chain_append((&c), 3);
  return c.tx_count;
}

uint64_t height_is_appends() {
  Chain c __attribute__((unused)) = chain_new();
  chain_append((&c), 5);
  chain_append((&c), 10);
  chain_append((&c), 3);
  chain_append((&c), 7);
  return c.height;
}

int main() {
  return (int)(0);

}

