/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct OffsetPtr {
  uint64_t offset;
  uint64_t size;
} OffsetPtr;

/* Forward declarations */
OffsetPtr optr_new(uint64_t size __attribute__((unused)));
void optr_advance(OffsetPtr* p __attribute__((unused)), uint64_t n __attribute__((unused)));
void optr_rewind(OffsetPtr* p __attribute__((unused)), uint64_t n __attribute__((unused)));
void optr_reset(OffsetPtr* p __attribute__((unused)));
uint64_t advance_5(uint64_t size __attribute__((unused)));
uint64_t advance_rewind(uint64_t size __attribute__((unused)));
uint64_t advance_reset(uint64_t size __attribute__((unused)));
uint64_t size_preserved(uint64_t size __attribute__((unused)));
int main();

OffsetPtr optr_new(uint64_t size __attribute__((unused))) {
  return (OffsetPtr){ .offset = 0, .size = size };
}

void optr_advance(OffsetPtr* p __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*p).offset = ((*p).offset + n);
}

void optr_rewind(OffsetPtr* p __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*p).offset = ((*p).offset - n);
}

void optr_reset(OffsetPtr* p __attribute__((unused))) {
  (*p).offset = 0;
}

uint64_t advance_5(uint64_t size __attribute__((unused))) {
  OffsetPtr p __attribute__((unused)) = optr_new(size);
  optr_advance((&p), 5);
  return p.offset;
}

uint64_t advance_rewind(uint64_t size __attribute__((unused))) {
  OffsetPtr p __attribute__((unused)) = optr_new(size);
  optr_advance((&p), 10);
  optr_rewind((&p), 3);
  return p.offset;
}

uint64_t advance_reset(uint64_t size __attribute__((unused))) {
  OffsetPtr p __attribute__((unused)) = optr_new(size);
  optr_advance((&p), 8);
  optr_reset((&p));
  return p.offset;
}

uint64_t size_preserved(uint64_t size __attribute__((unused))) {
  OffsetPtr p __attribute__((unused)) = optr_new(size);
  optr_advance((&p), 5);
  optr_rewind((&p), 2);
  optr_reset((&p));
  return p.size;
}

int main() {
  return (int)(0);

}

