/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct WindowSum {
  uint64_t sum;
  uint64_t count;
  uint64_t window_sz;
  uint64_t flushes;
} WindowSum;

/* Forward declarations */
WindowSum ws_new(uint64_t window_sz __attribute__((unused)));
void ws_add(WindowSum* w __attribute__((unused)), uint64_t v __attribute__((unused)));
void ws_flush(WindowSum* w __attribute__((unused)));
uint64_t three_samples();
uint64_t sample_count();
uint64_t flush_resets_sum();
uint64_t flush_count();
uint64_t two_windows_flushes();
int main();

WindowSum ws_new(uint64_t window_sz __attribute__((unused))) {
  return (WindowSum){ .sum = 0ULL, .count = 0ULL, .window_sz = window_sz, .flushes = 0ULL };
}

void ws_add(WindowSum* w __attribute__((unused)), uint64_t v __attribute__((unused))) {
  (*w).sum = ((*w).sum + v);
  (*w).count = ((*w).count + 1ULL);
}

void ws_flush(WindowSum* w __attribute__((unused))) {
  (*w).sum = 0ULL;
  (*w).count = 0ULL;
  (*w).flushes = ((*w).flushes + 1ULL);
}

uint64_t three_samples() {
  WindowSum w __attribute__((unused)) = ws_new(5ULL);
  ws_add((&w), 10ULL);
  ws_add((&w), 20ULL);
  ws_add((&w), 30ULL);
  return w.sum;
}

uint64_t sample_count() {
  WindowSum w __attribute__((unused)) = ws_new(5ULL);
  ws_add((&w), 10ULL);
  ws_add((&w), 20ULL);
  ws_add((&w), 30ULL);
  return w.count;
}

uint64_t flush_resets_sum() {
  WindowSum w __attribute__((unused)) = ws_new(5ULL);
  ws_add((&w), 10ULL);
  ws_add((&w), 20ULL);
  ws_flush((&w));
  return w.sum;
}

uint64_t flush_count() {
  WindowSum w __attribute__((unused)) = ws_new(5ULL);
  ws_add((&w), 10ULL);
  ws_add((&w), 20ULL);
  ws_flush((&w));
  return w.flushes;
}

uint64_t two_windows_flushes() {
  WindowSum w __attribute__((unused)) = ws_new(3ULL);
  ws_add((&w), 1ULL);
  ws_add((&w), 2ULL);
  ws_add((&w), 3ULL);
  ws_flush((&w));
  ws_add((&w), 4ULL);
  ws_add((&w), 5ULL);
  ws_add((&w), 6ULL);
  ws_flush((&w));
  return w.flushes;
}

int main() {
  return (int)(0ULL);

}

