/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct MulticastGroup {
  uint64_t members;
  uint64_t max_members;
  uint64_t messages;
} MulticastGroup;

/* Forward declarations */
MulticastGroup mg_new(uint64_t max_members __attribute__((unused)));
void mg_join(MulticastGroup* g __attribute__((unused)));
void mg_leave(MulticastGroup* g __attribute__((unused)));
void mg_send(MulticastGroup* g __attribute__((unused)));
uint64_t join_four(uint64_t max __attribute__((unused)));
uint64_t join3_leave1(uint64_t max __attribute__((unused)));
uint64_t send_five(uint64_t max __attribute__((unused)));
uint64_t max_preserved(uint64_t max __attribute__((unused)));
int main();

MulticastGroup mg_new(uint64_t max_members __attribute__((unused))) {
  return (MulticastGroup){ .members = 0ULL, .max_members = max_members, .messages = 0ULL };
}

void mg_join(MulticastGroup* g __attribute__((unused))) {
  (*g).members = ((*g).members + 1ULL);
}

void mg_leave(MulticastGroup* g __attribute__((unused))) {
  (*g).members = ((*g).members - 1ULL);
}

void mg_send(MulticastGroup* g __attribute__((unused))) {
  (*g).messages = ((*g).messages + 1ULL);
}

uint64_t join_four(uint64_t max __attribute__((unused))) {
  MulticastGroup g __attribute__((unused)) = mg_new(max);
  mg_join((&g));
  mg_join((&g));
  mg_join((&g));
  mg_join((&g));
  return g.members;
}

uint64_t join3_leave1(uint64_t max __attribute__((unused))) {
  MulticastGroup g __attribute__((unused)) = mg_new(max);
  mg_join((&g));
  mg_join((&g));
  mg_join((&g));
  mg_leave((&g));
  return g.members;
}

uint64_t send_five(uint64_t max __attribute__((unused))) {
  MulticastGroup g __attribute__((unused)) = mg_new(max);
  mg_join((&g));
  mg_send((&g));
  mg_send((&g));
  mg_send((&g));
  mg_send((&g));
  mg_send((&g));
  return g.messages;
}

uint64_t max_preserved(uint64_t max __attribute__((unused))) {
  MulticastGroup g __attribute__((unused)) = mg_new(max);
  mg_join((&g));
  mg_join((&g));
  mg_leave((&g));
  return g.max_members;
}

int main() {
  return (int)(0ULL);

}

