/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct GCStats {
  uint64_t live;
  uint64_t collected;
  uint64_t gc_cycles;
  uint64_t allocs;
} GCStats;

/* Forward declarations */
GCStats gc_new();
void gc_alloc(GCStats* g __attribute__((unused)));
void gc_collect(GCStats* g __attribute__((unused)), uint64_t freed __attribute__((unused)));
uint64_t alloc_five();
uint64_t collect_three();
uint64_t collected_total();
uint64_t gc_cycle_count();
int main();

GCStats gc_new() {
  return (GCStats){ .live = 0, .collected = 0, .gc_cycles = 0, .allocs = 0 };
}

void gc_alloc(GCStats* g __attribute__((unused))) {
  (*g).live = ((*g).live + 1);
  (*g).allocs = ((*g).allocs + 1);
}

void gc_collect(GCStats* g __attribute__((unused)), uint64_t freed __attribute__((unused))) {
  (*g).live = ((*g).live - freed);
  (*g).collected = ((*g).collected + freed);
  (*g).gc_cycles = ((*g).gc_cycles + 1);
}

uint64_t alloc_five() {
  GCStats g __attribute__((unused)) = gc_new();
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  return g.live;
}

uint64_t collect_three() {
  GCStats g __attribute__((unused)) = gc_new();
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_collect((&g), 3);
  return g.live;
}

uint64_t collected_total() {
  GCStats g __attribute__((unused)) = gc_new();
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_collect((&g), 3);
  gc_alloc((&g));
  gc_alloc((&g));
  gc_collect((&g), 4);
  return g.collected;
}

uint64_t gc_cycle_count() {
  GCStats g __attribute__((unused)) = gc_new();
  gc_alloc((&g));
  gc_alloc((&g));
  gc_alloc((&g));
  gc_collect((&g), 2);
  gc_alloc((&g));
  gc_collect((&g), 2);
  return g.gc_cycles;
}

int main() {
  return (int)(0);

}

