/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct ObjPool {
  uint64_t live;
  uint64_t cap;
  uint64_t generation;
  uint64_t allocs;
  uint64_t frees;
} ObjPool;

/* Forward declarations */
ObjPool op_new(uint64_t cap __attribute__((unused)));
void op_alloc(ObjPool* p __attribute__((unused)));
void op_free(ObjPool* p __attribute__((unused)));
uint64_t alloc_three(uint64_t cap __attribute__((unused)));
uint64_t generation_after_frees();
uint64_t alloc_free_allocs();
uint64_t alloc_free_frees();
int main();

ObjPool op_new(uint64_t cap __attribute__((unused))) {
  return (ObjPool){ .live = 0ULL, .cap = cap, .generation = 0ULL, .allocs = 0ULL, .frees = 0ULL };
}

void op_alloc(ObjPool* p __attribute__((unused))) {
  (*p).live = ((*p).live + 1ULL);
  (*p).allocs = ((*p).allocs + 1ULL);
}

void op_free(ObjPool* p __attribute__((unused))) {
  (*p).live = ((*p).live - 1ULL);
  (*p).generation = ((*p).generation + 1ULL);
  (*p).frees = ((*p).frees + 1ULL);
}

uint64_t alloc_three(uint64_t cap __attribute__((unused))) {
  ObjPool p __attribute__((unused)) = op_new(cap);
  op_alloc((&p));
  op_alloc((&p));
  op_alloc((&p));
  return p.live;
}

uint64_t generation_after_frees() {
  ObjPool p __attribute__((unused)) = op_new(4ULL);
  op_alloc((&p));
  op_alloc((&p));
  op_free((&p));
  op_free((&p));
  return p.generation;
}

uint64_t alloc_free_allocs() {
  ObjPool p __attribute__((unused)) = op_new(4ULL);
  op_alloc((&p));
  op_alloc((&p));
  op_alloc((&p));
  op_alloc((&p));
  op_free((&p));
  op_free((&p));
  op_alloc((&p));
  op_alloc((&p));
  return p.allocs;
}

uint64_t alloc_free_frees() {
  ObjPool p __attribute__((unused)) = op_new(4ULL);
  op_alloc((&p));
  op_alloc((&p));
  op_alloc((&p));
  op_alloc((&p));
  op_free((&p));
  op_free((&p));
  op_alloc((&p));
  return p.frees;
}

int main() {
  return (int)(0ULL);

}

