/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct TrieNode {
  uint64_t prefix_count;
  uint64_t terminal_count;
  uint64_t children;
} TrieNode;

/* Forward declarations */
TrieNode trie_new();
void trie_pass_through(TrieNode* t __attribute__((unused)));
void trie_terminal(TrieNode* t __attribute__((unused)));
void trie_add_child(TrieNode* t __attribute__((unused)));
uint64_t five_pass_through();
uint64_t mixed_inserts_prefix();
uint64_t mixed_inserts_terminal();
uint64_t children_count();
int main();

TrieNode trie_new() {
  return (TrieNode){ .prefix_count = 0ULL, .terminal_count = 0ULL, .children = 0ULL };
}

void trie_pass_through(TrieNode* t __attribute__((unused))) {
  (*t).prefix_count = ((*t).prefix_count + 1ULL);
}

void trie_terminal(TrieNode* t __attribute__((unused))) {
  (*t).prefix_count = ((*t).prefix_count + 1ULL);
  (*t).terminal_count = ((*t).terminal_count + 1ULL);
}

void trie_add_child(TrieNode* t __attribute__((unused))) {
  (*t).children = ((*t).children + 1ULL);
}

uint64_t five_pass_through() {
  TrieNode t __attribute__((unused)) = trie_new();
  trie_pass_through((&t));
  trie_pass_through((&t));
  trie_pass_through((&t));
  trie_pass_through((&t));
  trie_pass_through((&t));
  return t.prefix_count;
}

uint64_t mixed_inserts_prefix() {
  TrieNode t __attribute__((unused)) = trie_new();
  trie_pass_through((&t));
  trie_pass_through((&t));
  trie_pass_through((&t));
  trie_terminal((&t));
  trie_terminal((&t));
  return t.prefix_count;
}

uint64_t mixed_inserts_terminal() {
  TrieNode t __attribute__((unused)) = trie_new();
  trie_pass_through((&t));
  trie_pass_through((&t));
  trie_pass_through((&t));
  trie_terminal((&t));
  trie_terminal((&t));
  return t.terminal_count;
}

uint64_t children_count() {
  TrieNode t __attribute__((unused)) = trie_new();
  trie_add_child((&t));
  trie_add_child((&t));
  trie_add_child((&t));
  return t.children;
}

int main() {
  return (int)(0ULL);

}

