/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct LCG {
  uint64_t state;
  uint64_t a;
  uint64_t c;
  uint64_t steps;
} LCG;

/* Forward declarations */
LCG lcg_new(uint64_t seed __attribute__((unused)), uint64_t a __attribute__((unused)), uint64_t c __attribute__((unused)));
void lcg_step(LCG* g __attribute__((unused)));
uint64_t one_step_state();
uint64_t two_steps_state();
uint64_t step_count();
uint64_t params_preserved();
uint64_t increment_lcg();
int main();

LCG lcg_new(uint64_t seed __attribute__((unused)), uint64_t a __attribute__((unused)), uint64_t c __attribute__((unused))) {
  return (LCG){ .state = seed, .a = a, .c = c, .steps = 0ULL };
}

void lcg_step(LCG* g __attribute__((unused))) {
  (*g).state = (((*g).a * (*g).state) + (*g).c);
  (*g).steps = ((*g).steps + 1ULL);
}

uint64_t one_step_state() {
  LCG g __attribute__((unused)) = lcg_new(1ULL, 5ULL, 8ULL);
  lcg_step((&g));
  return g.state;
}

uint64_t two_steps_state() {
  LCG g __attribute__((unused)) = lcg_new(1ULL, 5ULL, 8ULL);
  lcg_step((&g));
  lcg_step((&g));
  return g.state;
}

uint64_t step_count() {
  LCG g __attribute__((unused)) = lcg_new(0ULL, 3ULL, 1ULL);
  lcg_step((&g));
  lcg_step((&g));
  lcg_step((&g));
  lcg_step((&g));
  return g.steps;
}

uint64_t params_preserved() {
  LCG g __attribute__((unused)) = lcg_new(0ULL, 7ULL, 3ULL);
  lcg_step((&g));
  lcg_step((&g));
  return g.a;
}

uint64_t increment_lcg() {
  LCG g __attribute__((unused)) = lcg_new(0ULL, 1ULL, 1ULL);
  lcg_step((&g));
  lcg_step((&g));
  lcg_step((&g));
  lcg_step((&g));
  lcg_step((&g));
  return g.state;
}

int main() {
  return (int)(0ULL);

}

