/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t add_mod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t q __attribute__((unused)));
uint64_t sub_mod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t q __attribute__((unused)));
uint64_t mul_mod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t q __attribute__((unused)));
void poly_reduce(forge_span_u64_t a __attribute__((unused)), uint64_t q __attribute__((unused)));
void poly_add(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t q __attribute__((unused)));
void poly_sub(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t q __attribute__((unused)));
void poly_scalar_mul(forge_span_u64_t a __attribute__((unused)), uint64_t s __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t q __attribute__((unused)));
uint64_t poly_inner_product(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t q __attribute__((unused)));
void poly_ntt_pointwise(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t q __attribute__((unused)));
uint64_t run();

uint64_t add_mod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t q __attribute__((unused))) {
  uint64_t c __attribute__((unused)) = (a + b);
  if ((c >= q)) {
    return (c - q);
  } else {
    return c;
  }
}

uint64_t sub_mod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t q __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return ((a + q) - b);
  }
}

uint64_t mul_mod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t q __attribute__((unused))) {
  return ((a * b) % q);
}

void poly_reduce(forge_span_u64_t a __attribute__((unused)), uint64_t q __attribute__((unused))) {
  {
    for (uint64_t i = 0; i < (uint64_t)(a.len); i++) {
      a.data[i] = (a.data[i] % q);
    }

  }
}

void poly_add(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t q __attribute__((unused))) {
  {
    for (uint64_t i = 0; i < (uint64_t)(c.len); i++) {
      c.data[i] = ((a.data[i] + b.data[i]) % q);
    }

  }
}

void poly_sub(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t q __attribute__((unused))) {
  {
    for (uint64_t i = 0; i < (uint64_t)(c.len); i++) {
      c.data[i] = (((a.data[i] + q) - (b.data[i] % q)) % q);
    }

  }
}

void poly_scalar_mul(forge_span_u64_t a __attribute__((unused)), uint64_t s __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t q __attribute__((unused))) {
  {
    for (uint64_t i = 0; i < (uint64_t)(b.len); i++) {
      b.data[i] = ((a.data[i] * s) % q);
    }

  }
}

uint64_t poly_inner_product(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t q __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = ((acc + ((a.data[i] * b.data[i]) % q)) % q);
      i = (i + 1ULL);
    }

  }
  return acc;
}

void poly_ntt_pointwise(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t c __attribute__((unused)), uint64_t q __attribute__((unused))) {
  {
    for (uint64_t i = 0; i < (uint64_t)(c.len); i++) {
      c.data[i] = ((a.data[i] * b.data[i]) % q);
    }

  }
}

uint64_t run() {
  uint64_t a0 __attribute__((unused)) = 1ULL;
  uint64_t a1 __attribute__((unused)) = 2ULL;
  uint64_t a2 __attribute__((unused)) = 3ULL;
  uint64_t a3 __attribute__((unused)) = 4ULL;
  uint64_t b0 __attribute__((unused)) = 4ULL;
  uint64_t b1 __attribute__((unused)) = 3ULL;
  uint64_t b2 __attribute__((unused)) = 2ULL;
  uint64_t b3 __attribute__((unused)) = 1ULL;
  uint64_t q __attribute__((unused)) = 3329ULL;
  uint64_t r __attribute__((unused)) = ((((((a0 * b0) % q) + ((a1 * b1) % q)) + ((a2 * b2) % q)) + ((a3 * b3) % q)) % q);
  return r;
}

