/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct Owned {
  uint64_t owner_id;
  uint64_t transfer_count;
  uint64_t releases;
} Owned;

/* Forward declarations */
Owned own_new();
void own_claim(Owned* o __attribute__((unused)), uint64_t new_owner __attribute__((unused)));
void own_transfer(Owned* o __attribute__((unused)), uint64_t new_owner __attribute__((unused)));
void own_release(Owned* o __attribute__((unused)));
uint64_t claim_owner1();
uint64_t transfer_chain();
uint64_t transfer_count();
uint64_t release_unowned();
uint64_t release_count();
int main();

Owned own_new() {
  return (Owned){ .owner_id = 0ULL, .transfer_count = 0ULL, .releases = 0ULL };
}

void own_claim(Owned* o __attribute__((unused)), uint64_t new_owner __attribute__((unused))) {
  (*o).owner_id = new_owner;
  (*o).transfer_count = ((*o).transfer_count + 1ULL);
}

void own_transfer(Owned* o __attribute__((unused)), uint64_t new_owner __attribute__((unused))) {
  (*o).owner_id = new_owner;
  (*o).transfer_count = ((*o).transfer_count + 1ULL);
}

void own_release(Owned* o __attribute__((unused))) {
  (*o).owner_id = 0ULL;
  (*o).releases = ((*o).releases + 1ULL);
}

uint64_t claim_owner1() {
  Owned o __attribute__((unused)) = own_new();
  own_claim((&o), 1ULL);
  return o.owner_id;
}

uint64_t transfer_chain() {
  Owned o __attribute__((unused)) = own_new();
  own_claim((&o), 1ULL);
  own_transfer((&o), 2ULL);
  own_transfer((&o), 3ULL);
  return o.owner_id;
}

uint64_t transfer_count() {
  Owned o __attribute__((unused)) = own_new();
  own_claim((&o), 1ULL);
  own_transfer((&o), 2ULL);
  own_transfer((&o), 3ULL);
  return o.transfer_count;
}

uint64_t release_unowned() {
  Owned o __attribute__((unused)) = own_new();
  own_claim((&o), 5ULL);
  own_transfer((&o), 7ULL);
  own_release((&o));
  return o.owner_id;
}

uint64_t release_count() {
  Owned o __attribute__((unused)) = own_new();
  own_claim((&o), 1ULL);
  own_release((&o));
  own_claim((&o), 2ULL);
  own_release((&o));
  return o.releases;
}

int main() {
  return (int)(0ULL);

}

