/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct AuditLog {
  uint64_t seq;
  uint64_t reads;
  uint64_t writes;
  uint64_t deletes;
} AuditLog;

/* Forward declarations */
AuditLog al_new();
void al_log_read(AuditLog* a __attribute__((unused)));
void al_log_write(AuditLog* a __attribute__((unused)));
void al_log_delete(AuditLog* a __attribute__((unused)));
uint64_t seq_advances();
uint64_t read_count();
uint64_t writes_independent();
uint64_t delete_count();
int main();

AuditLog al_new() {
  return (AuditLog){ .seq = 0ULL, .reads = 0ULL, .writes = 0ULL, .deletes = 0ULL };
}

void al_log_read(AuditLog* a __attribute__((unused))) {
  (*a).seq = ((*a).seq + 1ULL);
  (*a).reads = ((*a).reads + 1ULL);
}

void al_log_write(AuditLog* a __attribute__((unused))) {
  (*a).seq = ((*a).seq + 1ULL);
  (*a).writes = ((*a).writes + 1ULL);
}

void al_log_delete(AuditLog* a __attribute__((unused))) {
  (*a).seq = ((*a).seq + 1ULL);
  (*a).deletes = ((*a).deletes + 1ULL);
}

uint64_t seq_advances() {
  AuditLog a __attribute__((unused)) = al_new();
  al_log_read((&a));
  al_log_write((&a));
  al_log_read((&a));
  al_log_delete((&a));
  return a.seq;
}

uint64_t read_count() {
  AuditLog a __attribute__((unused)) = al_new();
  al_log_read((&a));
  al_log_write((&a));
  al_log_read((&a));
  al_log_delete((&a));
  al_log_read((&a));
  return a.reads;
}

uint64_t writes_independent() {
  AuditLog a __attribute__((unused)) = al_new();
  al_log_read((&a));
  al_log_write((&a));
  al_log_read((&a));
  al_log_write((&a));
  al_log_read((&a));
  return a.writes;
}

uint64_t delete_count() {
  AuditLog a __attribute__((unused)) = al_new();
  al_log_delete((&a));
  al_log_read((&a));
  al_log_write((&a));
  al_log_delete((&a));
  return a.deletes;
}

int main() {
  return (int)(0ULL);

}

