/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct RingCounter {
  uint64_t value;
  uint64_t modulus;
  uint64_t laps;
  uint64_t ticks;
} RingCounter;

/* Forward declarations */
RingCounter rc_new(uint64_t modulus __attribute__((unused)));
void rc_tick(RingCounter* r __attribute__((unused)));
void rc_tick_wrap(RingCounter* r __attribute__((unused)));
uint64_t three_ticks();
uint64_t wrap_resets();
uint64_t two_laps();
uint64_t total_ticks();
int main();

RingCounter rc_new(uint64_t modulus __attribute__((unused))) {
  return (RingCounter){ .value = 0, .modulus = modulus, .laps = 0, .ticks = 0 };
}

void rc_tick(RingCounter* r __attribute__((unused))) {
  (*r).value = ((*r).value + 1);
  (*r).ticks = ((*r).ticks + 1);
}

void rc_tick_wrap(RingCounter* r __attribute__((unused))) {
  (*r).value = 0;
  (*r).laps = ((*r).laps + 1);
  (*r).ticks = ((*r).ticks + 1);
}

uint64_t three_ticks() {
  RingCounter r __attribute__((unused)) = rc_new(5);
  rc_tick((&r));
  rc_tick((&r));
  rc_tick((&r));
  return r.value;
}

uint64_t wrap_resets() {
  RingCounter r __attribute__((unused)) = rc_new(4);
  rc_tick((&r));
  rc_tick((&r));
  rc_tick((&r));
  rc_tick_wrap((&r));
  return r.value;
}

uint64_t two_laps() {
  RingCounter r __attribute__((unused)) = rc_new(3);
  rc_tick((&r));
  rc_tick((&r));
  rc_tick_wrap((&r));
  rc_tick((&r));
  rc_tick((&r));
  rc_tick_wrap((&r));
  return r.laps;
}

uint64_t total_ticks() {
  RingCounter r __attribute__((unused)) = rc_new(3);
  rc_tick((&r));
  rc_tick((&r));
  rc_tick_wrap((&r));
  rc_tick((&r));
  rc_tick((&r));
  rc_tick_wrap((&r));
  return r.ticks;
}

int main() {
  return (int)(0);

}

