/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct FreqTable {
  uint64_t count_a;
  uint64_t count_b;
  uint64_t count_c;
  uint64_t total;
} FreqTable;

/* Forward declarations */
FreqTable ft_new();
void ft_observe_a(FreqTable* f __attribute__((unused)));
void ft_observe_b(FreqTable* f __attribute__((unused)));
void ft_observe_c(FreqTable* f __attribute__((unused)));
uint64_t count_a_two();
uint64_t total_six();
uint64_t sum_invariant();
uint64_t b_independent();
int main();

FreqTable ft_new() {
  return (FreqTable){ .count_a = 0, .count_b = 0, .count_c = 0, .total = 0 };
}

void ft_observe_a(FreqTable* f __attribute__((unused))) {
  (*f).count_a = ((*f).count_a + 1);
  (*f).total = ((*f).total + 1);
}

void ft_observe_b(FreqTable* f __attribute__((unused))) {
  (*f).count_b = ((*f).count_b + 1);
  (*f).total = ((*f).total + 1);
}

void ft_observe_c(FreqTable* f __attribute__((unused))) {
  (*f).count_c = ((*f).count_c + 1);
  (*f).total = ((*f).total + 1);
}

uint64_t count_a_two() {
  FreqTable f __attribute__((unused)) = ft_new();
  ft_observe_a((&f));
  ft_observe_a((&f));
  ft_observe_b((&f));
  ft_observe_b((&f));
  ft_observe_c((&f));
  ft_observe_c((&f));
  return f.count_a;
}

uint64_t total_six() {
  FreqTable f __attribute__((unused)) = ft_new();
  ft_observe_a((&f));
  ft_observe_a((&f));
  ft_observe_b((&f));
  ft_observe_b((&f));
  ft_observe_c((&f));
  ft_observe_c((&f));
  return f.total;
}

uint64_t sum_invariant() {
  FreqTable f __attribute__((unused)) = ft_new();
  ft_observe_a((&f));
  ft_observe_b((&f));
  ft_observe_b((&f));
  ft_observe_c((&f));
  return (((f.total - f.count_a) - f.count_b) - f.count_c);
}

uint64_t b_independent() {
  FreqTable f __attribute__((unused)) = ft_new();
  ft_observe_a((&f));
  ft_observe_a((&f));
  ft_observe_a((&f));
  ft_observe_b((&f));
  ft_observe_b((&f));
  ft_observe_b((&f));
  return f.count_b;
}

int main() {
  return (int)(0);

}

