/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct EpochGC {
  uint64_t epoch;
  uint64_t allocated;
  uint64_t reclaimed;
  uint64_t live;
  uint64_t gc_runs;
} EpochGC;

/* Forward declarations */
EpochGC egc_new();
void egc_alloc(EpochGC* e __attribute__((unused)), uint64_t n __attribute__((unused)));
void egc_collect(EpochGC* e __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t alloc_10();
uint64_t collect_4();
uint64_t live_invariant();
uint64_t epoch_advances();
int main();

EpochGC egc_new() {
  return (EpochGC){ .epoch = 1ULL, .allocated = 0ULL, .reclaimed = 0ULL, .live = 0ULL, .gc_runs = 0ULL };
}

void egc_alloc(EpochGC* e __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*e).allocated = ((*e).allocated + n);
  (*e).live = ((*e).live + n);
}

void egc_collect(EpochGC* e __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*e).reclaimed = ((*e).reclaimed + n);
  (*e).live = ((*e).live - n);
  (*e).epoch = ((*e).epoch + 1ULL);
  (*e).gc_runs = ((*e).gc_runs + 1ULL);
}

uint64_t alloc_10() {
  EpochGC e __attribute__((unused)) = egc_new();
  egc_alloc((&e), 10ULL);
  return e.live;
}

uint64_t collect_4() {
  EpochGC e __attribute__((unused)) = egc_new();
  egc_alloc((&e), 10ULL);
  egc_collect((&e), 4ULL);
  return e.live;
}

uint64_t live_invariant() {
  EpochGC e __attribute__((unused)) = egc_new();
  egc_alloc((&e), 20ULL);
  egc_collect((&e), 8ULL);
  egc_alloc((&e), 5ULL);
  egc_collect((&e), 3ULL);
  return (e.live - (e.allocated - e.reclaimed));
}

uint64_t epoch_advances() {
  EpochGC e __attribute__((unused)) = egc_new();
  egc_alloc((&e), 10ULL);
  egc_collect((&e), 3ULL);
  egc_collect((&e), 2ULL);
  return e.epoch;
}

int main() {
  return (int)(0ULL);

}

