/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct SessionTracker {
  uint64_t active;
  uint64_t total_sessions;
  uint64_t total_duration;
  uint64_t logouts;
} SessionTracker;

/* Forward declarations */
SessionTracker st_new();
void st_login(SessionTracker* s __attribute__((unused)));
void st_logout(SessionTracker* s __attribute__((unused)), uint64_t duration __attribute__((unused)));
uint64_t three_logins();
uint64_t login_logout();
uint64_t duration_sum();
uint64_t total_sessions();
int main();

SessionTracker st_new() {
  return (SessionTracker){ .active = 0, .total_sessions = 0, .total_duration = 0, .logouts = 0 };
}

void st_login(SessionTracker* s __attribute__((unused))) {
  (*s).active = ((*s).active + 1);
  (*s).total_sessions = ((*s).total_sessions + 1);
}

void st_logout(SessionTracker* s __attribute__((unused)), uint64_t duration __attribute__((unused))) {
  (*s).active = ((*s).active - 1);
  (*s).total_duration = ((*s).total_duration + duration);
  (*s).logouts = ((*s).logouts + 1);
}

uint64_t three_logins() {
  SessionTracker s __attribute__((unused)) = st_new();
  st_login((&s));
  st_login((&s));
  st_login((&s));
  return s.active;
}

uint64_t login_logout() {
  SessionTracker s __attribute__((unused)) = st_new();
  st_login((&s));
  st_logout((&s), 100);
  return s.active;
}

uint64_t duration_sum() {
  SessionTracker s __attribute__((unused)) = st_new();
  st_login((&s));
  st_login((&s));
  st_logout((&s), 100);
  st_logout((&s), 150);
  return s.total_duration;
}

uint64_t total_sessions() {
  SessionTracker s __attribute__((unused)) = st_new();
  st_login((&s));
  st_login((&s));
  st_login((&s));
  st_logout((&s), 60);
  return s.total_sessions;
}

int main() {
  return (int)(0);

}

