/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct DrainFill {
  uint64_t level;
  uint64_t capacity;
  uint64_t cycles;
  uint64_t fills;
  uint64_t drains;
} DrainFill;

/* Forward declarations */
DrainFill df_new(uint64_t capacity __attribute__((unused)), uint64_t initial __attribute__((unused)));
void df_fill(DrainFill* d __attribute__((unused)), uint64_t n __attribute__((unused)));
void df_drain(DrainFill* d __attribute__((unused)), uint64_t n __attribute__((unused)));
void df_complete_cycle(DrainFill* d __attribute__((unused)));
uint64_t fill_30();
uint64_t fill_drain();
uint64_t two_cycles();
uint64_t fill_drain_count();
int main();

DrainFill df_new(uint64_t capacity __attribute__((unused)), uint64_t initial __attribute__((unused))) {
  return (DrainFill){ .level = initial, .capacity = capacity, .cycles = 0ULL, .fills = 0ULL, .drains = 0ULL };
}

void df_fill(DrainFill* d __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*d).level = ((*d).level + n);
  (*d).fills = ((*d).fills + 1ULL);
}

void df_drain(DrainFill* d __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*d).level = ((*d).level - n);
  (*d).drains = ((*d).drains + 1ULL);
}

void df_complete_cycle(DrainFill* d __attribute__((unused))) {
  (*d).cycles = ((*d).cycles + 1ULL);
}

uint64_t fill_30() {
  DrainFill d __attribute__((unused)) = df_new(100ULL, 0ULL);
  df_fill((&d), 30ULL);
  return d.level;
}

uint64_t fill_drain() {
  DrainFill d __attribute__((unused)) = df_new(100ULL, 0ULL);
  df_fill((&d), 50ULL);
  df_drain((&d), 20ULL);
  return d.level;
}

uint64_t two_cycles() {
  DrainFill d __attribute__((unused)) = df_new(100ULL, 50ULL);
  df_complete_cycle((&d));
  df_complete_cycle((&d));
  return d.cycles;
}

uint64_t fill_drain_count() {
  DrainFill d __attribute__((unused)) = df_new(100ULL, 0ULL);
  df_fill((&d), 30ULL);
  df_fill((&d), 20ULL);
  df_drain((&d), 10ULL);
  return (d.fills + d.drains);
}

int main() {
  return (int)(0ULL);

}

