/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct ChannelStats {
  uint64_t sent_bytes;
  uint64_t received_bytes;
  uint64_t dropped_bytes;
  uint64_t retransmit_bytes;
  uint64_t total_attempted;
} ChannelStats;

/* Forward declarations */
ChannelStats cs_new();
void cs_send(ChannelStats* c __attribute__((unused)), uint64_t n __attribute__((unused)));
void cs_drop(ChannelStats* c __attribute__((unused)), uint64_t n __attribute__((unused)));
void cs_receive(ChannelStats* c __attribute__((unused)), uint64_t n __attribute__((unused)));
void cs_retransmit(ChannelStats* c __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t send_100();
uint64_t send_drop_total();
uint64_t receive_independent();
uint64_t retransmit_tracked();
int main();

ChannelStats cs_new() {
  return (ChannelStats){ .sent_bytes = 0ULL, .received_bytes = 0ULL, .dropped_bytes = 0ULL, .retransmit_bytes = 0ULL, .total_attempted = 0ULL };
}

void cs_send(ChannelStats* c __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*c).sent_bytes = ((*c).sent_bytes + n);
  (*c).total_attempted = ((*c).total_attempted + n);
}

void cs_drop(ChannelStats* c __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*c).dropped_bytes = ((*c).dropped_bytes + n);
  (*c).total_attempted = ((*c).total_attempted + n);
}

void cs_receive(ChannelStats* c __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*c).received_bytes = ((*c).received_bytes + n);
}

void cs_retransmit(ChannelStats* c __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*c).retransmit_bytes = ((*c).retransmit_bytes + n);
  (*c).total_attempted = ((*c).total_attempted + n);
}

uint64_t send_100() {
  ChannelStats c __attribute__((unused)) = cs_new();
  cs_send((&c), 100ULL);
  return c.sent_bytes;
}

uint64_t send_drop_total() {
  ChannelStats c __attribute__((unused)) = cs_new();
  cs_send((&c), 100ULL);
  cs_drop((&c), 50ULL);
  return c.total_attempted;
}

uint64_t receive_independent() {
  ChannelStats c __attribute__((unused)) = cs_new();
  cs_send((&c), 100ULL);
  cs_receive((&c), 80ULL);
  return c.received_bytes;
}

uint64_t retransmit_tracked() {
  ChannelStats c __attribute__((unused)) = cs_new();
  cs_send((&c), 100ULL);
  cs_retransmit((&c), 30ULL);
  return c.retransmit_bytes;
}

int main() {
  return (int)(0ULL);

}

