/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct WeightedScheduler {
  uint64_t high_dispatched;
  uint64_t low_dispatched;
  uint64_t rounds;
  uint64_t high_weight;
  uint64_t low_weight;
} WeightedScheduler;

/* Forward declarations */
WeightedScheduler ws_new(uint64_t high_w __attribute__((unused)), uint64_t low_w __attribute__((unused)));
void ws_round(WeightedScheduler* w __attribute__((unused)));
uint64_t two_rounds_high();
uint64_t two_rounds_low();
uint64_t round_count();
uint64_t equal_weights();
int main();

WeightedScheduler ws_new(uint64_t high_w __attribute__((unused)), uint64_t low_w __attribute__((unused))) {
  return (WeightedScheduler){ .high_dispatched = 0, .low_dispatched = 0, .rounds = 0, .high_weight = high_w, .low_weight = low_w };
}

void ws_round(WeightedScheduler* w __attribute__((unused))) {
  (*w).high_dispatched = ((*w).high_dispatched + (*w).high_weight);
  (*w).low_dispatched = ((*w).low_dispatched + (*w).low_weight);
  (*w).rounds = ((*w).rounds + 1);
}

uint64_t two_rounds_high() {
  WeightedScheduler w __attribute__((unused)) = ws_new(3, 1);
  ws_round((&w));
  ws_round((&w));
  return w.high_dispatched;
}

uint64_t two_rounds_low() {
  WeightedScheduler w __attribute__((unused)) = ws_new(3, 1);
  ws_round((&w));
  ws_round((&w));
  return w.low_dispatched;
}

uint64_t round_count() {
  WeightedScheduler w __attribute__((unused)) = ws_new(3, 1);
  ws_round((&w));
  ws_round((&w));
  ws_round((&w));
  return w.rounds;
}

uint64_t equal_weights() {
  WeightedScheduler w __attribute__((unused)) = ws_new(2, 2);
  ws_round((&w));
  ws_round((&w));
  return (w.high_dispatched - w.low_dispatched);
}

int main() {
  return (int)(0);

}

