/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#include <string.h>
#include <stdio.h>
#include <math.h>

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef void (*forge_fn_u64_ret_unit_t)(uint64_t);
typedef uint64_t (*forge_fn_u64_u64_ret_u64_t)(uint64_t, uint64_t);
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_u64_i32_u64_ret_u64_t)(uint64_t, int32_t, uint64_t);
typedef int32_t (*forge_fn_u64_u64_u64_ret_i32_t)(uint64_t, uint64_t, uint64_t);
typedef int32_t (*forge_fn_u64_u64_ret_i32_t)(uint64_t, uint64_t);
typedef int32_t (*forge_fn_u64_ret_i32_t)(uint64_t);
typedef int32_t (*forge_fn__ret_i32_t)(void);
typedef uint64_t (*forge_fn_u64_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t, uint64_t);
typedef void (*forge_fn__ret_unit_t)(void);
typedef void (*forge_fn_i32_ret_unit_t)(int32_t);
typedef double (*forge_fn_f64_ret_f64_t)(double);
typedef double (*forge_fn_f64_f64_ret_f64_t)(double, double);
typedef float (*forge_fn_f32_ret_f32_t)(float);
typedef float (*forge_fn_f32_f32_ret_f32_t)(float, float);

/* Forward declarations */
void print_char(uint64_t c __attribute__((unused)));
void print_newline();
void print_u64(uint64_t n __attribute__((unused)));
void println_u64(uint64_t n __attribute__((unused)));
void print_i64(int64_t n __attribute__((unused)));
void println_i64(int64_t n __attribute__((unused)));
void print_hex_nibble(uint64_t v __attribute__((unused)));
void print_hex_u64(uint64_t n __attribute__((unused)));
void print_hex_u64_padded(uint64_t n __attribute__((unused)));
void print_hex(uint64_t n __attribute__((unused)));
void print_bool(_Bool b __attribute__((unused)));
void flush_stdout();
uint64_t min64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t max64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t clamp64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t pow64(uint64_t base __attribute__((unused)), uint64_t exp __attribute__((unused)));
uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t round_up(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t gcd64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
_Bool is_pow2(uint64_t n __attribute__((unused)));
uint64_t popcount64(uint64_t n __attribute__((unused)));
uint64_t floor_log2(uint64_t n __attribute__((unused)));
int main();

void print_char(uint64_t c __attribute__((unused))) {
  putchar(c);
}

void print_newline() {
  putchar(10);
}

void print_u64(uint64_t n __attribute__((unused))) {
  if ((n >= 10)) {
    print_u64((n / 10));

  }
  putchar((48 + (n % 10)));
}

void println_u64(uint64_t n __attribute__((unused))) {
  print_u64(n);
  print_newline();
}

void print_i64(int64_t n __attribute__((unused))) {
  if ((n < 0)) {
    putchar(45);
    print_u64((0 - ((uint64_t)n)));

  } else {
    print_u64(((uint64_t)n));

  }
}

void println_i64(int64_t n __attribute__((unused))) {
  print_i64(n);
  print_newline();
}

void print_hex_nibble(uint64_t v __attribute__((unused))) {
  if ((v < 10)) {
    putchar((48 + v));

  } else {
    putchar((87 + v));

  }
}

void print_hex_u64(uint64_t n __attribute__((unused))) {
  if ((n >= 16)) {
    print_hex_u64((n / 16));

  }
  print_hex_nibble((n % 16));
}

void print_hex_u64_padded(uint64_t n __attribute__((unused))) {
  uint64_t shift __attribute__((unused)) = 60;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < 16)) {
      uint64_t nibble __attribute__((unused)) = ((n >> (60 - (i * 4))) & 15);
      print_hex_nibble(nibble);
      i = (i + 1);
    }

  }
}

void print_hex(uint64_t n __attribute__((unused))) {
  putchar(48);
  putchar(120);
  if ((n == 0)) {
    putchar(48);

  } else {
    print_hex_u64(n);

  }
}

void print_bool(_Bool b __attribute__((unused))) {
  if (b) {
    putchar(116);
    putchar(114);
    putchar(117);
    putchar(101);

  } else {
    putchar(102);
    putchar(97);
    putchar(108);
    putchar(115);
    putchar(101);

  }
}

void flush_stdout() {
  fflush(0);
}

uint64_t min64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t max64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t clamp64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  if ((v < lo)) {
    return lo;
  } else {
    if ((v > hi)) {
      return hi;
    } else {
      return v;
    }
  }
}

uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return (b - a);
  }
}

uint64_t pow64(uint64_t base __attribute__((unused)), uint64_t exp __attribute__((unused))) {
  if ((exp == 0)) {
    return 1;
  } else {
    return (base * pow64(base, (exp - 1)));
  }
}

uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (((a + b) - 1) / b);
}

uint64_t round_up(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (ceil_div(a, b) * b);
}

uint64_t gcd64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((b == 0)) {
    return a;
  } else {
    return gcd64(b, (a % b));
  }
}

uint64_t sat_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a > (-1 - b))) {
    return -1;
  } else {
    return (a + b);
  }
}

uint64_t sat_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a < b)) {
    return 0;
  } else {
    return (a - b);
  }
}

uint64_t sat_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((b == 0)) {
    return 0;
  } else {
    if ((a > (-1 / b))) {
      return -1;
    } else {
      return (a * b);
    }
  }
}

_Bool is_pow2(uint64_t n __attribute__((unused))) {
  return ((n & (n - 1)) == 0);
}

uint64_t popcount64(uint64_t n __attribute__((unused))) {
  if ((n == 0)) {
    return 0;
  } else {
    return (1 + popcount64((n & (n - 1))));
  }
}

uint64_t floor_log2(uint64_t n __attribute__((unused))) {
  if ((n == 1)) {
    return 0;
  } else {
    return (1 + floor_log2((n / 2)));
  }
}

int main() {
  putchar(72);
  putchar(101);
  putchar(108);
  putchar(108);
  putchar(111);
  putchar(32);
  putchar(102);
  putchar(114);
  putchar(111);
  putchar(109);
  putchar(32);
  putchar(70);
  putchar(111);
  putchar(114);
  putchar(103);
  putchar(101);
  putchar(33);
  print_newline();
  println_u64(42);
  uint64_t g __attribute__((unused)) = gcd64(48, 18);
  println_u64(g);
  uint64_t big __attribute__((unused)) = sat_add(-1, 1);
  println_u64(big);
  uint64_t p __attribute__((unused)) = popcount64(255);
  println_u64(p);
  return (int)(0);

}

