/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t min64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t max64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t clamp64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t pow64(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused)));
uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t round_up(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t gcd64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
_Bool is_pow2(uint64_t n __attribute__((unused)));
uint64_t popcount64(uint64_t n __attribute__((unused)));
uint64_t floor_log2(uint64_t n __attribute__((unused)));
uint64_t check_min();
uint64_t check_max();
uint64_t check_clamp();
uint64_t check_clamp_lo();
uint64_t check_clamp_hi();
uint64_t check_abs_diff();
uint64_t check_pow64();
uint64_t check_ceil_div();
uint64_t check_gcd();
uint64_t check_sat_overflow();
uint64_t check_sat_sub();
_Bool check_is_pow2();
uint64_t check_popcount();
uint64_t check_floor_log2();
int main();

uint64_t min64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t max64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t clamp64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  if ((v < lo)) {
    return lo;
  } else {
    if ((v > hi)) {
      return hi;
    } else {
      return v;
    }
  }
}

uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return (b - a);
  }
}

uint64_t pow64(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused))) {
  if ((forge_exp == 0ULL)) {
    return 1ULL;
  } else {
    return (base * pow64(base, (forge_exp - 1ULL)));
  }
}

uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (((a + b) - 1ULL) / b);
}

uint64_t round_up(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (ceil_div(a, b) * b);
}

uint64_t gcd64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((b == 0ULL)) {
    return a;
  } else {
    return gcd64(b, (a % b));
  }
}

uint64_t sat_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a > (0xffffffffffffffffULL - b))) {
    return 0xffffffffffffffffULL;
  } else {
    return (a + b);
  }
}

uint64_t sat_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a < b)) {
    return 0ULL;
  } else {
    return (a - b);
  }
}

uint64_t sat_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((b == 0ULL)) {
    return 0ULL;
  } else {
    if ((a > (0xffffffffffffffffULL / b))) {
      return 0xffffffffffffffffULL;
    } else {
      return (a * b);
    }
  }
}

_Bool is_pow2(uint64_t n __attribute__((unused))) {
  return ((n & (n - 1ULL)) == 0ULL);
}

uint64_t popcount64(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    return (1ULL + popcount64((n & (n - 1ULL))));
  }
}

uint64_t floor_log2(uint64_t n __attribute__((unused))) {
  if ((n == 1ULL)) {
    return 0ULL;
  } else {
    return (1ULL + floor_log2((n / 2ULL)));
  }
}

uint64_t check_min() {
  return min64(3ULL, 7ULL);
}

uint64_t check_max() {
  return max64(3ULL, 7ULL);
}

uint64_t check_clamp() {
  return clamp64(5ULL, 1ULL, 10ULL);
}

uint64_t check_clamp_lo() {
  return clamp64(0ULL, 1ULL, 10ULL);
}

uint64_t check_clamp_hi() {
  return clamp64(99ULL, 1ULL, 10ULL);
}

uint64_t check_abs_diff() {
  return abs_diff(10ULL, 5ULL);
}

uint64_t check_pow64() {
  return pow64(2ULL, 3ULL);
}

uint64_t check_ceil_div() {
  return ceil_div(10ULL, 3ULL);
}

uint64_t check_gcd() {
  return gcd64(48ULL, 18ULL);
}

uint64_t check_sat_overflow() {
  return sat_add(0xffffffffffffffffULL, 1ULL);
}

uint64_t check_sat_sub() {
  return sat_sub(3ULL, 10ULL);
}

_Bool check_is_pow2() {
  return is_pow2(64ULL);
}

uint64_t check_popcount() {
  return popcount64(15ULL);
}

uint64_t check_floor_log2() {
  return floor_log2(8ULL);
}

int main() {
  return (int)(0ULL);

}

