/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t cmp_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t max_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t min_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t clamp_u64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t abs_diff_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t check_cmp_lt();
uint64_t check_cmp_eq();
uint64_t check_cmp_gt();
uint64_t check_max_ab();
uint64_t check_max_ba();
uint64_t check_min_ab();
uint64_t check_min_ba();
uint64_t check_clamp_in();
uint64_t check_clamp_low();
uint64_t check_clamp_hi();
uint64_t check_abs_diff_5_3();
uint64_t check_abs_diff_3_5();
int main();

uint64_t cmp_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a < b)) {
    return 0ULL;
  } else {
    if ((a == b)) {
      return 1ULL;
    } else {
      return 2ULL;
    }
  }
}

uint64_t max_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t min_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t clamp_u64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  if ((v < lo)) {
    return lo;
  } else {
    if ((v > hi)) {
      return hi;
    } else {
      return v;
    }
  }
}

uint64_t abs_diff_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return (b - a);
  }
}

uint64_t check_cmp_lt() {
  return cmp_u64(3ULL, 5ULL);
}

uint64_t check_cmp_eq() {
  return cmp_u64(5ULL, 5ULL);
}

uint64_t check_cmp_gt() {
  return cmp_u64(7ULL, 5ULL);
}

uint64_t check_max_ab() {
  return max_u64(10ULL, 3ULL);
}

uint64_t check_max_ba() {
  return max_u64(3ULL, 10ULL);
}

uint64_t check_min_ab() {
  return min_u64(3ULL, 10ULL);
}

uint64_t check_min_ba() {
  return min_u64(10ULL, 3ULL);
}

uint64_t check_clamp_in() {
  return clamp_u64(5ULL, 1ULL, 10ULL);
}

uint64_t check_clamp_low() {
  return clamp_u64(0ULL, 1ULL, 10ULL);
}

uint64_t check_clamp_hi() {
  return clamp_u64(15ULL, 1ULL, 10ULL);
}

uint64_t check_abs_diff_5_3() {
  return abs_diff_u64(5ULL, 3ULL);
}

uint64_t check_abs_diff_3_5() {
  return abs_diff_u64(3ULL, 5ULL);
}

int main() {
  return (int)(0ULL);

}

