/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t count_unique_sorted(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t max_adjacent_diff(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
_Bool two_sum_exists(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
int main();

uint64_t count_unique_sorted(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t count __attribute__((unused)) = 1ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      if ((s.data[i] != s.data[(i - 1ULL)])) {
        count = (count + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return count;
}

uint64_t max_adjacent_diff(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t gap __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      uint64_t d;
      if ((s.data[i] >= s.data[(i - 1ULL)])) {
        d = (s.data[i] - s.data[(i - 1ULL)]);
      } else {
        d = (s.data[(i - 1ULL)] - s.data[i]);
      }
      if ((d > gap)) {
        gap = d;

      }
      i = (i + 1ULL);
    }

  }
  return gap;
}

_Bool two_sum_exists(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  _Bool found __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      uint64_t j __attribute__((unused)) = (i + 1ULL);
      {
        while ((j < n)) {
          if (((s.data[i] + s.data[j]) == target)) {
            found = 1;

          }
          j = (j + 1ULL);
        }

      }
      i = (i + 1ULL);
    }

  }
  return found;
}

int main() {
  return (int)(0ULL);

}

