/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
_Bool bmat_get(uint64_t mat __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused)));
uint64_t bmat_set(uint64_t mat __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused)));
uint64_t bmat_clear(uint64_t mat __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused)));
uint64_t bmat_row_mask(uint64_t row __attribute__((unused)));
uint64_t bmat_col_mask(uint64_t col __attribute__((unused)));
uint64_t bmat_and(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t bmat_or(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t bmat_xor(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t bmat_identity();
uint64_t check_set_0_0();
uint64_t check_and_zero();
uint64_t check_or_full();
uint64_t check_xor_same();
int main();

_Bool bmat_get(uint64_t mat __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused))) {
  return (((mat >> ((row * 8ULL) + col)) & 1ULL) == 1ULL);
}

uint64_t bmat_set(uint64_t mat __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused))) {
  return (mat | (1ULL << ((row * 8ULL) + col)));
}

uint64_t bmat_clear(uint64_t mat __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused))) {
  return (mat & (~(1ULL << ((row * 8ULL) + col))));
}

uint64_t bmat_row_mask(uint64_t row __attribute__((unused))) {
  return (255ULL << (row * 8ULL));
}

uint64_t bmat_col_mask(uint64_t col __attribute__((unused))) {
  return (72340172838076673ULL << col);
}

uint64_t bmat_and(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a & b);
}

uint64_t bmat_or(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a | b);
}

uint64_t bmat_xor(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a ^ b);
}

uint64_t bmat_identity() {
  return 0x8040201008040201ULL;
}

uint64_t check_set_0_0() {
  return bmat_set(0ULL, 0ULL, 0ULL);
}

uint64_t check_and_zero() {
  return bmat_and(0ULL, 0xffffffffffffffffULL);
}

uint64_t check_or_full() {
  return bmat_or(0ULL, 0xffffffffffffffffULL);
}

uint64_t check_xor_same() {
  return bmat_xor(42ULL, 42ULL);
}

int main() {
  return (int)(0ULL);

}

