/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t span_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t span_max(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t span_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t span_count_eq(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
_Bool span_all_le(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t bound __attribute__((unused)));
int main();

uint64_t span_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      acc = (acc + s.data[i]);
      i = (i + 1);
    }

  }
  return acc;
}

uint64_t span_max(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t m __attribute__((unused)) = s.data[0];
  uint64_t i __attribute__((unused)) = 1;
  {
    while ((i < n)) {
      if ((s.data[i] > m)) {
        m = s.data[i];

      }
      i = (i + 1);
    }

  }
  return m;
}

uint64_t span_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t m __attribute__((unused)) = s.data[0];
  uint64_t i __attribute__((unused)) = 1;
  {
    while ((i < n)) {
      if ((s.data[i] < m)) {
        m = s.data[i];

      }
      i = (i + 1);
    }

  }
  return m;
}

uint64_t span_count_eq(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      if ((s.data[i] == target)) {
        cnt = (cnt + 1);

      }
      i = (i + 1);
    }

  }
  return cnt;
}

_Bool span_all_le(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t bound __attribute__((unused))) {
  _Bool ok __attribute__((unused)) = 1;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      if ((s.data[i] > bound)) {
        ok = (i != i);

      }
      i = (i + 1);
    }

  }
  return ok;
}

int main() {
  return (int)(0);

}

