/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Monomorphized generic types */
typedef enum {
  Option_u64_tag_None = 0,
  Option_u64_tag_Some = 1,
} Option_u64_tag_t;
typedef struct Option_u64 {
  Option_u64_tag_t tag;
  union {
    struct {
      char _dummy;
    } None;
    struct {
      uint64_t _v0;
    } Some;
  } data;
} Option_u64;


/* Forward declarations */
Option_u64 safe_div(uint64_t n __attribute__((unused)), uint64_t d __attribute__((unused)));
uint64_t div_or_zero(uint64_t n __attribute__((unused)), uint64_t d __attribute__((unused)));
uint64_t safe_add_divs(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t c __attribute__((unused)), uint64_t d __attribute__((unused)));
uint64_t div4(uint64_t n __attribute__((unused)));
uint64_t clamp(uint64_t x __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t run();

Option_u64 safe_div(uint64_t n __attribute__((unused)), uint64_t d __attribute__((unused))) {
  if ((d != 0ULL)) {
    return (Option_u64){ .tag = Option_u64_tag_Some, .data.Some = { ._v0 = (n / d) } };
  } else {
    return (Option_u64){ .tag = Option_u64_tag_None, .data.None = { ._dummy = 0 } };
  }
}

uint64_t div_or_zero(uint64_t n __attribute__((unused)), uint64_t d __attribute__((unused))) {
  switch (safe_div(n, d).tag) {
    case Option_u64_tag_Some: {
      uint64_t q __attribute__((unused)) = safe_div(n, d).data.Some._v0;
      return q;
    }
    default: ;
    {
      return 0ULL;
    }
  }
}

uint64_t safe_add_divs(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t c __attribute__((unused)), uint64_t d __attribute__((unused))) {
  switch (safe_div(a, b).tag) {
    case Option_u64_tag_Some: {
      uint64_t ab __attribute__((unused)) = safe_div(a, b).data.Some._v0;
      switch (safe_div(c, d).tag) {
        case Option_u64_tag_Some: {
          uint64_t cd __attribute__((unused)) = safe_div(c, d).data.Some._v0;
          return (ab + cd);
        }
        default: ;
        {
          return ab;
        }
      }
    }
    default: ;
    {
      return div_or_zero(c, d);
    }
  }
}

uint64_t div4(uint64_t n __attribute__((unused))) {
  uint64_t q __attribute__((unused)) = (n >> 2ULL);
  /* assert erased */;
  return q;
}

uint64_t clamp(uint64_t x __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  uint64_t r;
  if ((x < lo)) {
    r = lo;
  } else {
    if ((x > hi)) {
      r = hi;
    } else {
      r = x;
    }
  }
  /* assert erased */;
  return r;
}

uint64_t run() {
  return 0ULL;
}

