/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t stack_push(forge_span_u64_t s __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t stack_pop(forge_span_u64_t s __attribute__((unused)), uint64_t len __attribute__((unused)));
uint64_t stack_top(forge_span_u64_t s __attribute__((unused)), uint64_t len __attribute__((unused)));
_Bool stack_is_empty(uint64_t len __attribute__((unused)));
_Bool stack_is_full(uint64_t len __attribute__((unused)), uint64_t cap __attribute__((unused)));
uint64_t stack_size(uint64_t len __attribute__((unused)));
uint64_t check_push_pop(forge_span_u64_t s __attribute__((unused)));
int main();

uint64_t stack_push(forge_span_u64_t s __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t val __attribute__((unused))) {
  s.data[len] = val;
  return (len + 1);
}

uint64_t stack_pop(forge_span_u64_t s __attribute__((unused)), uint64_t len __attribute__((unused))) {
  return (len - 1);
}

uint64_t stack_top(forge_span_u64_t s __attribute__((unused)), uint64_t len __attribute__((unused))) {
  return s.data[(len - 1)];
}

_Bool stack_is_empty(uint64_t len __attribute__((unused))) {
  return (len == 0);
}

_Bool stack_is_full(uint64_t len __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  return (len == cap);
}

uint64_t stack_size(uint64_t len __attribute__((unused))) {
  return len;
}

uint64_t check_push_pop(forge_span_u64_t s __attribute__((unused))) {
  uint64_t len0 __attribute__((unused)) = 0;
  uint64_t len1 __attribute__((unused)) = stack_push(s, len0, 42);
  uint64_t len2 __attribute__((unused)) = stack_push(s, len1, 99);
  return stack_pop(s, len2);
}

int main() {
  return (int)(0);

}

