/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t mat_get(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t r __attribute__((unused)), uint64_t c __attribute__((unused)));
void mat_fill(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t mat_row_sum(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)));
uint64_t mat_col_sum(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t col __attribute__((unused)));
int main();

uint64_t mat_get(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t r __attribute__((unused)), uint64_t c __attribute__((unused))) {
  return m.data[((r * cols) + c)];
}

void mat_fill(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  uint64_t total __attribute__((unused)) = (rows * cols);
  {
    while ((i < total)) {
      m.data[i] = val;
      i = (i + 1);
    }

  }
}

uint64_t mat_row_sum(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused))) {
  uint64_t base __attribute__((unused)) = (row * cols);
  uint64_t s __attribute__((unused)) = 0;
  uint64_t j __attribute__((unused)) = 0;
  {
    while ((j < cols)) {
      s = (s + m.data[(base + j)]);
      j = (j + 1);
    }

  }
  return s;
}

uint64_t mat_col_sum(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t col __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < rows)) {
      s = (s + m.data[((i * cols) + col)]);
      i = (i + 1);
    }

  }
  return s;
}

int main() {
  return (int)(0);

}

