/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t popcount(uint64_t x __attribute__((unused)));
uint64_t count_trailing_zeros(uint64_t x __attribute__((unused)));
_Bool is_power_of_two(uint64_t x __attribute__((unused)));
uint64_t next_power_of_two(uint64_t x __attribute__((unused)));
int main();

uint64_t popcount(uint64_t x __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = x;
  uint64_t cnt __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < 64ULL)) {
      cnt = (cnt + (n % 2ULL));
      n = (n / 2ULL);
      i = (i + 1ULL);
    }

  }
  return cnt;
}

uint64_t count_trailing_zeros(uint64_t x __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = x;
  uint64_t cnt __attribute__((unused)) = 0ULL;
  {
    while (((n % 2ULL) == 0ULL)) {
      n = (n / 2ULL);
      cnt = (cnt + 1ULL);
    }

  }
  return cnt;
}

_Bool is_power_of_two(uint64_t x __attribute__((unused))) {
  return ((x & (x - 1ULL)) == 0ULL);
}

uint64_t next_power_of_two(uint64_t x __attribute__((unused))) {
  uint64_t p __attribute__((unused)) = 1ULL;
  {
    while ((p < x)) {
      p = (p * 2ULL);
    }

  }
  return p;
}

int main() {
  return (int)(0ULL);

}

