/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif



typedef struct Point {
  uint64_t x;
  uint64_t y;
} Point;

typedef struct Color {
  uint64_t r;
  uint64_t g;
  uint64_t b;
} Color;

/* Forward declarations */
uint64_t Point__Hashable__hash(const Point* self __attribute__((unused)));
_Bool Point__Eq__eq(const Point* self __attribute__((unused)), const Point* other __attribute__((unused)));
uint64_t Color__Hashable__hash(const Color* self __attribute__((unused)));
int main();

uint64_t Point__Hashable__hash(const Point* self __attribute__((unused))) {
  return (((*self).x * 31) + (*self).y);
}

_Bool Point__Eq__eq(const Point* self __attribute__((unused)), const Point* other __attribute__((unused))) {
  return (((*self).x == (*other).x) && ((*self).y == (*other).y));
}

uint64_t Color__Hashable__hash(const Color* self __attribute__((unused))) {
  return ((((*self).r * 1000003) + ((*self).g * 1009)) + (*self).b);
}

int main() {
  Point p1 __attribute__((unused)) = (Point){ .x = 3, .y = 7 };
  Point p2 __attribute__((unused)) = (Point){ .x = 3, .y = 7 };
  Color c __attribute__((unused)) = (Color){ .r = 255, .g = 128, .b = 0 };
  uint64_t h1 __attribute__((unused)) = Point__Hashable__hash((&p1));
  uint64_t h2 __attribute__((unused)) = Color__Hashable__hash((&c));
  _Bool eq __attribute__((unused)) = Point__Eq__eq((&p1), (&p2));
  uint64_t eq_val;
  if (eq) {
    eq_val = 1;
  } else {
    eq_val = 0;
  }
  return (int)(((h1 + h2) + eq_val));

}

