/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t gcd(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t lcm(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sum_range(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t product_range(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t count_divisors(uint64_t n __attribute__((unused)));
_Bool is_prime(uint64_t n __attribute__((unused)));
int main();

uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return (b - a);
  }
}

uint64_t gcd(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = a;
  uint64_t y __attribute__((unused)) = b;
  {
    while ((y > 0)) {
      uint64_t t __attribute__((unused)) = y;
      y = (x % y);
      x = t;
    }

  }
  return x;
}

uint64_t lcm(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  uint64_t g __attribute__((unused)) = gcd(a, b);
  return ((a / g) * b);
}

uint64_t sum_range(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = lo;
  {
    while ((i <= hi)) {
      acc = (acc + i);
      i = (i + 1);
    }

  }
  return acc;
}

uint64_t product_range(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 1;
  uint64_t i __attribute__((unused)) = lo;
  {
    while ((i <= hi)) {
      acc = (acc * i);
      i = (i + 1);
    }

  }
  return acc;
}

uint64_t count_divisors(uint64_t n __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = 1;
  uint64_t i __attribute__((unused)) = 2;
  {
    while ((i <= n)) {
      if (((n % i) == 0)) {
        cnt = (cnt + 1);

      }
      i = (i + 1);
    }

  }
  return cnt;
}

_Bool is_prime(uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 2;
  _Bool prime __attribute__((unused)) = 1;
  {
    while ((((i * i) <= n) && prime)) {
      if (((n % i) == 0)) {
        prime = 0;

      }
      i = (i + 1);
    }

  }
  return prime;
}

int main() {
  return (int)(0);

}

