/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void convolve(forge_span_u64_t a __attribute__((unused)), uint64_t na __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t nb __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
uint64_t dot_product(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
void cross_correlate(forge_span_u64_t signal __attribute__((unused)), uint64_t ns __attribute__((unused)), forge_span_u64_t kernel __attribute__((unused)), uint64_t nk __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
int main();

void convolve(forge_span_u64_t a __attribute__((unused)), uint64_t na __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t nb __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t nc __attribute__((unused)) = (na + nb);
  uint64_t k __attribute__((unused)) = 0;
  {
    while ((k < nc)) {
      out.data[k] = 0;
      k = (k + 1);
    }

  }
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < na)) {
      uint64_t j __attribute__((unused)) = 0;
      {
        while ((j < nb)) {
          out.data[(i + j)] = (out.data[(i + j)] + (a.data[i] * b.data[j]));
          j = (j + 1);
        }

      }
      i = (i + 1);
    }

  }
}

uint64_t dot_product(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      acc = (acc + (a.data[i] * b.data[i]));
      i = (i + 1);
    }

  }
  return acc;
}

void cross_correlate(forge_span_u64_t signal __attribute__((unused)), uint64_t ns __attribute__((unused)), forge_span_u64_t kernel __attribute__((unused)), uint64_t nk __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t nout __attribute__((unused)) = ((ns - nk) + 1);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < nout)) {
      uint64_t acc __attribute__((unused)) = 0;
      uint64_t j __attribute__((unused)) = 0;
      {
        while ((j < nk)) {
          acc = (acc + (signal.data[(i + j)] * kernel.data[j]));
          j = (j + 1);
        }

      }
      out.data[i] = acc;
      i = (i + 1);
    }

  }
}

int main() {
  return (int)(0);

}

