/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

typedef struct Vec_u64 {
  forge_span_u64_t data;
  uintptr_t len;
} Vec_u64;

/* Forward declarations */
Vec_u64 vec_u64_new(forge_span_u64_t data __attribute__((unused)));
uintptr_t vec_u64_len(const Vec_u64* v __attribute__((unused)));
uintptr_t vec_u64_capacity(const Vec_u64* v __attribute__((unused)));
uint64_t sum_via_vec(forge_span_u64_t sp __attribute__((unused)));
uintptr_t check_len(forge_span_u64_t sp __attribute__((unused)));
int main();

Vec_u64 vec_u64_new(forge_span_u64_t data __attribute__((unused))) {
  return (Vec_u64){ .data = data, .len = 0 };
}

uintptr_t vec_u64_len(const Vec_u64* v __attribute__((unused))) {
  return (*v).len;
}

uintptr_t vec_u64_capacity(const Vec_u64* v __attribute__((unused))) {
  return (*v).data.len;
}

uint64_t sum_via_vec(forge_span_u64_t sp __attribute__((unused))) {
  Vec_u64 v __attribute__((unused)) = vec_u64_new(sp);
  uintptr_t cap __attribute__((unused)) = vec_u64_capacity((&v));
  uint64_t acc __attribute__((unused)) = 0;
  {
    { forge_span_u64_t __span_x = sp;
      for (uint64_t __i_x = 0; __i_x < __span_x.len; __i_x++) {
        uint64_t x __attribute__((unused)) = __span_x.data[__i_x];
        acc = (acc + x);
      }
    }

  }
  return (acc + (cap * 0));
}

uintptr_t check_len(forge_span_u64_t sp __attribute__((unused))) {
  Vec_u64 v __attribute__((unused)) = vec_u64_new(sp);
  return vec_u64_len((&v));
}

int main() {
  return (int)(0);

}

