/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t vec_dot(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t vec_norm_sq(forge_span_u64_t a __attribute__((unused)), uint64_t n __attribute__((unused)));
void vec_add(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)));
void vec_scale(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t s __attribute__((unused)));
void vec_axpy(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t alpha __attribute__((unused)));
void vec_hadamard(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t vec_dot(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = (acc + (a.data[i] * b.data[i]));
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t vec_norm_sq(forge_span_u64_t a __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = (acc + (a.data[i] * a.data[i]));
      i = (i + 1ULL);
    }

  }
  return acc;
}

void vec_add(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      out.data[i] = (a.data[i] + b.data[i]);
      i = (i + 1ULL);
    }

  }
}

void vec_scale(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t s __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      out.data[i] = (a.data[i] * s);
      i = (i + 1ULL);
    }

  }
}

void vec_axpy(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t alpha __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      out.data[i] = ((alpha * a.data[i]) + b.data[i]);
      i = (i + 1ULL);
    }

  }
}

void vec_hadamard(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      out.data[i] = (a.data[i] * b.data[i]);
      i = (i + 1ULL);
    }

  }
}

int main() {
  return (int)(0ULL);

}

