/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t buf_append(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t buf_prepend(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t buf_drain(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t k __attribute__((unused)));
uint64_t buf_compact(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t sentinel __attribute__((unused)));
uint64_t buf_find(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t val __attribute__((unused)));
int main();

uint64_t buf_append(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t val __attribute__((unused))) {
  buf.data[len] = val;
  return (len + 1ULL);
}

uint64_t buf_prepend(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = len;
  {
    while ((i >= 1ULL)) {
      buf.data[i] = buf.data[(i - 1ULL)];
      i = (i - 1ULL);
    }

  }
  buf.data[0ULL] = val;
  return (len + 1ULL);
}

uint64_t buf_drain(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t k __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while (((i + k) < len)) {
      buf.data[i] = buf.data[(i + k)];
      i = (i + 1ULL);
    }

  }
  return (len - k);
}

uint64_t buf_compact(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t sentinel __attribute__((unused))) {
  uint64_t w __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < len)) {
      if ((buf.data[i] != sentinel)) {
        buf.data[w] = buf.data[i];
        w = (w + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return w;
}

uint64_t buf_find(forge_span_u64_t buf __attribute__((unused)), uint64_t len __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  uint64_t found __attribute__((unused)) = len;
  _Bool done __attribute__((unused)) = 0;
  {
    while (((i < len) && (!done))) {
      if ((buf.data[i] == val)) {
        found = i;
        done = 1;

      }
      i = (i + 1ULL);
    }

  }
  return found;
}

int main() {
  return (int)(0ULL);

}

