/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t ring_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t ring_neg(uint64_t a __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t ring_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t ring_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t ring_sum(forge_span_u64_t s __attribute__((unused)), uint64_t k __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t ring_pow(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t ring_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  return (((a % n) + (b % n)) % n);
}

uint64_t ring_neg(uint64_t a __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t am __attribute__((unused)) = (a % n);
  if ((am == 0ULL)) {
    return 0ULL;
  } else {
    return (n - am);
  }
}

uint64_t ring_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t bm __attribute__((unused)) = (b % n);
  uint64_t am __attribute__((unused)) = (a % n);
  if ((am >= bm)) {
    return ((am - bm) % n);
  } else {
    return (((n - bm) + am) % n);
  }
}

uint64_t ring_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  return (((a % n) * (b % n)) % n);
}

uint64_t ring_sum(forge_span_u64_t s __attribute__((unused)), uint64_t k __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < k)) {
      acc = ((acc + (s.data[i] % n)) % n);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t ring_pow(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = (1ULL % n);
  uint64_t b __attribute__((unused)) = (base % n);
  uint64_t e __attribute__((unused)) = forge_exp;
  {
    while ((e > 0ULL)) {
      if (((e % 2ULL) == 1ULL)) {
        acc = ((acc * b) % n);

      }
      b = ((b * b) % n);
      e = (e / 2ULL);
    }

  }
  return acc;
}

int main() {
  return (int)(0ULL);

}

