/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void window_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
void window_max(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
void window_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
uint64_t window_count(uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)));
int main();

void window_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t sum __attribute__((unused)) = 0;
  uint64_t j __attribute__((unused)) = 0;
  {
    while ((j < w)) {
      sum = (sum + s.data[j]);
      j = (j + 1);
    }

  }
  out.data[0] = sum;
  uint64_t i __attribute__((unused)) = 1;
  {
    while (((i + w) <= n)) {
      sum = ((sum + s.data[((i + w) - 1)]) - s.data[(i - 1)]);
      out.data[i] = sum;
      i = (i + 1);
    }

  }
}

void window_max(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while (((i + w) <= n)) {
      uint64_t mx __attribute__((unused)) = s.data[i];
      uint64_t j __attribute__((unused)) = 1;
      {
        while ((j < w)) {
          if ((s.data[(i + j)] > mx)) {
            mx = s.data[(i + j)];

          }
          j = (j + 1);
        }

      }
      out.data[i] = mx;
      i = (i + 1);
    }

  }
}

void window_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while (((i + w) <= n)) {
      uint64_t mn __attribute__((unused)) = s.data[i];
      uint64_t j __attribute__((unused)) = 1;
      {
        while ((j < w)) {
          if ((s.data[(i + j)] < mn)) {
            mn = s.data[(i + j)];

          }
          j = (j + 1);
        }

      }
      out.data[i] = mn;
      i = (i + 1);
    }

  }
}

uint64_t window_count(uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused))) {
  return ((n - w) + 1);
}

int main() {
  return (int)(0);

}

