/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void map_add_scalar(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)));
void map_mul_scalar(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)));
void map_mod(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t m __attribute__((unused)));
void map_clamp(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
void map_copy_add(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)));
uint64_t map_count_gt(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t threshold __attribute__((unused)));
int main();

void map_add_scalar(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      s.data[i] = (s.data[i] + k);
      i = (i + 1);
    }

  }
}

void map_mul_scalar(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      s.data[i] = (s.data[i] * k);
      i = (i + 1);
    }

  }
}

void map_mod(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t m __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      s.data[i] = (s.data[i] % m);
      i = (i + 1);
    }

  }
}

void map_clamp(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      if ((s.data[i] < lo)) {
        s.data[i] = lo;

      } else if ((s.data[i] > hi)) {
        s.data[i] = hi;

      }
      i = (i + 1);
    }

  }
}

void map_copy_add(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      dst.data[i] = (src.data[i] + k);
      i = (i + 1);
    }

  }
}

uint64_t map_count_gt(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t threshold __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      if ((s.data[i] > threshold)) {
        cnt = (cnt + 1);

      }
      i = (i + 1);
    }

  }
  return cnt;
}

int main() {
  return (int)(0);

}

