/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t min64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t max64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t clamp64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t pow64(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused)));
uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t round_up(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t gcd64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
_Bool is_pow2(uint64_t n __attribute__((unused)));
uint64_t popcount64(uint64_t n __attribute__((unused)));
uint64_t floor_log2(uint64_t n __attribute__((unused)));
void clamp_all(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
void pairwise_min(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)));
void pairwise_max(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)));
void sat_prefix_sum(forge_span_u64_t s __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t min64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t max64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t clamp64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  if ((v < lo)) {
    return lo;
  } else {
    if ((v > hi)) {
      return hi;
    } else {
      return v;
    }
  }
}

uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return (b - a);
  }
}

uint64_t pow64(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused))) {
  if ((forge_exp == 0ULL)) {
    return 1ULL;
  } else {
    return (base * pow64(base, (forge_exp - 1ULL)));
  }
}

uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (((a + b) - 1ULL) / b);
}

uint64_t round_up(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (ceil_div(a, b) * b);
}

uint64_t gcd64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((b == 0ULL)) {
    return a;
  } else {
    return gcd64(b, (a % b));
  }
}

uint64_t sat_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a > (0xffffffffffffffffULL - b))) {
    return 0xffffffffffffffffULL;
  } else {
    return (a + b);
  }
}

uint64_t sat_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a < b)) {
    return 0ULL;
  } else {
    return (a - b);
  }
}

uint64_t sat_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((b == 0ULL)) {
    return 0ULL;
  } else {
    if ((a > (0xffffffffffffffffULL / b))) {
      return 0xffffffffffffffffULL;
    } else {
      return (a * b);
    }
  }
}

_Bool is_pow2(uint64_t n __attribute__((unused))) {
  return ((n & (n - 1ULL)) == 0ULL);
}

uint64_t popcount64(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    return (1ULL + popcount64((n & (n - 1ULL))));
  }
}

uint64_t floor_log2(uint64_t n __attribute__((unused))) {
  if ((n == 1ULL)) {
    return 0ULL;
  } else {
    return (1ULL + floor_log2((n / 2ULL)));
  }
}

void clamp_all(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      s.data[i] = clamp64(s.data[i], lo, hi);
      i = (i + 1ULL);
    }

  }
}

void pairwise_min(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      out.data[i] = min64(a.data[i], b.data[i]);
      i = (i + 1ULL);
    }

  }
}

void pairwise_max(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      out.data[i] = max64(a.data[i], b.data[i]);
      i = (i + 1ULL);
    }

  }
}

void sat_prefix_sum(forge_span_u64_t s __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t new_acc __attribute__((unused)) = sat_add(s.data[i], acc);
      acc = new_acc;
      out.data[i] = acc;
      i = (i + 1ULL);
    }

  }
}

int main() {
  return (int)(0ULL);

}

