/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t max_subarray_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t find_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t max_subarray_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t best __attribute__((unused)) = s.data[0ULL];
  uint64_t current __attribute__((unused)) = s.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      current = (current + s.data[i]);
      if ((current > best)) {
        best = current;

      }
      i = (i + 1ULL);
    }

  }
  return best;
}

uint64_t find_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t m __attribute__((unused)) = s.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      if ((s.data[i] < m)) {
        m = s.data[i];

      }
      i = (i + 1ULL);
    }

  }
  return m;
}

int main() {
  return (int)(0ULL);

}

