/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void ewma_filter(forge_span_u64_t samples __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t alpha __attribute__((unused)), forge_span_u64_t output __attribute__((unused)));
void sma(forge_span_u64_t samples __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t output __attribute__((unused)));
int main();

void ewma_filter(forge_span_u64_t samples __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t alpha __attribute__((unused)), forge_span_u64_t output __attribute__((unused))) {
  output.data[0] = samples.data[0];
  uint64_t i __attribute__((unused)) = 1;
  {
    while ((i < n)) {
      uint64_t prev __attribute__((unused)) = output.data[(i - 1)];
      uint64_t cur __attribute__((unused)) = samples.data[i];
      output.data[i] = (((alpha * cur) + ((256 - alpha) * prev)) / 256);
      i = (i + 1);
    }

  }
}

void sma(forge_span_u64_t samples __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t output __attribute__((unused))) {
  uint64_t sum __attribute__((unused)) = 0;
  uint64_t j __attribute__((unused)) = 0;
  {
    while ((j < w)) {
      sum = (sum + samples.data[j]);
      j = (j + 1);
    }

  }
  output.data[(w - 1)] = (sum / w);
  uint64_t i __attribute__((unused)) = w;
  {
    while ((i < n)) {
      sum = ((sum + samples.data[i]) - samples.data[(i - w)]);
      output.data[i] = (sum / w);
      i = (i + 1);
    }

  }
}

int main() {
  return (int)(0);

}

