/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void forward_diff(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
void cumsum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
void second_diff(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
int main();

void forward_diff(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while (((i + 1ULL) < n)) {
      out.data[i] = (s.data[(i + 1ULL)] - s.data[i]);
      i = (i + 1ULL);
    }

  }
}

void cumsum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  out.data[0ULL] = s.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      out.data[i] = (out.data[(i - 1ULL)] + s.data[i]);
      i = (i + 1ULL);
    }

  }
}

void second_diff(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while (((i + 2ULL) < n)) {
      out.data[i] = ((s.data[(i + 2ULL)] - (2ULL * s.data[(i + 1ULL)])) + s.data[i]);
      i = (i + 1ULL);
    }

  }
}

int main() {
  return (int)(0ULL);

}

