/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
_Bool bit_get(forge_span_u64_t words __attribute__((unused)), uint64_t nwords __attribute__((unused)), uint64_t pos __attribute__((unused)));
void bit_set(forge_span_u64_t words __attribute__((unused)), uint64_t nwords __attribute__((unused)), uint64_t pos __attribute__((unused)));
void bit_clear(forge_span_u64_t words __attribute__((unused)), uint64_t nwords __attribute__((unused)), uint64_t pos __attribute__((unused)));
uint64_t bit_count(forge_span_u64_t words __attribute__((unused)), uint64_t nwords __attribute__((unused)));
int main();

_Bool bit_get(forge_span_u64_t words __attribute__((unused)), uint64_t nwords __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  uint64_t word_idx __attribute__((unused)) = (pos / 64ULL);
  uint64_t bit_idx __attribute__((unused)) = (pos % 64ULL);
  uint64_t mask __attribute__((unused)) = (1ULL * (1ULL << bit_idx));
  return ((words.data[word_idx] & mask) != 0ULL);
}

void bit_set(forge_span_u64_t words __attribute__((unused)), uint64_t nwords __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  uint64_t word_idx __attribute__((unused)) = (pos / 64ULL);
  uint64_t bit_idx __attribute__((unused)) = (pos % 64ULL);
  uint64_t mask __attribute__((unused)) = (1ULL << bit_idx);
  words.data[word_idx] = (words.data[word_idx] | mask);
}

void bit_clear(forge_span_u64_t words __attribute__((unused)), uint64_t nwords __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  uint64_t word_idx __attribute__((unused)) = (pos / 64ULL);
  uint64_t bit_idx __attribute__((unused)) = (pos % 64ULL);
  uint64_t mask __attribute__((unused)) = (1ULL << bit_idx);
  words.data[word_idx] = (words.data[word_idx] & (mask ^ 0xffffffffffffffffULL));
}

uint64_t bit_count(forge_span_u64_t words __attribute__((unused)), uint64_t nwords __attribute__((unused))) {
  uint64_t count __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < nwords)) {
      uint64_t w __attribute__((unused)) = words.data[i];
      {
        while ((w != 0ULL)) {
          w = (w & (w - 1ULL));
          count = (count + 1ULL);
        }

      }
      i = (i + 1ULL);
    }

  }
  return count;
}

int main() {
  return (int)(0ULL);

}

