/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t lis_length(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t dp __attribute__((unused)));
int main();

uint64_t lis_length(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t dp __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      dp.data[i] = 1ULL;
      i = (i + 1ULL);
    }

  }
  uint64_t best __attribute__((unused)) = 1ULL;
  uint64_t i2 __attribute__((unused)) = 1ULL;
  {
    while ((i2 < n)) {
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j < i2)) {
          if ((s.data[j] < s.data[i2])) {
            uint64_t candidate __attribute__((unused)) = (dp.data[j] + 1ULL);
            if ((candidate > dp.data[i2])) {
              dp.data[i2] = candidate;

            }

          }
          j = (j + 1ULL);
        }

      }
      if ((dp.data[i2] > best)) {
        best = dp.data[i2];

      }
      i2 = (i2 + 1ULL);
    }

  }
  return best;
}

int main() {
  return (int)(0ULL);

}

