/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Monomorphized generic types */
typedef enum {
  Option_u64_tag_Some = 0,
  Option_u64_tag_None = 1,
} Option_u64_tag_t;
typedef struct Option_u64 {
  Option_u64_tag_t tag;
  union {
    struct {
      uint64_t _v0;
    } Some;
    struct {
      char _dummy;
    } None;
  } data;
} Option_u64;


typedef enum {
  ParseResult_tag_Good = 0,
  ParseResult_tag_Bad = 1,
} ParseResult_tag_t;
typedef struct ParseResult {
  ParseResult_tag_t tag;
  union {
    struct {
      uint64_t _v0;
    } Good;
    struct {
      char _dummy;
    } Bad;
  } data;
} ParseResult;

/* Forward declarations */
ParseResult parse_even(uint64_t n __attribute__((unused)));
uint64_t double_if_good(ParseResult r __attribute__((unused)));
uint64_t handle_opt(Option_u64 o __attribute__((unused)));
uint64_t classify_pair(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
int main();

ParseResult parse_even(uint64_t n __attribute__((unused))) {
  if (((n % 2) == 0)) {
    return (ParseResult){ .tag = ParseResult_tag_Good, .data.Good = { ._v0 = n } };
  } else {
    return (ParseResult){ .tag = ParseResult_tag_Bad, .data.Bad = { ._dummy = 0 } };
  }
}

uint64_t double_if_good(ParseResult r __attribute__((unused))) {
  switch (r.tag) {
    case ParseResult_tag_Good: {
      uint64_t v __attribute__((unused)) = r.data.Good._v0;
      return (v * 2);
    }
    case ParseResult_tag_Bad: {
      return 0;
    }
    default: __builtin_unreachable();
  }
}

uint64_t handle_opt(Option_u64 o __attribute__((unused))) {
  uint64_t inner;
  switch (o.tag) {
    case Option_u64_tag_Some: {
      uint64_t v __attribute__((unused)) = o.data.Some._v0;
      inner = v;
      break;
    }
    default: {
      inner = 0;
      break;
    }
  }
  ParseResult parsed __attribute__((unused)) = parse_even(inner);
  return double_if_good(parsed);
}

uint64_t classify_pair(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  ParseResult pa __attribute__((unused)) = parse_even(a);
  ParseResult pb __attribute__((unused)) = parse_even(b);
  switch (pa.tag) {
    case ParseResult_tag_Good: {
      uint64_t x __attribute__((unused)) = pa.data.Good._v0;
      switch (pb.tag) {
        case ParseResult_tag_Good: {
          uint64_t y __attribute__((unused)) = pb.data.Good._v0;
          return (x + y);
        }
        case ParseResult_tag_Bad: {
          return x;
        }
        default: __builtin_unreachable();
      }
    }
    case ParseResult_tag_Bad: {
      switch (pb.tag) {
        case ParseResult_tag_Good: {
          uint64_t y __attribute__((unused)) = pb.data.Good._v0;
          return y;
        }
        case ParseResult_tag_Bad: {
          return 0;
        }
        default: __builtin_unreachable();
      }
    }
    default: __builtin_unreachable();
  }
}

int main() {
  uint64_t r1 __attribute__((unused)) = double_if_good(parse_even(4));
  uint64_t r2 __attribute__((unused)) = double_if_good(parse_even(7));
  uint64_t r3 __attribute__((unused)) = handle_opt((Option_u64){ .tag = Option_u64_tag_Some, .data.Some = { ._v0 = 10 } });
  uint64_t r4 __attribute__((unused)) = handle_opt((Option_u64){ .tag = Option_u64_tag_Some, .data.Some = { ._v0 = 3 } });
  Option_u64 none_val __attribute__((unused)) = (Option_u64){ .tag = Option_u64_tag_None, .data.None = { ._dummy = 0 } };
  uint64_t r5 __attribute__((unused)) = handle_opt(none_val);
  uint64_t c1 __attribute__((unused)) = classify_pair(4, 6);
  uint64_t c2 __attribute__((unused)) = classify_pair(4, 7);
  uint64_t c3 __attribute__((unused)) = classify_pair(3, 6);
  uint64_t c4 __attribute__((unused)) = classify_pair(3, 7);
  return (int)(((((((((r1 + r2) + r3) + r4) + r5) + c1) + c2) + c3) + c4));

}

