/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t kahn_topo_sort(forge_span_u64_t adj_ptr __attribute__((unused)), forge_span_u64_t adj_list __attribute__((unused)), uint64_t n_verts __attribute__((unused)), uint64_t n_edges __attribute__((unused)), forge_span_u64_t in_degree __attribute__((unused)), forge_span_u64_t queue __attribute__((unused)), forge_span_u64_t output __attribute__((unused)));
int main();

uint64_t kahn_topo_sort(forge_span_u64_t adj_ptr __attribute__((unused)), forge_span_u64_t adj_list __attribute__((unused)), uint64_t n_verts __attribute__((unused)), uint64_t n_edges __attribute__((unused)), forge_span_u64_t in_degree __attribute__((unused)), forge_span_u64_t queue __attribute__((unused)), forge_span_u64_t output __attribute__((unused))) {
  uint64_t front __attribute__((unused)) = 0;
  uint64_t back __attribute__((unused)) = 0;
  uint64_t v __attribute__((unused)) = 0;
  {
    while ((v < n_verts)) {
      if (((in_degree.data[v] == 0) && (back < n_verts))) {
        queue.data[back] = v;
        back = (back + 1);

      }
      v = (v + 1);
    }

  }
  uint64_t out_idx __attribute__((unused)) = 0;
  {
    while ((front < back)) {
      uint64_t u __attribute__((unused)) = queue.data[front];
      front = (front + 1);
      if ((out_idx < n_verts)) {
        output.data[out_idx] = u;
        out_idx = (out_idx + 1);

      }
      if ((u < n_verts)) {
        uint64_t start __attribute__((unused)) = adj_ptr.data[u];
        uint64_t end __attribute__((unused)) = adj_ptr.data[(u + 1)];
        uint64_t e __attribute__((unused)) = start;
        {
          while ((e < end)) {
            uint64_t nb __attribute__((unused)) = adj_list.data[e];
            if ((in_degree.data[nb] > 0)) {
              in_degree.data[nb] = (in_degree.data[nb] - 1);
              if (((in_degree.data[nb] == 0) && (back < n_verts))) {
                queue.data[back] = nb;
                back = (back + 1);

              }

            }
            e = (e + 1);
          }

        }

      }
    }

  }
  return out_idx;
}

int main() {
  return (int)(0);

}

