/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void pagerank_step(forge_span_u64_t adj_ptr __attribute__((unused)), forge_span_u64_t adj_list __attribute__((unused)), uint64_t n_verts __attribute__((unused)), uint64_t n_edges __attribute__((unused)), forge_span_u64_t out_degree __attribute__((unused)), forge_span_u64_t old_rank __attribute__((unused)), forge_span_u64_t new_rank __attribute__((unused)), uint64_t damping __attribute__((unused)));
int main();

void pagerank_step(forge_span_u64_t adj_ptr __attribute__((unused)), forge_span_u64_t adj_list __attribute__((unused)), uint64_t n_verts __attribute__((unused)), uint64_t n_edges __attribute__((unused)), forge_span_u64_t out_degree __attribute__((unused)), forge_span_u64_t old_rank __attribute__((unused)), forge_span_u64_t new_rank __attribute__((unused)), uint64_t damping __attribute__((unused))) {
  uint64_t base __attribute__((unused)) = ((1000 - damping) / n_verts);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n_verts)) {
      new_rank.data[i] = base;
      i = (i + 1);
    }

  }
  uint64_t v __attribute__((unused)) = 0;
  {
    while ((v < n_verts)) {
      uint64_t deg __attribute__((unused)) = out_degree.data[v];
      if ((deg > 0)) {
        uint64_t contrib __attribute__((unused)) = ((damping * old_rank.data[v]) / (1000 * deg));
        uint64_t start __attribute__((unused)) = adj_ptr.data[v];
        uint64_t end __attribute__((unused)) = adj_ptr.data[(v + 1)];
        uint64_t e __attribute__((unused)) = start;
        {
          while ((e < end)) {
            uint64_t nb __attribute__((unused)) = adj_list.data[e];
            new_rank.data[nb] = (new_rank.data[nb] + contrib);
            e = (e + 1);
          }

        }

      }
      v = (v + 1);
    }

  }
}

int main() {
  return (int)(0);

}

