/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void sort5(forge_span_u64_t s __attribute__((unused)), uint64_t base __attribute__((unused)));
uint64_t medians_of_fives(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t medians __attribute__((unused)));
int main();

void sort5(forge_span_u64_t s __attribute__((unused)), uint64_t base __attribute__((unused))) {
  uint64_t pass __attribute__((unused)) = 0ULL;
  {
    while ((pass < 4ULL)) {
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j < (4ULL - pass))) {
          if ((s.data[(base + j)] > s.data[((base + j) + 1ULL)])) {
            uint64_t tmp __attribute__((unused)) = s.data[(base + j)];
            s.data[(base + j)] = s.data[((base + j) + 1ULL)];
            s.data[((base + j) + 1ULL)] = tmp;

          }
          j = (j + 1ULL);
        }

      }
      pass = (pass + 1ULL);
    }

  }
}

uint64_t medians_of_fives(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t medians __attribute__((unused))) {
  uint64_t n_groups __attribute__((unused)) = (n / 5ULL);
  uint64_t g __attribute__((unused)) = 0ULL;
  {
    while ((g < n_groups)) {
      uint64_t base __attribute__((unused)) = (g * 5ULL);
      sort5(s, base);
      medians.data[g] = s.data[(base + 2ULL)];
      g = (g + 1ULL);
    }

  }
  return n_groups;
}

int main() {
  return (int)(0ULL);

}

