/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct FibState {
  uint64_t a;
  uint64_t b;
  uint64_t n;
} FibState;

/* Forward declarations */
FibState fib_step(FibState s __attribute__((unused)));
uint64_t fib(uint64_t n __attribute__((unused)));
int main();

FibState fib_step(FibState s __attribute__((unused))) {
  return (FibState){ .a = s.b, .b = (s.a + s.b), .n = (s.n + 1ULL) };
}

uint64_t fib(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    if ((n == 1ULL)) {
      return 1ULL;
    } else {
      FibState s0 __attribute__((unused)) = (FibState){ .a = 0ULL, .b = 1ULL, .n = 2ULL };
      FibState s1 __attribute__((unused)) = fib_step(s0);
      FibState s2 __attribute__((unused)) = fib_step(s1);
      FibState s3 __attribute__((unused)) = fib_step(s2);
      FibState s4 __attribute__((unused)) = fib_step(s3);
      FibState s5 __attribute__((unused)) = fib_step(s4);
      FibState s6 __attribute__((unused)) = fib_step(s5);
      FibState s7 __attribute__((unused)) = fib_step(s6);
      FibState s8 __attribute__((unused)) = fib_step(s7);
      FibState s9 __attribute__((unused)) = fib_step(s8);
      FibState s10 __attribute__((unused)) = fib_step(s9);
      FibState s11 __attribute__((unused)) = fib_step(s10);
      FibState s12 __attribute__((unused)) = fib_step(s11);
      FibState s13 __attribute__((unused)) = fib_step(s12);
      FibState s14 __attribute__((unused)) = fib_step(s13);
      FibState s15 __attribute__((unused)) = fib_step(s14);
      FibState s16 __attribute__((unused)) = fib_step(s15);
      FibState s17 __attribute__((unused)) = fib_step(s16);
      FibState s18 __attribute__((unused)) = fib_step(s17);
      if ((n == 2ULL)) {
        return s1.b;
      } else {
        if ((n == 3ULL)) {
          return s2.b;
        } else {
          if ((n == 4ULL)) {
            return s3.b;
          } else {
            if ((n == 5ULL)) {
              return s4.b;
            } else {
              if ((n == 6ULL)) {
                return s5.b;
              } else {
                if ((n == 7ULL)) {
                  return s6.b;
                } else {
                  if ((n == 8ULL)) {
                    return s7.b;
                  } else {
                    if ((n == 9ULL)) {
                      return s8.b;
                    } else {
                      if ((n == 10ULL)) {
                        return s9.b;
                      } else {
                        if ((n == 11ULL)) {
                          return s10.b;
                        } else {
                          if ((n == 12ULL)) {
                            return s11.b;
                          } else {
                            if ((n == 13ULL)) {
                              return s12.b;
                            } else {
                              if ((n == 14ULL)) {
                                return s13.b;
                              } else {
                                if ((n == 15ULL)) {
                                  return s14.b;
                                } else {
                                  if ((n == 16ULL)) {
                                    return s15.b;
                                  } else {
                                    if ((n == 17ULL)) {
                                      return s16.b;
                                    } else {
                                      if ((n == 18ULL)) {
                                        return s17.b;
                                      } else {
                                        if ((n == 19ULL)) {
                                          return s18.b;
                                        } else {
                                          return fib_step(s18).b;
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

int main() {
  uint64_t f0 __attribute__((unused)) = fib(0ULL);
  uint64_t f1 __attribute__((unused)) = fib(1ULL);
  uint64_t f2 __attribute__((unused)) = fib(2ULL);
  uint64_t f5 __attribute__((unused)) = fib(5ULL);
  uint64_t f10 __attribute__((unused)) = fib(10ULL);
  uint64_t f12 __attribute__((unused)) = fib(12ULL);
  return (int)((((((f0 + f1) + f2) + f5) + f10) + f12));

}

