/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void str_reverse(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
void to_upper(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t trim_leading(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t ch __attribute__((unused)));
uint64_t char_count(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t ch __attribute__((unused)));
int main();

void str_reverse(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t l __attribute__((unused)) = 0ULL;
  uint64_t r __attribute__((unused)) = n;
  {
    while (((l + 1ULL) < r)) {
      r = (r - 1ULL);
      uint64_t tmp __attribute__((unused)) = s.data[l];
      s.data[l] = s.data[r];
      s.data[r] = tmp;
      l = (l + 1ULL);
    }

  }
}

void to_upper(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if (((s.data[i] >= 97ULL) && (s.data[i] <= 122ULL))) {
        s.data[i] = (s.data[i] - 32ULL);

      }
      i = (i + 1ULL);
    }

  }
}

uint64_t trim_leading(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t ch __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  _Bool found __attribute__((unused)) = 0;
  {
    while (((i < n) && (!found))) {
      if ((s.data[i] != ch)) {
        found = 1;

      } else {
        i = (i + 1ULL);

      }
    }

  }
  return i;
}

uint64_t char_count(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t ch __attribute__((unused))) {
  uint64_t count __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((s.data[i] == ch)) {
        count = (count + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return count;
}

int main() {
  return (int)(0ULL);

}

