/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;

/* Forward declarations */
__forge_tuple_u64_u64_t gap_insert(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t ch __attribute__((unused)));
__forge_tuple_u64_u64_t gap_delete(uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t cap __attribute__((unused)));
__forge_tuple_u64_u64_t gap_move(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t pos __attribute__((unused)));
int main();

__forge_tuple_u64_u64_t gap_insert(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t ch __attribute__((unused))) {
  buf.data[gap_start] = ch;
  return (__forge_tuple_u64_u64_t){ ._0 = (gap_start + 1ULL), ._1 = gap_end };
}

__forge_tuple_u64_u64_t gap_delete(uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  return (__forge_tuple_u64_u64_t){ ._0 = (gap_start - 1ULL), ._1 = gap_end };
}

__forge_tuple_u64_u64_t gap_move(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  uint64_t gap_size __attribute__((unused)) = (gap_end - gap_start);
  uint64_t gs __attribute__((unused)) = gap_start;
  uint64_t ge __attribute__((unused)) = gap_end;
  {
    while ((gs > pos)) {
      ge = (ge - 1ULL);
      gs = (gs - 1ULL);
      buf.data[ge] = buf.data[gs];
    }

  }
  {
    while (((gs < pos) && (ge < cap))) {
      buf.data[gs] = buf.data[ge];
      gs = (gs + 1ULL);
      ge = (ge + 1ULL);
    }

  }
  return (__forge_tuple_u64_u64_t){ ._0 = gs, ._1 = ge };
}

int main() {
  return (int)(0ULL);

}

