/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t min64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t max64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t clamp64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t pow64(uint64_t base __attribute__((unused)), uint64_t exp __attribute__((unused)));
uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t round_up(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t gcd64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t sat_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
_Bool is_pow2(uint64_t n __attribute__((unused)));
uint64_t popcount64(uint64_t n __attribute__((unused)));
uint64_t floor_log2(uint64_t n __attribute__((unused)));
void fill_all(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t fill_then_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t power(uint64_t base __attribute__((unused)), uint64_t exp __attribute__((unused)));
void bfs_simple(forge_span_u64_t adj __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t levels __attribute__((unused)), forge_span_u64_t queue __attribute__((unused)));
uint64_t lis_simple(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t dp __attribute__((unused)));
uint64_t mod_exp(uint64_t base __attribute__((unused)), uint64_t exp __attribute__((unused)), uint64_t modulus __attribute__((unused)));
int main();

uint64_t min64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t max64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t clamp64(uint64_t v __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  if ((v < lo)) {
    return lo;
  } else {
    if ((v > hi)) {
      return hi;
    } else {
      return v;
    }
  }
}

uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return (b - a);
  }
}

uint64_t pow64(uint64_t base __attribute__((unused)), uint64_t exp __attribute__((unused))) {
  if ((exp == 0)) {
    return 1;
  } else {
    return (base * pow64(base, (exp - 1)));
  }
}

uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (((a + b) - 1) / b);
}

uint64_t round_up(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (ceil_div(a, b) * b);
}

uint64_t gcd64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((b == 0)) {
    return a;
  } else {
    return gcd64(b, (a % b));
  }
}

uint64_t sat_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a > (-1 - b))) {
    return -1;
  } else {
    return (a + b);
  }
}

uint64_t sat_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a < b)) {
    return 0;
  } else {
    return (a - b);
  }
}

uint64_t sat_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((b == 0)) {
    return 0;
  } else {
    if ((a > (-1 / b))) {
      return -1;
    } else {
      return (a * b);
    }
  }
}

_Bool is_pow2(uint64_t n __attribute__((unused))) {
  return ((n & (n - 1)) == 0);
}

uint64_t popcount64(uint64_t n __attribute__((unused))) {
  if ((n == 0)) {
    return 0;
  } else {
    return (1 + popcount64((n & (n - 1))));
  }
}

uint64_t floor_log2(uint64_t n __attribute__((unused))) {
  if ((n == 1)) {
    return 0;
  } else {
    return (1 + floor_log2((n / 2)));
  }
}

void fill_all(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      s.data[i] = val;
      i = (i + 1);
    }

  }
}

uint64_t fill_then_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t val __attribute__((unused))) {
  fill_all(s, n, val);
  uint64_t acc __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      acc = (acc + s.data[i]);
      i = (i + 1);
    }

  }
  return acc;
}

uint64_t power(uint64_t base __attribute__((unused)), uint64_t exp __attribute__((unused))) {
  if ((exp == 0)) {
    return 1;
  } else {
    return (base * power(base, (exp - 1)));
  }
}

void bfs_simple(forge_span_u64_t adj __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t levels __attribute__((unused)), forge_span_u64_t queue __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      levels.data[i] = -1;
      i = (i + 1);
    }

  }
  levels.data[0] = 0;
  queue.data[0] = 0;
  uint64_t front __attribute__((unused)) = 0;
  uint64_t back __attribute__((unused)) = 1;
  {
    while ((front < back)) {
      uint64_t u __attribute__((unused)) = queue.data[front];
      front = (front + 1);
      uint64_t next __attribute__((unused)) = (u + 1);
      if ((((next < n) && (levels.data[next] == -1)) && (back < n))) {
        levels.data[next] = (levels.data[u] + 1);
        queue.data[back] = next;
        back = (back + 1);

      }
    }

  }
}

uint64_t lis_simple(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t dp __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      dp.data[i] = 1;
      i = (i + 1);
    }

  }
  uint64_t best __attribute__((unused)) = 1;
  uint64_t i2 __attribute__((unused)) = 1;
  {
    while ((i2 < n)) {
      uint64_t j __attribute__((unused)) = 0;
      {
        while ((j < i2)) {
          if ((s.data[j] < s.data[i2])) {
            uint64_t c __attribute__((unused)) = (dp.data[j] + 1);
            if ((c > dp.data[i2])) {
              dp.data[i2] = c;

            }

          }
          j = (j + 1);
        }

      }
      if ((dp.data[i2] > best)) {
        best = dp.data[i2];

      }
      i2 = (i2 + 1);
    }

  }
  return best;
}

uint64_t mod_exp(uint64_t base __attribute__((unused)), uint64_t exp __attribute__((unused)), uint64_t modulus __attribute__((unused))) {
  uint64_t res __attribute__((unused)) = (1 % modulus);
  uint64_t b __attribute__((unused)) = (base % modulus);
  uint64_t e __attribute__((unused)) = exp;
  {
    while ((e > 0)) {
      if (((e % 2) == 1)) {
        res = ((res * b) % modulus);

      }
      b = ((b * b) % modulus);
      e = (e / 2);
    }

  }
  return res;
}

int main() {
  return (int)(0);

}

