/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t rle_decode(forge_span_u64_t encoded __attribute__((unused)), uint64_t enc_len __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t out_cap __attribute__((unused)));
int main();

uint64_t rle_decode(forge_span_u64_t encoded __attribute__((unused)), uint64_t enc_len __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t out_cap __attribute__((unused))) {
  uint64_t ri __attribute__((unused)) = 0;
  uint64_t wi __attribute__((unused)) = 0;
  {
    while (((ri + 1) < enc_len)) {
      uint64_t val __attribute__((unused)) = encoded.data[ri];
      uint64_t cnt __attribute__((unused)) = encoded.data[(ri + 1)];
      uint64_t j __attribute__((unused)) = 0;
      {
        while ((j < cnt)) {
          if ((wi < out_cap)) {
            out.data[wi] = val;
            wi = (wi + 1);

          }
          j = (j + 1);
        }

      }
      ri = (ri + 2);
    }

  }
  return wi;
}

int main() {
  return (int)(0);

}

