/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t window_min(forge_span_u64_t s __attribute__((unused)), uint64_t start __attribute__((unused)), uint64_t k __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t sliding_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
int main();

uint64_t window_min(forge_span_u64_t s __attribute__((unused)), uint64_t start __attribute__((unused)), uint64_t k __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t mn __attribute__((unused)) = s.data[start];
  uint64_t j __attribute__((unused)) = 1;
  {
    while ((j < k)) {
      uint64_t idx __attribute__((unused)) = (start + j);
      if (((idx < n) && (s.data[idx] < mn))) {
        mn = s.data[idx];

      }
      j = (j + 1);
    }

  }
  return mn;
}

uint64_t sliding_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t out_len __attribute__((unused)) = ((n - k) + 1);
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < out_len)) {
      if (((i + k) <= n)) {
        uint64_t mn __attribute__((unused)) = window_min(s, i, k, n);
        out.data[i] = mn;

      }
      i = (i + 1);
    }

  }
  return out_len;
}

int main() {
  return (int)(0);

}

