/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void gauss_seidel_step(forge_span_u64_t x __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t diag __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t converged(forge_span_u64_t x_old __attribute__((unused)), forge_span_u64_t x_new __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t tol __attribute__((unused)));
int main();

void gauss_seidel_step(forge_span_u64_t x __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t diag __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((diag.data[i] > 0ULL)) {
        x.data[i] = (b.data[i] / diag.data[i]);

      } else {
        x.data[i] = 0ULL;

      }
      i = (i + 1ULL);
    }

  }
}

uint64_t converged(forge_span_u64_t x_old __attribute__((unused)), forge_span_u64_t x_new __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t tol __attribute__((unused))) {
  uint64_t ok __attribute__((unused)) = 1ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((x_new.data[i] > (x_old.data[i] + tol))) {
        ok = 0ULL;

      }
      if ((x_old.data[i] > (x_new.data[i] + tol))) {
        ok = 0ULL;

      }
      i = (i + 1ULL);
    }

  }
  return ok;
}

int main() {
  return (int)(0ULL);

}

