/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t compute_syndrome(forge_span_u64_t codeword __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t count_ones(forge_span_u64_t codeword __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t is_valid(forge_span_u64_t codeword __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t compute_syndrome(forge_span_u64_t codeword __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t syn __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      if ((codeword.data[i] == 1)) {
        if ((syn == 0)) {
          syn = i;

        } else if ((i > syn)) {
          syn = i;

        }

      }
      i = (i + 1);
    }

  }
  return syn;
}

uint64_t count_ones(forge_span_u64_t codeword __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      if ((codeword.data[i] == 1)) {
        cnt = (cnt + 1);

      }
      i = (i + 1);
    }

  }
  return cnt;
}

uint64_t is_valid(forge_span_u64_t codeword __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = compute_syndrome(codeword, n);
  if ((s == 0)) {
    return 1;
  } else {
    return 0;
  }
}

int main() {
  return (int)(0);

}

