/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t max(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t min(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t clamp(uint64_t x __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t round_up_to_pow2(uint64_t x __attribute__((unused)));
int main();

uint64_t max(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t min(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return a;
  } else {
    return b;
  }
}

uint64_t clamp(uint64_t x __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  if ((x < lo)) {
    return lo;
  } else {
    if ((x > hi)) {
      return hi;
    } else {
      return x;
    }
  }
}

uint64_t abs_diff(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return (b - a);
  }
}

uint64_t ceil_div(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (((a + b) - 1) / b);
}

uint64_t round_up_to_pow2(uint64_t x __attribute__((unused))) {
  if ((x <= 1)) {
    return 1;
  } else {
    if ((x <= 2)) {
      return 2;
    } else {
      if ((x <= 4)) {
        return 4;
      } else {
        if ((x <= 8)) {
          return 8;
        } else {
          return 16;
        }
      }
    }
  }
}

int main() {
  uint64_t a __attribute__((unused)) = max(7, 3);
  uint64_t b __attribute__((unused)) = min(7, 3);
  uint64_t c __attribute__((unused)) = clamp(15, 0, 10);
  uint64_t d __attribute__((unused)) = clamp(5, 0, 10);
  uint64_t e __attribute__((unused)) = abs_diff(10, 4);
  uint64_t f __attribute__((unused)) = ceil_div(10, 3);
  uint64_t g __attribute__((unused)) = round_up_to_pow2(5);
  uint64_t h __attribute__((unused)) = round_up_to_pow2(8);
  return (int)((((((((a + b) + c) + d) + e) + f) + g) + h));

}

