/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* Forward declarations */
uint64_t replicate(uint64_t N __attribute__((unused)), uint64_t v __attribute__((unused)));
uint64_t scale_up(uint64_t FACTOR __attribute__((unused)), uint64_t x __attribute__((unused)));
uint64_t threshold_check(uint64_t LIMIT __attribute__((unused)), uint64_t x __attribute__((unused)));
uint64_t fixed_sum(uint64_t A __attribute__((unused)), uint64_t B __attribute__((unused)));
int main();

uint64_t replicate(uint64_t N __attribute__((unused)), uint64_t v __attribute__((unused))) {
  return (v * N);
}

uint64_t scale_up(uint64_t FACTOR __attribute__((unused)), uint64_t x __attribute__((unused))) {
  return (x * FACTOR);
}

uint64_t threshold_check(uint64_t LIMIT __attribute__((unused)), uint64_t x __attribute__((unused))) {
  if ((x <= LIMIT)) {
    return 1;
  } else {
    return 0;
  }
}

uint64_t fixed_sum(uint64_t A __attribute__((unused)), uint64_t B __attribute__((unused))) {
  return (A + B);
}

int main() {
  uint64_t r1 __attribute__((unused)) = replicate(3, 7);
  uint64_t r2 __attribute__((unused)) = replicate(5, 4);
  uint64_t s1 __attribute__((unused)) = scale_up(10, 8);
  uint64_t s2 __attribute__((unused)) = scale_up(100, 2);
  uint64_t t1 __attribute__((unused)) = threshold_check(50, 30);
  uint64_t t2 __attribute__((unused)) = threshold_check(50, 60);
  uint64_t f1 __attribute__((unused)) = fixed_sum(10, 20);
  uint64_t f2 __attribute__((unused)) = fixed_sum(7, 8);
  return (int)((((((((r1 + r2) + s1) + s2) + t1) + t2) + f1) + f2));

}

