/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t bandwidth(forge_span_u64_t mat __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t bandwidth(forge_span_u64_t mat __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t bw __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j < n)) {
          if (((((i * n) + j) < (n * n)) && (mat.data[((i * n) + j)] > 0ULL))) {
            uint64_t diff;
            if ((i >= j)) {
              diff = (i - j);
            } else {
              diff = (j - i);
            }
            if ((diff > bw)) {
              bw = diff;

            }

          }
          j = (j + 1ULL);
        }

      }
      i = (i + 1ULL);
    }

  }
  return bw;
}

int main() {
  return (int)(0ULL);

}

