/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void affine_enc(forge_span_u64_t plain __attribute__((unused)), forge_span_u64_t cipher __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused)));
uint64_t mod_inv_naive(uint64_t a __attribute__((unused)), uint64_t m __attribute__((unused)));
int main();

void affine_enc(forge_span_u64_t plain __attribute__((unused)), forge_span_u64_t cipher __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      cipher.data[i] = (((a * plain.data[i]) + b) % m);
      i = (i + 1ULL);
    }

  }
}

uint64_t mod_inv_naive(uint64_t a __attribute__((unused)), uint64_t m __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < m)) {
      if ((((a * i) % m) == 1ULL)) {
        x = i;

      }
      i = (i + 1ULL);
    }

  }
  return x;
}

int main() {
  return (int)(0ULL);

}

