/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

typedef struct BoundedU8 {
  uint64_t val;
} BoundedU8;

typedef struct Fraction {
  uint64_t num;
  uint64_t den;
} Fraction;

typedef struct SortedPair {
  uint64_t lo;
  uint64_t hi;
} SortedPair;

/* Forward declarations */
BoundedU8 make_bounded(uint64_t v __attribute__((unused)));
Fraction make_fraction(uint64_t n __attribute__((unused)), uint64_t d __attribute__((unused)));
SortedPair make_sorted(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t frac_value_times_10(Fraction f __attribute__((unused)));
uint64_t span_size(SortedPair p __attribute__((unused)));
int main();

BoundedU8 make_bounded(uint64_t v __attribute__((unused))) {
  return (BoundedU8){ .val = v };
}

Fraction make_fraction(uint64_t n __attribute__((unused)), uint64_t d __attribute__((unused))) {
  return (Fraction){ .num = n, .den = d };
}

SortedPair make_sorted(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return (SortedPair){ .lo = a, .hi = b };
  } else {
    return (SortedPair){ .lo = b, .hi = a };
  }
}

uint64_t frac_value_times_10(Fraction f __attribute__((unused))) {
  if ((f.den == 0ULL)) {
    return 0ULL;
  } else {
    return ((f.num * 10ULL) / f.den);
  }
}

uint64_t span_size(SortedPair p __attribute__((unused))) {
  return (p.hi - p.lo);
}

int main() {
  BoundedU8 b1 __attribute__((unused)) = make_bounded(100ULL);
  BoundedU8 b2 __attribute__((unused)) = make_bounded(200ULL);
  Fraction f1 __attribute__((unused)) = make_fraction(1ULL, 4ULL);
  Fraction f2 __attribute__((unused)) = make_fraction(3ULL, 2ULL);
  uint64_t fv1 __attribute__((unused)) = frac_value_times_10(f1);
  uint64_t fv2 __attribute__((unused)) = frac_value_times_10(f2);
  SortedPair sp __attribute__((unused)) = make_sorted(7ULL, 3ULL);
  uint64_t sz __attribute__((unused)) = span_size(sp);
  return (int)(((((b1.val + b2.val) + fv1) + fv2) + sz));

}

