/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t crc16(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t crc16(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t poly __attribute__((unused)) = 4129;
  uint64_t crc __attribute__((unused)) = 65535;
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < n)) {
      crc = (crc ^ ((data.data[i] & 255) * 256));
      crc = (crc & 65535);
      uint64_t bit __attribute__((unused)) = 0;
      {
        while ((bit < 8)) {
          if (((crc / 32768) > 0)) {
            crc = (((crc * 2) ^ poly) & 65535);

          } else {
            crc = ((crc * 2) & 65535);

          }
          bit = (bit + 1);
        }

      }
      i = (i + 1);
    }

  }
  return crc;
}

int main() {
  return (int)(0);

}

