/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t slip_encode(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t cap __attribute__((unused)));
int main();

uint64_t slip_encode(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  uint64_t end_byte __attribute__((unused)) = 192ULL;
  uint64_t esc_byte __attribute__((unused)) = 219ULL;
  uint64_t out __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t b __attribute__((unused)) = (src.data[i] & 255ULL);
      if ((b == end_byte)) {
        dst.data[out] = esc_byte;
        out = (out + 1ULL);
        dst.data[out] = 220ULL;
        out = (out + 1ULL);

      } else if ((b == esc_byte)) {
        dst.data[out] = esc_byte;
        out = (out + 1ULL);
        dst.data[out] = 221ULL;
        out = (out + 1ULL);

      } else {
        dst.data[out] = b;
        out = (out + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return out;
}

int main() {
  return (int)(0ULL);

}

