/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t check_rb_violations(forge_span_u64_t color __attribute__((unused)), forge_span_u64_t parent __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t count_black_nodes(forge_span_u64_t color __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t check_rb_violations(forge_span_u64_t color __attribute__((unused)), forge_span_u64_t parent __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t violations __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((color.data[i] == 1ULL)) {
        uint64_t p __attribute__((unused)) = parent.data[i];
        if (((p < n) && (color.data[p] == 1ULL))) {
          violations = (violations + 1ULL);

        }

      }
      i = (i + 1ULL);
    }

  }
  return violations;
}

uint64_t count_black_nodes(forge_span_u64_t color __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((color.data[i] == 0ULL)) {
        cnt = (cnt + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return cnt;
}

int main() {
  return (int)(0ULL);

}

