/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t decrease_key(forge_span_u64_t keys __attribute__((unused)), forge_span_u64_t parent __attribute__((unused)), forge_span_u64_t marked __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t node __attribute__((unused)), uint64_t new_val __attribute__((unused)));
int main();

uint64_t decrease_key(forge_span_u64_t keys __attribute__((unused)), forge_span_u64_t parent __attribute__((unused)), forge_span_u64_t marked __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t node __attribute__((unused)), uint64_t new_val __attribute__((unused))) {
  keys.data[node] = new_val;
  uint64_t cur __attribute__((unused)) = node;
  uint64_t cuts __attribute__((unused)) = 0ULL;
  _Bool done __attribute__((unused)) = 0;
  {
    while ((done == 0)) {
      if ((cuts == n)) {
        done = 1;

      } else {
        uint64_t p __attribute__((unused)) = parent.data[cur];
        if ((p >= n)) {
          done = 1;

        } else if ((marked.data[p] == 0ULL)) {
          marked.data[p] = 1ULL;
          done = 1;

        } else {
          marked.data[p] = 0ULL;
          cur = p;
          cuts = (cuts + 1ULL);

        }

      }
    }

  }
  return cuts;
}

int main() {
  return (int)(0ULL);

}

