/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t reservoir_sample(forge_span_u64_t stream __attribute__((unused)), forge_span_u64_t weights __attribute__((unused)), forge_span_u64_t reservoir __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)), uint64_t seed __attribute__((unused)));
int main();

uint64_t reservoir_sample(forge_span_u64_t stream __attribute__((unused)), forge_span_u64_t weights __attribute__((unused)), forge_span_u64_t reservoir __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)), uint64_t seed __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0;
  {
    while ((i < k)) {
      if ((i < n)) {
        reservoir.data[i] = stream.data[i];

      }
      i = (i + 1);
    }

  }
  uint64_t j __attribute__((unused)) = k;
  uint64_t rng __attribute__((unused)) = seed;
  {
    while ((j < n)) {
      rng = (((rng * 6364136223846793005) + 1) % 1000000007);
      uint64_t slot __attribute__((unused)) = (rng % k);
      if ((weights.data[j] > (rng % 100))) {
        reservoir.data[slot] = stream.data[j];

      }
      j = (j + 1);
    }

  }
  return n;
}

int main() {
  return (int)(0);

}

