/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void compute_syndrome(forge_span_u64_t received __attribute__((unused)), forge_span_u64_t h_matrix __attribute__((unused)), forge_span_u64_t syndrome __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t m __attribute__((unused)), uint64_t p __attribute__((unused)));
int main();

void compute_syndrome(forge_span_u64_t received __attribute__((unused)), forge_span_u64_t h_matrix __attribute__((unused)), forge_span_u64_t syndrome __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t m __attribute__((unused)), uint64_t p __attribute__((unused))) {
  uint64_t j __attribute__((unused)) = 0;
  {
    while ((j < m)) {
      uint64_t acc __attribute__((unused)) = 0;
      uint64_t i __attribute__((unused)) = 0;
      {
        while ((i < n)) {
          uint64_t idx __attribute__((unused)) = ((j * n) + i);
          if ((idx < (m * n))) {
            acc = ((acc + (received.data[i] * h_matrix.data[idx])) % p);

          }
          i = (i + 1);
        }

      }
      syndrome.data[j] = acc;
      j = (j + 1);
    }

  }
}

int main() {
  return (int)(0);

}

