/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t streaming_median(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t streaming_median(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t est __attribute__((unused)) = data.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      uint64_t below __attribute__((unused)) = 0ULL;
      uint64_t above __attribute__((unused)) = 0ULL;
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j <= i)) {
          if ((data.data[j] < est)) {
            below = (below + 1ULL);

          } else if ((data.data[j] > est)) {
            above = (above + 1ULL);

          }
          j = (j + 1ULL);
        }

      }
      if ((below > (above + 1ULL))) {
        if ((est > 0ULL)) {
          est = (est - 1ULL);

        }

      } else if ((above > (below + 1ULL))) {
        est = (est + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return est;
}

int main() {
  return (int)(0ULL);

}

