/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint8_t* data; uintptr_t len; } forge_span_u8_t;

/* Forward declarations */
uint64_t ctrl_byte13(uint64_t ctrl __attribute__((unused)));
uint64_t ctrl_byte14(uint64_t ctrl __attribute__((unused)));
uint64_t ctrl_byte15(uint64_t ctrl __attribute__((unused)));
void build_insn(forge_span_u8_t out __attribute__((unused)), uint64_t b0 __attribute__((unused)), uint64_t b1 __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1_or_imm __attribute__((unused)), uint64_t src2 __attribute__((unused)), uint64_t mod9 __attribute__((unused)), uint64_t mod10 __attribute__((unused)), uint64_t mod11 __attribute__((unused)), uint64_t ctrl __attribute__((unused)), uint64_t b15_fixed __attribute__((unused)));
void encode_nop(forge_span_u8_t out __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_exit(forge_span_u8_t out __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_s2r(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t sr_code __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_mov(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_iadd3(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1 __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_imad_wide(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1 __attribute__((unused)), uint64_t src2 __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_ldg_32(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t addr_reg __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_stg_32(forge_span_u8_t out __attribute__((unused)), uint64_t addr_reg __attribute__((unused)), uint64_t src __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_fadd(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1 __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_setp_lt_s32(forge_span_u8_t out __attribute__((unused)), uint64_t pred_dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1 __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void encode_bra(forge_span_u8_t out __attribute__((unused)), uint64_t offset __attribute__((unused)), uint64_t ctrl __attribute__((unused)));
void patch_pred(forge_span_u8_t insn __attribute__((unused)), uint64_t pred __attribute__((unused)), uint8_t negate __attribute__((unused)));
int main();

uint64_t ctrl_byte13(uint64_t ctrl __attribute__((unused))) {
  uint64_t raw24 __attribute__((unused)) = ((ctrl & 8388607) * 2);
  return (raw24 & 255);
}

uint64_t ctrl_byte14(uint64_t ctrl __attribute__((unused))) {
  uint64_t raw24 __attribute__((unused)) = ((ctrl & 8388607) * 2);
  return ((raw24 / 256) & 255);
}

uint64_t ctrl_byte15(uint64_t ctrl __attribute__((unused))) {
  uint64_t raw24 __attribute__((unused)) = ((ctrl & 8388607) * 2);
  return ((raw24 / 65536) & 255);
}

void build_insn(forge_span_u8_t out __attribute__((unused)), uint64_t b0 __attribute__((unused)), uint64_t b1 __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1_or_imm __attribute__((unused)), uint64_t src2 __attribute__((unused)), uint64_t mod9 __attribute__((unused)), uint64_t mod10 __attribute__((unused)), uint64_t mod11 __attribute__((unused)), uint64_t ctrl __attribute__((unused)), uint64_t b15_fixed __attribute__((unused))) {
  out.data[0] = ((uint8_t)b0);
  out.data[1] = ((uint8_t)b1);
  out.data[2] = ((uint8_t)dest);
  out.data[3] = ((uint8_t)src0);
  out.data[4] = ((uint8_t)src1_or_imm);
  out.data[5] = 0;
  out.data[6] = 0;
  out.data[7] = 0;
  out.data[8] = ((uint8_t)src2);
  out.data[9] = ((uint8_t)mod9);
  out.data[10] = ((uint8_t)mod10);
  out.data[11] = ((uint8_t)mod11);
  out.data[12] = 0;
  out.data[13] = ((uint8_t)ctrl_byte13(ctrl));
  out.data[14] = ((uint8_t)ctrl_byte14(ctrl));
  out.data[15] = ((uint8_t)(ctrl_byte15(ctrl) | b15_fixed));
}

void encode_nop(forge_span_u8_t out __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 24, 121, 0, 0, 0, 0, 0, 0, 0, ctrl, 0);
}

void encode_exit(forge_span_u8_t out __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 77, 121, 0, 0, 0, 0, 0, 128, 3, ctrl, 0);
}

void encode_s2r(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t sr_code __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 25, 121, dest, 0, sr_code, 0, 0, 0, 0, ctrl, 0);
}

void encode_mov(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 2, 121, dest, src, 0, 0, 0, 0, 0, ctrl, 0);
}

void encode_iadd3(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1 __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 16, 120, dest, src0, src1, 255, 0, 0, 0, ctrl, 0);
}

void encode_imad_wide(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1 __attribute__((unused)), uint64_t src2 __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 36, 122, dest, src0, src1, src2, 0, 16, 0, ctrl, 0);
}

void encode_ldg_32(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t addr_reg __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 129, 120, dest, addr_reg, 0, 0, 0, 32, 0, ctrl, 0);
}

void encode_stg_32(forge_span_u8_t out __attribute__((unused)), uint64_t addr_reg __attribute__((unused)), uint64_t src __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 133, 120, src, addr_reg, 0, 0, 0, 32, 0, ctrl, 0);
}

void encode_fadd(forge_span_u8_t out __attribute__((unused)), uint64_t dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1 __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 21, 122, dest, src0, src1, 0, 0, 0, 0, ctrl, 0);
}

void encode_setp_lt_s32(forge_span_u8_t out __attribute__((unused)), uint64_t pred_dest __attribute__((unused)), uint64_t src0 __attribute__((unused)), uint64_t src1 __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  build_insn(out, 12, 122, pred_dest, src0, src1, 0, 1, 0, 0, ctrl, 0);
}

void encode_bra(forge_span_u8_t out __attribute__((unused)), uint64_t offset __attribute__((unused)), uint64_t ctrl __attribute__((unused))) {
  uint64_t lo __attribute__((unused)) = (offset & 255);
  uint64_t hi __attribute__((unused)) = ((offset / 256) & 255);
  build_insn(out, 47, 121, 0, 0, lo, hi, 0, 0, 0, ctrl, 0);
}

void patch_pred(forge_span_u8_t insn __attribute__((unused)), uint64_t pred __attribute__((unused)), uint8_t negate __attribute__((unused))) {
  uint64_t code;
  if ((negate == 1)) {
    code = (pred | 8);
  } else {
    code = pred;
  }
  uint64_t lo_nibble __attribute__((unused)) = (((uint64_t)insn.data[1]) & 15);
  insn.data[1] = ((uint8_t)(lo_nibble | (code * 16)));
}

int main() {
  return (int)(0);

}

