/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))

#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint32_t* data; uintptr_t len; } forge_span_u32_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_ptr_u64_u64_ret_u64_t)(uint64_t*, uint64_t);
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef uint64_t (*forge_fn__ret_u64_t)(void);
typedef float (*forge_fn_f32_u64_u64_ret_f32_t)(float, uint64_t, uint64_t);

uint64_t shfl_down_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

uint64_t shfl_xor_sync(uint64_t val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

uint64_t atom_add(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_cas(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_max(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_min(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t shfl_up_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

uint64_t atom_or(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_xor(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_and(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_sub(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t atom_exch(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

uint64_t ballot_sync(uint64_t pred);  /* extern: forge_gpu */

uint64_t lane_id(void);  /* extern: forge_gpu */

uint64_t warp_id(void);  /* extern: forge_gpu */

float shfl_xor_sync_f32(float val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

float shfl_down_sync_f32(float val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

static const uint32_t M31_P = 2147483647ULL;

/* Tuple typedefs */
typedef struct { uint32_t _0; uint32_t _1; uint32_t _2; uint32_t _3; } __forge_tuple_u32_u32_u32_u32_t;

/* Forward declarations */
static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused)));
static uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused)));
static uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused)));
static uint32_t m31_add(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t m31_sub(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t m31_mul(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t m31_neg(uint32_t a __attribute__((unused)));
static uint32_t m31_double(uint32_t a __attribute__((unused)));
static uint32_t cm31_mul_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
static uint32_t cm31_mul_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
static uint32_t cm31_add_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused)));
static uint32_t cm31_add_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused)));
static uint32_t cm31_sub_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused)));
static uint32_t cm31_sub_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused)));
static uint32_t qm31_mul_out_re_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
static uint32_t qm31_mul_out_re_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
static uint32_t qm31_mul_out_im_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
static uint32_t qm31_mul_out_im_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
static uint32_t qm31_add_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t qm31_add_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t qm31_add_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t qm31_add_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t qm31_sub_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t qm31_sub_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t qm31_sub_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static uint32_t qm31_sub_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static __device__ __forceinline__ uint32_t iv0();
static __device__ __forceinline__ uint32_t iv1();
static __device__ __forceinline__ uint32_t iv2();
static __device__ __forceinline__ uint32_t iv3();
static __device__ __forceinline__ uint32_t iv4();
static __device__ __forceinline__ uint32_t iv5();
static __device__ __forceinline__ uint32_t iv6();
static __device__ __forceinline__ uint32_t iv7();
static __device__ __forceinline__ uint32_t rotr32(uint32_t x __attribute__((unused)), uint32_t n __attribute__((unused)));
static __device__ __forceinline__ __forge_tuple_u32_u32_u32_u32_t g_mix(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)), uint32_t c __attribute__((unused)), uint32_t d __attribute__((unused)), uint32_t x __attribute__((unused)), uint32_t y __attribute__((unused)));
static __device__ __forceinline__ uint32_t reduce_word(uint32_t v __attribute__((unused)));
__global__ void merkle_hash_leaves_single(forge_span_u32_t column __attribute__((unused)), forge_span_u32_t hashes __attribute__((unused)), uint64_t n_leaves __attribute__((unused)));
__global__ void merkle_hash_leaves_quad(forge_span_u32_t c0 __attribute__((unused)), forge_span_u32_t c1 __attribute__((unused)), forge_span_u32_t c2 __attribute__((unused)), forge_span_u32_t c3 __attribute__((unused)), forge_span_u32_t hashes __attribute__((unused)), uint64_t n_leaves __attribute__((unused)));

static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

static uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused))) {
  return ((block_idx * block_dim) + thread_idx);
}

static uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused))) {
  return (block_dim * grid_dim);
}

static uint32_t m31_add(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = (((uint64_t)a) + ((uint64_t)b));
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r;
  if ((s >= p)) {
    r = (s - p);
  } else {
    r = s;
  }
  return ((uint32_t)r);
}

static uint32_t m31_sub(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t a64 __attribute__((unused)) = ((uint64_t)a);
  uint64_t b64 __attribute__((unused)) = ((uint64_t)b);
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r;
  if ((a64 >= b64)) {
    r = (a64 - b64);
  } else {
    r = ((a64 + p) - b64);
  }
  return ((uint32_t)r);
}

static uint32_t m31_mul(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t prod __attribute__((unused)) = (((uint64_t)a) * ((uint64_t)b));
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r __attribute__((unused)) = (prod % p);
  return ((uint32_t)r);
}

static uint32_t m31_neg(uint32_t a __attribute__((unused))) {
  if ((a == 0ULL)) {
    return 0ULL;
  } else {
    return (M31_P - a);
  }
}

static uint32_t m31_double(uint32_t a __attribute__((unused))) {
  return m31_add(a, a);
}

static uint32_t cm31_mul_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  uint32_t ac __attribute__((unused)) = m31_mul(a_re, b_re);
  uint32_t bd __attribute__((unused)) = m31_mul(a_im, b_im);
  return m31_sub(ac, bd);
}

static uint32_t cm31_mul_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  uint32_t ad __attribute__((unused)) = m31_mul(a_re, b_im);
  uint32_t bc __attribute__((unused)) = m31_mul(a_im, b_re);
  return m31_add(ad, bc);
}

static uint32_t cm31_add_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused))) {
  return m31_add(a_re, b_re);
}

static uint32_t cm31_add_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  return m31_add(a_im, b_im);
}

static uint32_t cm31_sub_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused))) {
  return m31_sub(a_re, b_re);
}

static uint32_t cm31_sub_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  return m31_sub(a_im, b_im);
}

static uint32_t qm31_mul_out_re_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ac_re __attribute__((unused)) = cm31_mul_re(a_re, a_im, c_re, c_im);
  uint32_t bd_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, d_re, d_im);
  uint32_t bd_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, d_re, d_im);
  uint32_t t __attribute__((unused)) = m31_sub(m31_double(bd_re), bd_im);
  return m31_add(ac_re, t);
}

static uint32_t qm31_mul_out_re_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ac_im __attribute__((unused)) = cm31_mul_im(a_re, a_im, c_re, c_im);
  uint32_t bd_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, d_re, d_im);
  uint32_t bd_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, d_re, d_im);
  uint32_t t __attribute__((unused)) = m31_add(bd_re, m31_double(bd_im));
  return m31_add(ac_im, t);
}

static uint32_t qm31_mul_out_im_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ad_re __attribute__((unused)) = cm31_mul_re(a_re, a_im, d_re, d_im);
  uint32_t bc_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, c_re, c_im);
  return m31_add(ad_re, bc_re);
}

static uint32_t qm31_mul_out_im_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ad_im __attribute__((unused)) = cm31_mul_im(a_re, a_im, d_re, d_im);
  uint32_t bc_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, c_re, c_im);
  return m31_add(ad_im, bc_im);
}

static uint32_t qm31_add_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

static uint32_t qm31_add_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

static uint32_t qm31_add_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

static uint32_t qm31_add_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

static uint32_t qm31_sub_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

static uint32_t qm31_sub_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

static uint32_t qm31_sub_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

static uint32_t qm31_sub_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

static __device__ __forceinline__ uint32_t iv0() {
  return 1779033703ULL;
}

static __device__ __forceinline__ uint32_t iv1() {
  return 3144134277ULL;
}

static __device__ __forceinline__ uint32_t iv2() {
  return 1013904242ULL;
}

static __device__ __forceinline__ uint32_t iv3() {
  return 2773480762ULL;
}

static __device__ __forceinline__ uint32_t iv4() {
  return 1359893119ULL;
}

static __device__ __forceinline__ uint32_t iv5() {
  return 2600822924ULL;
}

static __device__ __forceinline__ uint32_t iv6() {
  return 528734635ULL;
}

static __device__ __forceinline__ uint32_t iv7() {
  return 1541459225ULL;
}

static __device__ __forceinline__ uint32_t rotr32(uint32_t x __attribute__((unused)), uint32_t n __attribute__((unused))) {
  return ((x >> n) | (x << (32ULL - n)));
}

static __device__ __forceinline__ __forge_tuple_u32_u32_u32_u32_t g_mix(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)), uint32_t c __attribute__((unused)), uint32_t d __attribute__((unused)), uint32_t x __attribute__((unused)), uint32_t y __attribute__((unused))) {
  uint32_t a1 __attribute__((unused)) = ((a + b) + x);
  uint32_t d1 __attribute__((unused)) = rotr32((d ^ a1), 16ULL);
  uint32_t c1 __attribute__((unused)) = (c + d1);
  uint32_t b1 __attribute__((unused)) = rotr32((b ^ c1), 12ULL);
  uint32_t a2 __attribute__((unused)) = ((a1 + b1) + y);
  uint32_t d2 __attribute__((unused)) = rotr32((d1 ^ a2), 8ULL);
  uint32_t c2 __attribute__((unused)) = (c1 + d2);
  uint32_t b2 __attribute__((unused)) = rotr32((b1 ^ c2), 7ULL);
  return FORGE_AGG(__forge_tuple_u32_u32_u32_u32_t, a2, b2, c2, d2);
}

static __device__ __forceinline__ uint32_t reduce_word(uint32_t v __attribute__((unused))) {
  uint32_t lo __attribute__((unused)) = (v & M31_P);
  uint32_t hi __attribute__((unused)) = (v >> 31ULL);
  uint32_t r __attribute__((unused)) = (lo + hi);
  if ((r >= M31_P)) {
    return (r - M31_P);
  } else {
    return r;
  }
}

__global__ void merkle_hash_leaves_single(forge_span_u32_t column __attribute__((unused)), forge_span_u32_t hashes __attribute__((unused)), uint64_t n_leaves __attribute__((unused))) {
  uint64_t leaf __attribute__((unused)) = ((blockIdx_x * blockDim_x) + threadIdx_x);
  if ((leaf < n_leaves)) {
    uint32_t m0 __attribute__((unused)) = column.data[leaf];
    uint32_t m1 __attribute__((unused)) = 0ULL;
    uint32_t m2 __attribute__((unused)) = 0ULL;
    uint32_t m3 __attribute__((unused)) = 0ULL;
    uint32_t m4 __attribute__((unused)) = 0ULL;
    uint32_t m5 __attribute__((unused)) = 0ULL;
    uint32_t m6 __attribute__((unused)) = 0ULL;
    uint32_t m7 __attribute__((unused)) = 0ULL;
    uint32_t m8 __attribute__((unused)) = 0ULL;
    uint32_t m9 __attribute__((unused)) = 0ULL;
    uint32_t m10 __attribute__((unused)) = 0ULL;
    uint32_t m11 __attribute__((unused)) = 0ULL;
    uint32_t m12 __attribute__((unused)) = 0ULL;
    uint32_t m13 __attribute__((unused)) = 0ULL;
    uint32_t m14 __attribute__((unused)) = 0ULL;
    uint32_t m15 __attribute__((unused)) = 0ULL;
    uint32_t h0 __attribute__((unused)) = (iv0() ^ 16842784ULL);
    uint32_t h1 __attribute__((unused)) = iv1();
    uint32_t h2 __attribute__((unused)) = iv2();
    uint32_t h3 __attribute__((unused)) = iv3();
    uint32_t h4 __attribute__((unused)) = iv4();
    uint32_t h5 __attribute__((unused)) = iv5();
    uint32_t h6 __attribute__((unused)) = iv6();
    uint32_t h7 __attribute__((unused)) = iv7();
    uint32_t v0 __attribute__((unused)) = h0;
    uint32_t v1 __attribute__((unused)) = h1;
    uint32_t v2 __attribute__((unused)) = h2;
    uint32_t v3 __attribute__((unused)) = h3;
    uint32_t v4 __attribute__((unused)) = h4;
    uint32_t v5 __attribute__((unused)) = h5;
    uint32_t v6 __attribute__((unused)) = h6;
    uint32_t v7 __attribute__((unused)) = h7;
    uint32_t v8 __attribute__((unused)) = iv0();
    uint32_t v9 __attribute__((unused)) = iv1();
    uint32_t v10 __attribute__((unused)) = iv2();
    uint32_t v11 __attribute__((unused)) = iv3();
    uint32_t v12 __attribute__((unused)) = (iv4() ^ 4ULL);
    uint32_t v13 __attribute__((unused)) = iv5();
    uint32_t v14 __attribute__((unused)) = (iv6() ^ 4294967295ULL);
    uint32_t v15 __attribute__((unused)) = iv7();
    __forge_tuple_u32_u32_u32_u32_t __tup_135_8 __attribute__((unused)) = g_mix(v0, v4, v8, v12, m0, m1);
    uint32_t a0 __attribute__((unused)) = (__tup_135_8)._0;
    uint32_t b0 __attribute__((unused)) = (__tup_135_8)._1;
    uint32_t c0 __attribute__((unused)) = (__tup_135_8)._2;
    uint32_t d0 __attribute__((unused)) = (__tup_135_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_136_8 __attribute__((unused)) = g_mix(v1, v5, v9, v13, m2, m3);
    uint32_t a1 __attribute__((unused)) = (__tup_136_8)._0;
    uint32_t b1 __attribute__((unused)) = (__tup_136_8)._1;
    uint32_t c1 __attribute__((unused)) = (__tup_136_8)._2;
    uint32_t d1 __attribute__((unused)) = (__tup_136_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_137_8 __attribute__((unused)) = g_mix(v2, v6, v10, v14, m4, m5);
    uint32_t a2 __attribute__((unused)) = (__tup_137_8)._0;
    uint32_t b2 __attribute__((unused)) = (__tup_137_8)._1;
    uint32_t c2 __attribute__((unused)) = (__tup_137_8)._2;
    uint32_t d2 __attribute__((unused)) = (__tup_137_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_138_8 __attribute__((unused)) = g_mix(v3, v7, v11, v15, m6, m7);
    uint32_t a3 __attribute__((unused)) = (__tup_138_8)._0;
    uint32_t b3 __attribute__((unused)) = (__tup_138_8)._1;
    uint32_t c3 __attribute__((unused)) = (__tup_138_8)._2;
    uint32_t d3 __attribute__((unused)) = (__tup_138_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_139_8 __attribute__((unused)) = g_mix(a0, b1, c2, d3, m8, m9);
    uint32_t a4 __attribute__((unused)) = (__tup_139_8)._0;
    uint32_t b4 __attribute__((unused)) = (__tup_139_8)._1;
    uint32_t c4 __attribute__((unused)) = (__tup_139_8)._2;
    uint32_t d4 __attribute__((unused)) = (__tup_139_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_140_8 __attribute__((unused)) = g_mix(a1, b2, c3, d0, m10, m11);
    uint32_t a5 __attribute__((unused)) = (__tup_140_8)._0;
    uint32_t b5 __attribute__((unused)) = (__tup_140_8)._1;
    uint32_t c5 __attribute__((unused)) = (__tup_140_8)._2;
    uint32_t d5 __attribute__((unused)) = (__tup_140_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_141_8 __attribute__((unused)) = g_mix(a2, b3, c0, d1, m12, m13);
    uint32_t a6 __attribute__((unused)) = (__tup_141_8)._0;
    uint32_t b6 __attribute__((unused)) = (__tup_141_8)._1;
    uint32_t c6 __attribute__((unused)) = (__tup_141_8)._2;
    uint32_t d6 __attribute__((unused)) = (__tup_141_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_142_8 __attribute__((unused)) = g_mix(a3, b0, c1, d2, m14, m15);
    uint32_t a7 __attribute__((unused)) = (__tup_142_8)._0;
    uint32_t b7 __attribute__((unused)) = (__tup_142_8)._1;
    uint32_t c7 __attribute__((unused)) = (__tup_142_8)._2;
    uint32_t d7 __attribute__((unused)) = (__tup_142_8)._3;
    uint32_t r0_0 __attribute__((unused)) = a4;
    uint32_t r0_1 __attribute__((unused)) = a5;
    uint32_t r0_2 __attribute__((unused)) = a6;
    uint32_t r0_3 __attribute__((unused)) = a7;
    uint32_t r0_4 __attribute__((unused)) = b7;
    uint32_t r0_5 __attribute__((unused)) = b4;
    uint32_t r0_6 __attribute__((unused)) = b5;
    uint32_t r0_7 __attribute__((unused)) = b6;
    uint32_t r0_8 __attribute__((unused)) = c6;
    uint32_t r0_9 __attribute__((unused)) = c7;
    uint32_t r0_10 __attribute__((unused)) = c4;
    uint32_t r0_11 __attribute__((unused)) = c5;
    uint32_t r0_12 __attribute__((unused)) = d5;
    uint32_t r0_13 __attribute__((unused)) = d6;
    uint32_t r0_14 __attribute__((unused)) = d7;
    uint32_t r0_15 __attribute__((unused)) = d4;
    __forge_tuple_u32_u32_u32_u32_t __tup_151_8 __attribute__((unused)) = g_mix(r0_0, r0_4, r0_8, r0_12, m14, m10);
    uint32_t a0b __attribute__((unused)) = (__tup_151_8)._0;
    uint32_t b0b __attribute__((unused)) = (__tup_151_8)._1;
    uint32_t c0b __attribute__((unused)) = (__tup_151_8)._2;
    uint32_t d0b __attribute__((unused)) = (__tup_151_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_152_8 __attribute__((unused)) = g_mix(r0_1, r0_5, r0_9, r0_13, m4, m8);
    uint32_t a1b __attribute__((unused)) = (__tup_152_8)._0;
    uint32_t b1b __attribute__((unused)) = (__tup_152_8)._1;
    uint32_t c1b __attribute__((unused)) = (__tup_152_8)._2;
    uint32_t d1b __attribute__((unused)) = (__tup_152_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_153_8 __attribute__((unused)) = g_mix(r0_2, r0_6, r0_10, r0_14, m9, m15);
    uint32_t a2b __attribute__((unused)) = (__tup_153_8)._0;
    uint32_t b2b __attribute__((unused)) = (__tup_153_8)._1;
    uint32_t c2b __attribute__((unused)) = (__tup_153_8)._2;
    uint32_t d2b __attribute__((unused)) = (__tup_153_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_154_8 __attribute__((unused)) = g_mix(r0_3, r0_7, r0_11, r0_15, m13, m6);
    uint32_t a3b __attribute__((unused)) = (__tup_154_8)._0;
    uint32_t b3b __attribute__((unused)) = (__tup_154_8)._1;
    uint32_t c3b __attribute__((unused)) = (__tup_154_8)._2;
    uint32_t d3b __attribute__((unused)) = (__tup_154_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_155_8 __attribute__((unused)) = g_mix(a0b, b1b, c2b, d3b, m1, m12);
    uint32_t a4b __attribute__((unused)) = (__tup_155_8)._0;
    uint32_t b4b __attribute__((unused)) = (__tup_155_8)._1;
    uint32_t c4b __attribute__((unused)) = (__tup_155_8)._2;
    uint32_t d4b __attribute__((unused)) = (__tup_155_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_156_8 __attribute__((unused)) = g_mix(a1b, b2b, c3b, d0b, m0, m2);
    uint32_t a5b __attribute__((unused)) = (__tup_156_8)._0;
    uint32_t b5b __attribute__((unused)) = (__tup_156_8)._1;
    uint32_t c5b __attribute__((unused)) = (__tup_156_8)._2;
    uint32_t d5b __attribute__((unused)) = (__tup_156_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_157_8 __attribute__((unused)) = g_mix(a2b, b3b, c0b, d1b, m11, m7);
    uint32_t a6b __attribute__((unused)) = (__tup_157_8)._0;
    uint32_t b6b __attribute__((unused)) = (__tup_157_8)._1;
    uint32_t c6b __attribute__((unused)) = (__tup_157_8)._2;
    uint32_t d6b __attribute__((unused)) = (__tup_157_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_158_8 __attribute__((unused)) = g_mix(a3b, b0b, c1b, d2b, m5, m3);
    uint32_t a7b __attribute__((unused)) = (__tup_158_8)._0;
    uint32_t b7b __attribute__((unused)) = (__tup_158_8)._1;
    uint32_t c7b __attribute__((unused)) = (__tup_158_8)._2;
    uint32_t d7b __attribute__((unused)) = (__tup_158_8)._3;
    uint32_t r1_0 __attribute__((unused)) = a4b;
    uint32_t r1_1 __attribute__((unused)) = a5b;
    uint32_t r1_2 __attribute__((unused)) = a6b;
    uint32_t r1_3 __attribute__((unused)) = a7b;
    uint32_t r1_4 __attribute__((unused)) = b7b;
    uint32_t r1_5 __attribute__((unused)) = b4b;
    uint32_t r1_6 __attribute__((unused)) = b5b;
    uint32_t r1_7 __attribute__((unused)) = b6b;
    uint32_t r1_8 __attribute__((unused)) = c6b;
    uint32_t r1_9 __attribute__((unused)) = c7b;
    uint32_t r1_10 __attribute__((unused)) = c4b;
    uint32_t r1_11 __attribute__((unused)) = c5b;
    uint32_t r1_12 __attribute__((unused)) = d5b;
    uint32_t r1_13 __attribute__((unused)) = d6b;
    uint32_t r1_14 __attribute__((unused)) = d7b;
    uint32_t r1_15 __attribute__((unused)) = d4b;
    __forge_tuple_u32_u32_u32_u32_t __tup_165_8 __attribute__((unused)) = g_mix(r1_0, r1_4, r1_8, r1_12, m11, m8);
    uint32_t a0c __attribute__((unused)) = (__tup_165_8)._0;
    uint32_t b0c __attribute__((unused)) = (__tup_165_8)._1;
    uint32_t c0c __attribute__((unused)) = (__tup_165_8)._2;
    uint32_t d0c __attribute__((unused)) = (__tup_165_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_166_8 __attribute__((unused)) = g_mix(r1_1, r1_5, r1_9, r1_13, m12, m0);
    uint32_t a1c __attribute__((unused)) = (__tup_166_8)._0;
    uint32_t b1c __attribute__((unused)) = (__tup_166_8)._1;
    uint32_t c1c __attribute__((unused)) = (__tup_166_8)._2;
    uint32_t d1c __attribute__((unused)) = (__tup_166_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_167_8 __attribute__((unused)) = g_mix(r1_2, r1_6, r1_10, r1_14, m5, m2);
    uint32_t a2c __attribute__((unused)) = (__tup_167_8)._0;
    uint32_t b2c __attribute__((unused)) = (__tup_167_8)._1;
    uint32_t c2c __attribute__((unused)) = (__tup_167_8)._2;
    uint32_t d2c __attribute__((unused)) = (__tup_167_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_168_8 __attribute__((unused)) = g_mix(r1_3, r1_7, r1_11, r1_15, m15, m13);
    uint32_t a3c __attribute__((unused)) = (__tup_168_8)._0;
    uint32_t b3c __attribute__((unused)) = (__tup_168_8)._1;
    uint32_t c3c __attribute__((unused)) = (__tup_168_8)._2;
    uint32_t d3c __attribute__((unused)) = (__tup_168_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_169_8 __attribute__((unused)) = g_mix(a0c, b1c, c2c, d3c, m10, m14);
    uint32_t a4c __attribute__((unused)) = (__tup_169_8)._0;
    uint32_t b4c __attribute__((unused)) = (__tup_169_8)._1;
    uint32_t c4c __attribute__((unused)) = (__tup_169_8)._2;
    uint32_t d4c __attribute__((unused)) = (__tup_169_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_170_8 __attribute__((unused)) = g_mix(a1c, b2c, c3c, d0c, m3, m6);
    uint32_t a5c __attribute__((unused)) = (__tup_170_8)._0;
    uint32_t b5c __attribute__((unused)) = (__tup_170_8)._1;
    uint32_t c5c __attribute__((unused)) = (__tup_170_8)._2;
    uint32_t d5c __attribute__((unused)) = (__tup_170_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_171_8 __attribute__((unused)) = g_mix(a2c, b3c, c0c, d1c, m7, m1);
    uint32_t a6c __attribute__((unused)) = (__tup_171_8)._0;
    uint32_t b6c __attribute__((unused)) = (__tup_171_8)._1;
    uint32_t c6c __attribute__((unused)) = (__tup_171_8)._2;
    uint32_t d6c __attribute__((unused)) = (__tup_171_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_172_8 __attribute__((unused)) = g_mix(a3c, b0c, c1c, d2c, m9, m4);
    uint32_t a7c __attribute__((unused)) = (__tup_172_8)._0;
    uint32_t b7c __attribute__((unused)) = (__tup_172_8)._1;
    uint32_t c7c __attribute__((unused)) = (__tup_172_8)._2;
    uint32_t d7c __attribute__((unused)) = (__tup_172_8)._3;
    uint32_t r2_0 __attribute__((unused)) = a4c;
    uint32_t r2_1 __attribute__((unused)) = a5c;
    uint32_t r2_2 __attribute__((unused)) = a6c;
    uint32_t r2_3 __attribute__((unused)) = a7c;
    uint32_t r2_4 __attribute__((unused)) = b7c;
    uint32_t r2_5 __attribute__((unused)) = b4c;
    uint32_t r2_6 __attribute__((unused)) = b5c;
    uint32_t r2_7 __attribute__((unused)) = b6c;
    uint32_t r2_8 __attribute__((unused)) = c6c;
    uint32_t r2_9 __attribute__((unused)) = c7c;
    uint32_t r2_10 __attribute__((unused)) = c4c;
    uint32_t r2_11 __attribute__((unused)) = c5c;
    uint32_t r2_12 __attribute__((unused)) = d5c;
    uint32_t r2_13 __attribute__((unused)) = d6c;
    uint32_t r2_14 __attribute__((unused)) = d7c;
    uint32_t r2_15 __attribute__((unused)) = d4c;
    __forge_tuple_u32_u32_u32_u32_t __tup_179_8 __attribute__((unused)) = g_mix(r2_0, r2_4, r2_8, r2_12, m7, m9);
    uint32_t a0d __attribute__((unused)) = (__tup_179_8)._0;
    uint32_t b0d __attribute__((unused)) = (__tup_179_8)._1;
    uint32_t c0d __attribute__((unused)) = (__tup_179_8)._2;
    uint32_t d0d __attribute__((unused)) = (__tup_179_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_180_8 __attribute__((unused)) = g_mix(r2_1, r2_5, r2_9, r2_13, m3, m1);
    uint32_t a1d __attribute__((unused)) = (__tup_180_8)._0;
    uint32_t b1d __attribute__((unused)) = (__tup_180_8)._1;
    uint32_t c1d __attribute__((unused)) = (__tup_180_8)._2;
    uint32_t d1d __attribute__((unused)) = (__tup_180_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_181_8 __attribute__((unused)) = g_mix(r2_2, r2_6, r2_10, r2_14, m13, m12);
    uint32_t a2d __attribute__((unused)) = (__tup_181_8)._0;
    uint32_t b2d __attribute__((unused)) = (__tup_181_8)._1;
    uint32_t c2d __attribute__((unused)) = (__tup_181_8)._2;
    uint32_t d2d __attribute__((unused)) = (__tup_181_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_182_8 __attribute__((unused)) = g_mix(r2_3, r2_7, r2_11, r2_15, m11, m14);
    uint32_t a3d __attribute__((unused)) = (__tup_182_8)._0;
    uint32_t b3d __attribute__((unused)) = (__tup_182_8)._1;
    uint32_t c3d __attribute__((unused)) = (__tup_182_8)._2;
    uint32_t d3d __attribute__((unused)) = (__tup_182_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_183_8 __attribute__((unused)) = g_mix(a0d, b1d, c2d, d3d, m2, m6);
    uint32_t a4d __attribute__((unused)) = (__tup_183_8)._0;
    uint32_t b4d __attribute__((unused)) = (__tup_183_8)._1;
    uint32_t c4d __attribute__((unused)) = (__tup_183_8)._2;
    uint32_t d4d __attribute__((unused)) = (__tup_183_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_184_8 __attribute__((unused)) = g_mix(a1d, b2d, c3d, d0d, m5, m10);
    uint32_t a5d __attribute__((unused)) = (__tup_184_8)._0;
    uint32_t b5d __attribute__((unused)) = (__tup_184_8)._1;
    uint32_t c5d __attribute__((unused)) = (__tup_184_8)._2;
    uint32_t d5d __attribute__((unused)) = (__tup_184_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_185_8 __attribute__((unused)) = g_mix(a2d, b3d, c0d, d1d, m4, m0);
    uint32_t a6d __attribute__((unused)) = (__tup_185_8)._0;
    uint32_t b6d __attribute__((unused)) = (__tup_185_8)._1;
    uint32_t c6d __attribute__((unused)) = (__tup_185_8)._2;
    uint32_t d6d __attribute__((unused)) = (__tup_185_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_186_8 __attribute__((unused)) = g_mix(a3d, b0d, c1d, d2d, m15, m8);
    uint32_t a7d __attribute__((unused)) = (__tup_186_8)._0;
    uint32_t b7d __attribute__((unused)) = (__tup_186_8)._1;
    uint32_t c7d __attribute__((unused)) = (__tup_186_8)._2;
    uint32_t d7d __attribute__((unused)) = (__tup_186_8)._3;
    uint32_t r3_0 __attribute__((unused)) = a4d;
    uint32_t r3_1 __attribute__((unused)) = a5d;
    uint32_t r3_2 __attribute__((unused)) = a6d;
    uint32_t r3_3 __attribute__((unused)) = a7d;
    uint32_t r3_4 __attribute__((unused)) = b7d;
    uint32_t r3_5 __attribute__((unused)) = b4d;
    uint32_t r3_6 __attribute__((unused)) = b5d;
    uint32_t r3_7 __attribute__((unused)) = b6d;
    uint32_t r3_8 __attribute__((unused)) = c6d;
    uint32_t r3_9 __attribute__((unused)) = c7d;
    uint32_t r3_10 __attribute__((unused)) = c4d;
    uint32_t r3_11 __attribute__((unused)) = c5d;
    uint32_t r3_12 __attribute__((unused)) = d5d;
    uint32_t r3_13 __attribute__((unused)) = d6d;
    uint32_t r3_14 __attribute__((unused)) = d7d;
    uint32_t r3_15 __attribute__((unused)) = d4d;
    __forge_tuple_u32_u32_u32_u32_t __tup_193_8 __attribute__((unused)) = g_mix(r3_0, r3_4, r3_8, r3_12, m9, m0);
    uint32_t a0e __attribute__((unused)) = (__tup_193_8)._0;
    uint32_t b0e __attribute__((unused)) = (__tup_193_8)._1;
    uint32_t c0e __attribute__((unused)) = (__tup_193_8)._2;
    uint32_t d0e __attribute__((unused)) = (__tup_193_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_194_8 __attribute__((unused)) = g_mix(r3_1, r3_5, r3_9, r3_13, m5, m7);
    uint32_t a1e __attribute__((unused)) = (__tup_194_8)._0;
    uint32_t b1e __attribute__((unused)) = (__tup_194_8)._1;
    uint32_t c1e __attribute__((unused)) = (__tup_194_8)._2;
    uint32_t d1e __attribute__((unused)) = (__tup_194_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_195_8 __attribute__((unused)) = g_mix(r3_2, r3_6, r3_10, r3_14, m2, m4);
    uint32_t a2e __attribute__((unused)) = (__tup_195_8)._0;
    uint32_t b2e __attribute__((unused)) = (__tup_195_8)._1;
    uint32_t c2e __attribute__((unused)) = (__tup_195_8)._2;
    uint32_t d2e __attribute__((unused)) = (__tup_195_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_196_8 __attribute__((unused)) = g_mix(r3_3, r3_7, r3_11, r3_15, m10, m15);
    uint32_t a3e __attribute__((unused)) = (__tup_196_8)._0;
    uint32_t b3e __attribute__((unused)) = (__tup_196_8)._1;
    uint32_t c3e __attribute__((unused)) = (__tup_196_8)._2;
    uint32_t d3e __attribute__((unused)) = (__tup_196_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_197_8 __attribute__((unused)) = g_mix(a0e, b1e, c2e, d3e, m14, m1);
    uint32_t a4e __attribute__((unused)) = (__tup_197_8)._0;
    uint32_t b4e __attribute__((unused)) = (__tup_197_8)._1;
    uint32_t c4e __attribute__((unused)) = (__tup_197_8)._2;
    uint32_t d4e __attribute__((unused)) = (__tup_197_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_198_8 __attribute__((unused)) = g_mix(a1e, b2e, c3e, d0e, m11, m12);
    uint32_t a5e __attribute__((unused)) = (__tup_198_8)._0;
    uint32_t b5e __attribute__((unused)) = (__tup_198_8)._1;
    uint32_t c5e __attribute__((unused)) = (__tup_198_8)._2;
    uint32_t d5e __attribute__((unused)) = (__tup_198_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_199_8 __attribute__((unused)) = g_mix(a2e, b3e, c0e, d1e, m6, m8);
    uint32_t a6e __attribute__((unused)) = (__tup_199_8)._0;
    uint32_t b6e __attribute__((unused)) = (__tup_199_8)._1;
    uint32_t c6e __attribute__((unused)) = (__tup_199_8)._2;
    uint32_t d6e __attribute__((unused)) = (__tup_199_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_200_8 __attribute__((unused)) = g_mix(a3e, b0e, c1e, d2e, m3, m13);
    uint32_t a7e __attribute__((unused)) = (__tup_200_8)._0;
    uint32_t b7e __attribute__((unused)) = (__tup_200_8)._1;
    uint32_t c7e __attribute__((unused)) = (__tup_200_8)._2;
    uint32_t d7e __attribute__((unused)) = (__tup_200_8)._3;
    uint32_t r4_0 __attribute__((unused)) = a4e;
    uint32_t r4_1 __attribute__((unused)) = a5e;
    uint32_t r4_2 __attribute__((unused)) = a6e;
    uint32_t r4_3 __attribute__((unused)) = a7e;
    uint32_t r4_4 __attribute__((unused)) = b7e;
    uint32_t r4_5 __attribute__((unused)) = b4e;
    uint32_t r4_6 __attribute__((unused)) = b5e;
    uint32_t r4_7 __attribute__((unused)) = b6e;
    uint32_t r4_8 __attribute__((unused)) = c6e;
    uint32_t r4_9 __attribute__((unused)) = c7e;
    uint32_t r4_10 __attribute__((unused)) = c4e;
    uint32_t r4_11 __attribute__((unused)) = c5e;
    uint32_t r4_12 __attribute__((unused)) = d5e;
    uint32_t r4_13 __attribute__((unused)) = d6e;
    uint32_t r4_14 __attribute__((unused)) = d7e;
    uint32_t r4_15 __attribute__((unused)) = d4e;
    __forge_tuple_u32_u32_u32_u32_t __tup_207_8 __attribute__((unused)) = g_mix(r4_0, r4_4, r4_8, r4_12, m2, m12);
    uint32_t a0f __attribute__((unused)) = (__tup_207_8)._0;
    uint32_t b0f __attribute__((unused)) = (__tup_207_8)._1;
    uint32_t c0f __attribute__((unused)) = (__tup_207_8)._2;
    uint32_t d0f __attribute__((unused)) = (__tup_207_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_208_8 __attribute__((unused)) = g_mix(r4_1, r4_5, r4_9, r4_13, m6, m10);
    uint32_t a1f __attribute__((unused)) = (__tup_208_8)._0;
    uint32_t b1f __attribute__((unused)) = (__tup_208_8)._1;
    uint32_t c1f __attribute__((unused)) = (__tup_208_8)._2;
    uint32_t d1f __attribute__((unused)) = (__tup_208_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_209_8 __attribute__((unused)) = g_mix(r4_2, r4_6, r4_10, r4_14, m0, m11);
    uint32_t a2f __attribute__((unused)) = (__tup_209_8)._0;
    uint32_t b2f __attribute__((unused)) = (__tup_209_8)._1;
    uint32_t c2f __attribute__((unused)) = (__tup_209_8)._2;
    uint32_t d2f __attribute__((unused)) = (__tup_209_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_210_8 __attribute__((unused)) = g_mix(r4_3, r4_7, r4_11, r4_15, m8, m3);
    uint32_t a3f __attribute__((unused)) = (__tup_210_8)._0;
    uint32_t b3f __attribute__((unused)) = (__tup_210_8)._1;
    uint32_t c3f __attribute__((unused)) = (__tup_210_8)._2;
    uint32_t d3f __attribute__((unused)) = (__tup_210_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_211_8 __attribute__((unused)) = g_mix(a0f, b1f, c2f, d3f, m4, m13);
    uint32_t a4f __attribute__((unused)) = (__tup_211_8)._0;
    uint32_t b4f __attribute__((unused)) = (__tup_211_8)._1;
    uint32_t c4f __attribute__((unused)) = (__tup_211_8)._2;
    uint32_t d4f __attribute__((unused)) = (__tup_211_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_212_8 __attribute__((unused)) = g_mix(a1f, b2f, c3f, d0f, m7, m5);
    uint32_t a5f __attribute__((unused)) = (__tup_212_8)._0;
    uint32_t b5f __attribute__((unused)) = (__tup_212_8)._1;
    uint32_t c5f __attribute__((unused)) = (__tup_212_8)._2;
    uint32_t d5f __attribute__((unused)) = (__tup_212_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_213_8 __attribute__((unused)) = g_mix(a2f, b3f, c0f, d1f, m15, m14);
    uint32_t a6f __attribute__((unused)) = (__tup_213_8)._0;
    uint32_t b6f __attribute__((unused)) = (__tup_213_8)._1;
    uint32_t c6f __attribute__((unused)) = (__tup_213_8)._2;
    uint32_t d6f __attribute__((unused)) = (__tup_213_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_214_8 __attribute__((unused)) = g_mix(a3f, b0f, c1f, d2f, m1, m9);
    uint32_t a7f __attribute__((unused)) = (__tup_214_8)._0;
    uint32_t b7f __attribute__((unused)) = (__tup_214_8)._1;
    uint32_t c7f __attribute__((unused)) = (__tup_214_8)._2;
    uint32_t d7f __attribute__((unused)) = (__tup_214_8)._3;
    uint32_t r5_0 __attribute__((unused)) = a4f;
    uint32_t r5_1 __attribute__((unused)) = a5f;
    uint32_t r5_2 __attribute__((unused)) = a6f;
    uint32_t r5_3 __attribute__((unused)) = a7f;
    uint32_t r5_4 __attribute__((unused)) = b7f;
    uint32_t r5_5 __attribute__((unused)) = b4f;
    uint32_t r5_6 __attribute__((unused)) = b5f;
    uint32_t r5_7 __attribute__((unused)) = b6f;
    uint32_t r5_8 __attribute__((unused)) = c6f;
    uint32_t r5_9 __attribute__((unused)) = c7f;
    uint32_t r5_10 __attribute__((unused)) = c4f;
    uint32_t r5_11 __attribute__((unused)) = c5f;
    uint32_t r5_12 __attribute__((unused)) = d5f;
    uint32_t r5_13 __attribute__((unused)) = d6f;
    uint32_t r5_14 __attribute__((unused)) = d7f;
    uint32_t r5_15 __attribute__((unused)) = d4f;
    __forge_tuple_u32_u32_u32_u32_t __tup_221_8 __attribute__((unused)) = g_mix(r5_0, r5_4, r5_8, r5_12, m12, m5);
    uint32_t a0g __attribute__((unused)) = (__tup_221_8)._0;
    uint32_t b0g __attribute__((unused)) = (__tup_221_8)._1;
    uint32_t c0g __attribute__((unused)) = (__tup_221_8)._2;
    uint32_t d0g __attribute__((unused)) = (__tup_221_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_222_8 __attribute__((unused)) = g_mix(r5_1, r5_5, r5_9, r5_13, m1, m15);
    uint32_t a1g __attribute__((unused)) = (__tup_222_8)._0;
    uint32_t b1g __attribute__((unused)) = (__tup_222_8)._1;
    uint32_t c1g __attribute__((unused)) = (__tup_222_8)._2;
    uint32_t d1g __attribute__((unused)) = (__tup_222_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_223_8 __attribute__((unused)) = g_mix(r5_2, r5_6, r5_10, r5_14, m14, m13);
    uint32_t a2g __attribute__((unused)) = (__tup_223_8)._0;
    uint32_t b2g __attribute__((unused)) = (__tup_223_8)._1;
    uint32_t c2g __attribute__((unused)) = (__tup_223_8)._2;
    uint32_t d2g __attribute__((unused)) = (__tup_223_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_224_8 __attribute__((unused)) = g_mix(r5_3, r5_7, r5_11, r5_15, m4, m10);
    uint32_t a3g __attribute__((unused)) = (__tup_224_8)._0;
    uint32_t b3g __attribute__((unused)) = (__tup_224_8)._1;
    uint32_t c3g __attribute__((unused)) = (__tup_224_8)._2;
    uint32_t d3g __attribute__((unused)) = (__tup_224_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_225_8 __attribute__((unused)) = g_mix(a0g, b1g, c2g, d3g, m0, m7);
    uint32_t a4g __attribute__((unused)) = (__tup_225_8)._0;
    uint32_t b4g __attribute__((unused)) = (__tup_225_8)._1;
    uint32_t c4g __attribute__((unused)) = (__tup_225_8)._2;
    uint32_t d4g __attribute__((unused)) = (__tup_225_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_226_8 __attribute__((unused)) = g_mix(a1g, b2g, c3g, d0g, m6, m3);
    uint32_t a5g __attribute__((unused)) = (__tup_226_8)._0;
    uint32_t b5g __attribute__((unused)) = (__tup_226_8)._1;
    uint32_t c5g __attribute__((unused)) = (__tup_226_8)._2;
    uint32_t d5g __attribute__((unused)) = (__tup_226_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_227_8 __attribute__((unused)) = g_mix(a2g, b3g, c0g, d1g, m9, m2);
    uint32_t a6g __attribute__((unused)) = (__tup_227_8)._0;
    uint32_t b6g __attribute__((unused)) = (__tup_227_8)._1;
    uint32_t c6g __attribute__((unused)) = (__tup_227_8)._2;
    uint32_t d6g __attribute__((unused)) = (__tup_227_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_228_8 __attribute__((unused)) = g_mix(a3g, b0g, c1g, d2g, m8, m11);
    uint32_t a7g __attribute__((unused)) = (__tup_228_8)._0;
    uint32_t b7g __attribute__((unused)) = (__tup_228_8)._1;
    uint32_t c7g __attribute__((unused)) = (__tup_228_8)._2;
    uint32_t d7g __attribute__((unused)) = (__tup_228_8)._3;
    uint32_t r6_0 __attribute__((unused)) = a4g;
    uint32_t r6_1 __attribute__((unused)) = a5g;
    uint32_t r6_2 __attribute__((unused)) = a6g;
    uint32_t r6_3 __attribute__((unused)) = a7g;
    uint32_t r6_4 __attribute__((unused)) = b7g;
    uint32_t r6_5 __attribute__((unused)) = b4g;
    uint32_t r6_6 __attribute__((unused)) = b5g;
    uint32_t r6_7 __attribute__((unused)) = b6g;
    uint32_t r6_8 __attribute__((unused)) = c6g;
    uint32_t r6_9 __attribute__((unused)) = c7g;
    uint32_t r6_10 __attribute__((unused)) = c4g;
    uint32_t r6_11 __attribute__((unused)) = c5g;
    uint32_t r6_12 __attribute__((unused)) = d5g;
    uint32_t r6_13 __attribute__((unused)) = d6g;
    uint32_t r6_14 __attribute__((unused)) = d7g;
    uint32_t r6_15 __attribute__((unused)) = d4g;
    __forge_tuple_u32_u32_u32_u32_t __tup_235_8 __attribute__((unused)) = g_mix(r6_0, r6_4, r6_8, r6_12, m13, m11);
    uint32_t a0h __attribute__((unused)) = (__tup_235_8)._0;
    uint32_t b0h __attribute__((unused)) = (__tup_235_8)._1;
    uint32_t c0h __attribute__((unused)) = (__tup_235_8)._2;
    uint32_t d0h __attribute__((unused)) = (__tup_235_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_236_8 __attribute__((unused)) = g_mix(r6_1, r6_5, r6_9, r6_13, m7, m14);
    uint32_t a1h __attribute__((unused)) = (__tup_236_8)._0;
    uint32_t b1h __attribute__((unused)) = (__tup_236_8)._1;
    uint32_t c1h __attribute__((unused)) = (__tup_236_8)._2;
    uint32_t d1h __attribute__((unused)) = (__tup_236_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_237_8 __attribute__((unused)) = g_mix(r6_2, r6_6, r6_10, r6_14, m12, m1);
    uint32_t a2h __attribute__((unused)) = (__tup_237_8)._0;
    uint32_t b2h __attribute__((unused)) = (__tup_237_8)._1;
    uint32_t c2h __attribute__((unused)) = (__tup_237_8)._2;
    uint32_t d2h __attribute__((unused)) = (__tup_237_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_238_8 __attribute__((unused)) = g_mix(r6_3, r6_7, r6_11, r6_15, m3, m9);
    uint32_t a3h __attribute__((unused)) = (__tup_238_8)._0;
    uint32_t b3h __attribute__((unused)) = (__tup_238_8)._1;
    uint32_t c3h __attribute__((unused)) = (__tup_238_8)._2;
    uint32_t d3h __attribute__((unused)) = (__tup_238_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_239_8 __attribute__((unused)) = g_mix(a0h, b1h, c2h, d3h, m5, m0);
    uint32_t a4h __attribute__((unused)) = (__tup_239_8)._0;
    uint32_t b4h __attribute__((unused)) = (__tup_239_8)._1;
    uint32_t c4h __attribute__((unused)) = (__tup_239_8)._2;
    uint32_t d4h __attribute__((unused)) = (__tup_239_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_240_8 __attribute__((unused)) = g_mix(a1h, b2h, c3h, d0h, m15, m4);
    uint32_t a5h __attribute__((unused)) = (__tup_240_8)._0;
    uint32_t b5h __attribute__((unused)) = (__tup_240_8)._1;
    uint32_t c5h __attribute__((unused)) = (__tup_240_8)._2;
    uint32_t d5h __attribute__((unused)) = (__tup_240_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_241_8 __attribute__((unused)) = g_mix(a2h, b3h, c0h, d1h, m8, m6);
    uint32_t a6h __attribute__((unused)) = (__tup_241_8)._0;
    uint32_t b6h __attribute__((unused)) = (__tup_241_8)._1;
    uint32_t c6h __attribute__((unused)) = (__tup_241_8)._2;
    uint32_t d6h __attribute__((unused)) = (__tup_241_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_242_8 __attribute__((unused)) = g_mix(a3h, b0h, c1h, d2h, m2, m10);
    uint32_t a7h __attribute__((unused)) = (__tup_242_8)._0;
    uint32_t b7h __attribute__((unused)) = (__tup_242_8)._1;
    uint32_t c7h __attribute__((unused)) = (__tup_242_8)._2;
    uint32_t d7h __attribute__((unused)) = (__tup_242_8)._3;
    uint32_t r7_0 __attribute__((unused)) = a4h;
    uint32_t r7_1 __attribute__((unused)) = a5h;
    uint32_t r7_2 __attribute__((unused)) = a6h;
    uint32_t r7_3 __attribute__((unused)) = a7h;
    uint32_t r7_4 __attribute__((unused)) = b7h;
    uint32_t r7_5 __attribute__((unused)) = b4h;
    uint32_t r7_6 __attribute__((unused)) = b5h;
    uint32_t r7_7 __attribute__((unused)) = b6h;
    uint32_t r7_8 __attribute__((unused)) = c6h;
    uint32_t r7_9 __attribute__((unused)) = c7h;
    uint32_t r7_10 __attribute__((unused)) = c4h;
    uint32_t r7_11 __attribute__((unused)) = c5h;
    uint32_t r7_12 __attribute__((unused)) = d5h;
    uint32_t r7_13 __attribute__((unused)) = d6h;
    uint32_t r7_14 __attribute__((unused)) = d7h;
    uint32_t r7_15 __attribute__((unused)) = d4h;
    __forge_tuple_u32_u32_u32_u32_t __tup_249_8 __attribute__((unused)) = g_mix(r7_0, r7_4, r7_8, r7_12, m6, m15);
    uint32_t a0i __attribute__((unused)) = (__tup_249_8)._0;
    uint32_t b0i __attribute__((unused)) = (__tup_249_8)._1;
    uint32_t c0i __attribute__((unused)) = (__tup_249_8)._2;
    uint32_t d0i __attribute__((unused)) = (__tup_249_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_250_8 __attribute__((unused)) = g_mix(r7_1, r7_5, r7_9, r7_13, m14, m9);
    uint32_t a1i __attribute__((unused)) = (__tup_250_8)._0;
    uint32_t b1i __attribute__((unused)) = (__tup_250_8)._1;
    uint32_t c1i __attribute__((unused)) = (__tup_250_8)._2;
    uint32_t d1i __attribute__((unused)) = (__tup_250_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_251_8 __attribute__((unused)) = g_mix(r7_2, r7_6, r7_10, r7_14, m11, m3);
    uint32_t a2i __attribute__((unused)) = (__tup_251_8)._0;
    uint32_t b2i __attribute__((unused)) = (__tup_251_8)._1;
    uint32_t c2i __attribute__((unused)) = (__tup_251_8)._2;
    uint32_t d2i __attribute__((unused)) = (__tup_251_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_252_8 __attribute__((unused)) = g_mix(r7_3, r7_7, r7_11, r7_15, m0, m8);
    uint32_t a3i __attribute__((unused)) = (__tup_252_8)._0;
    uint32_t b3i __attribute__((unused)) = (__tup_252_8)._1;
    uint32_t c3i __attribute__((unused)) = (__tup_252_8)._2;
    uint32_t d3i __attribute__((unused)) = (__tup_252_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_253_8 __attribute__((unused)) = g_mix(a0i, b1i, c2i, d3i, m12, m2);
    uint32_t a4i __attribute__((unused)) = (__tup_253_8)._0;
    uint32_t b4i __attribute__((unused)) = (__tup_253_8)._1;
    uint32_t c4i __attribute__((unused)) = (__tup_253_8)._2;
    uint32_t d4i __attribute__((unused)) = (__tup_253_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_254_8 __attribute__((unused)) = g_mix(a1i, b2i, c3i, d0i, m13, m7);
    uint32_t a5i __attribute__((unused)) = (__tup_254_8)._0;
    uint32_t b5i __attribute__((unused)) = (__tup_254_8)._1;
    uint32_t c5i __attribute__((unused)) = (__tup_254_8)._2;
    uint32_t d5i __attribute__((unused)) = (__tup_254_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_255_8 __attribute__((unused)) = g_mix(a2i, b3i, c0i, d1i, m1, m4);
    uint32_t a6i __attribute__((unused)) = (__tup_255_8)._0;
    uint32_t b6i __attribute__((unused)) = (__tup_255_8)._1;
    uint32_t c6i __attribute__((unused)) = (__tup_255_8)._2;
    uint32_t d6i __attribute__((unused)) = (__tup_255_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_256_8 __attribute__((unused)) = g_mix(a3i, b0i, c1i, d2i, m10, m5);
    uint32_t a7i __attribute__((unused)) = (__tup_256_8)._0;
    uint32_t b7i __attribute__((unused)) = (__tup_256_8)._1;
    uint32_t c7i __attribute__((unused)) = (__tup_256_8)._2;
    uint32_t d7i __attribute__((unused)) = (__tup_256_8)._3;
    uint32_t r8_0 __attribute__((unused)) = a4i;
    uint32_t r8_1 __attribute__((unused)) = a5i;
    uint32_t r8_2 __attribute__((unused)) = a6i;
    uint32_t r8_3 __attribute__((unused)) = a7i;
    uint32_t r8_4 __attribute__((unused)) = b7i;
    uint32_t r8_5 __attribute__((unused)) = b4i;
    uint32_t r8_6 __attribute__((unused)) = b5i;
    uint32_t r8_7 __attribute__((unused)) = b6i;
    uint32_t r8_8 __attribute__((unused)) = c6i;
    uint32_t r8_9 __attribute__((unused)) = c7i;
    uint32_t r8_10 __attribute__((unused)) = c4i;
    uint32_t r8_11 __attribute__((unused)) = c5i;
    uint32_t r8_12 __attribute__((unused)) = d5i;
    uint32_t r8_13 __attribute__((unused)) = d6i;
    uint32_t r8_14 __attribute__((unused)) = d7i;
    uint32_t r8_15 __attribute__((unused)) = d4i;
    __forge_tuple_u32_u32_u32_u32_t __tup_263_8 __attribute__((unused)) = g_mix(r8_0, r8_4, r8_8, r8_12, m10, m2);
    uint32_t a0j __attribute__((unused)) = (__tup_263_8)._0;
    uint32_t b0j __attribute__((unused)) = (__tup_263_8)._1;
    uint32_t c0j __attribute__((unused)) = (__tup_263_8)._2;
    uint32_t d0j __attribute__((unused)) = (__tup_263_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_264_8 __attribute__((unused)) = g_mix(r8_1, r8_5, r8_9, r8_13, m8, m4);
    uint32_t a1j __attribute__((unused)) = (__tup_264_8)._0;
    uint32_t b1j __attribute__((unused)) = (__tup_264_8)._1;
    uint32_t c1j __attribute__((unused)) = (__tup_264_8)._2;
    uint32_t d1j __attribute__((unused)) = (__tup_264_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_265_8 __attribute__((unused)) = g_mix(r8_2, r8_6, r8_10, r8_14, m7, m6);
    uint32_t a2j __attribute__((unused)) = (__tup_265_8)._0;
    uint32_t b2j __attribute__((unused)) = (__tup_265_8)._1;
    uint32_t c2j __attribute__((unused)) = (__tup_265_8)._2;
    uint32_t d2j __attribute__((unused)) = (__tup_265_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_266_8 __attribute__((unused)) = g_mix(r8_3, r8_7, r8_11, r8_15, m1, m5);
    uint32_t a3j __attribute__((unused)) = (__tup_266_8)._0;
    uint32_t b3j __attribute__((unused)) = (__tup_266_8)._1;
    uint32_t c3j __attribute__((unused)) = (__tup_266_8)._2;
    uint32_t d3j __attribute__((unused)) = (__tup_266_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_267_8 __attribute__((unused)) = g_mix(a0j, b1j, c2j, d3j, m15, m11);
    uint32_t a4j __attribute__((unused)) = (__tup_267_8)._0;
    uint32_t b4j __attribute__((unused)) = (__tup_267_8)._1;
    uint32_t c4j __attribute__((unused)) = (__tup_267_8)._2;
    uint32_t d4j __attribute__((unused)) = (__tup_267_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_268_8 __attribute__((unused)) = g_mix(a1j, b2j, c3j, d0j, m9, m14);
    uint32_t a5j __attribute__((unused)) = (__tup_268_8)._0;
    uint32_t b5j __attribute__((unused)) = (__tup_268_8)._1;
    uint32_t c5j __attribute__((unused)) = (__tup_268_8)._2;
    uint32_t d5j __attribute__((unused)) = (__tup_268_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_269_8 __attribute__((unused)) = g_mix(a2j, b3j, c0j, d1j, m3, m12);
    uint32_t a6j __attribute__((unused)) = (__tup_269_8)._0;
    uint32_t b6j __attribute__((unused)) = (__tup_269_8)._1;
    uint32_t c6j __attribute__((unused)) = (__tup_269_8)._2;
    uint32_t d6j __attribute__((unused)) = (__tup_269_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_270_8 __attribute__((unused)) = g_mix(a3j, b0j, c1j, d2j, m13, m0);
    uint32_t a7j __attribute__((unused)) = (__tup_270_8)._0;
    uint32_t b7j __attribute__((unused)) = (__tup_270_8)._1;
    uint32_t c7j __attribute__((unused)) = (__tup_270_8)._2;
    uint32_t d7j __attribute__((unused)) = (__tup_270_8)._3;
    uint32_t f0 __attribute__((unused)) = a4j;
    uint32_t f1 __attribute__((unused)) = a5j;
    uint32_t f2 __attribute__((unused)) = a6j;
    uint32_t f3 __attribute__((unused)) = a7j;
    uint32_t f4 __attribute__((unused)) = b7j;
    uint32_t f5 __attribute__((unused)) = b4j;
    uint32_t f6 __attribute__((unused)) = b5j;
    uint32_t f7 __attribute__((unused)) = b6j;
    uint32_t f8 __attribute__((unused)) = c6j;
    uint32_t f9 __attribute__((unused)) = c7j;
    uint32_t f10 __attribute__((unused)) = c4j;
    uint32_t f11 __attribute__((unused)) = c5j;
    uint32_t f12 __attribute__((unused)) = d5j;
    uint32_t f13 __attribute__((unused)) = d6j;
    uint32_t f14 __attribute__((unused)) = d7j;
    uint32_t f15 __attribute__((unused)) = d4j;
    uint32_t out0 __attribute__((unused)) = ((h0 ^ f0) ^ f8);
    uint32_t out1 __attribute__((unused)) = ((h1 ^ f1) ^ f9);
    uint32_t out2 __attribute__((unused)) = ((h2 ^ f2) ^ f10);
    uint32_t out3 __attribute__((unused)) = ((h3 ^ f3) ^ f11);
    uint32_t out4 __attribute__((unused)) = ((h4 ^ f4) ^ f12);
    uint32_t out5 __attribute__((unused)) = ((h5 ^ f5) ^ f13);
    uint32_t out6 __attribute__((unused)) = ((h6 ^ f6) ^ f14);
    uint32_t out7 __attribute__((unused)) = ((h7 ^ f7) ^ f15);
    uint64_t base __attribute__((unused)) = (leaf * 8ULL);
    if (((base + 7ULL) < hashes.len)) {
      hashes.data[base] = reduce_word(out0);
      hashes.data[(base + 1ULL)] = reduce_word(out1);
      hashes.data[(base + 2ULL)] = reduce_word(out2);
      hashes.data[(base + 3ULL)] = reduce_word(out3);
      hashes.data[(base + 4ULL)] = reduce_word(out4);
      hashes.data[(base + 5ULL)] = reduce_word(out5);
      hashes.data[(base + 6ULL)] = reduce_word(out6);
      hashes.data[(base + 7ULL)] = reduce_word(out7);

    }

  }
}

__global__ void merkle_hash_leaves_quad(forge_span_u32_t c0 __attribute__((unused)), forge_span_u32_t c1 __attribute__((unused)), forge_span_u32_t c2 __attribute__((unused)), forge_span_u32_t c3 __attribute__((unused)), forge_span_u32_t hashes __attribute__((unused)), uint64_t n_leaves __attribute__((unused))) {
  uint64_t leaf __attribute__((unused)) = ((blockIdx_x * blockDim_x) + threadIdx_x);
  if ((leaf < n_leaves)) {
    uint32_t m0 __attribute__((unused)) = c0.data[leaf];
    uint32_t m1 __attribute__((unused)) = c1.data[leaf];
    uint32_t m2 __attribute__((unused)) = c2.data[leaf];
    uint32_t m3 __attribute__((unused)) = c3.data[leaf];
    uint32_t m4 __attribute__((unused)) = 0ULL;
    uint32_t m5 __attribute__((unused)) = 0ULL;
    uint32_t m6 __attribute__((unused)) = 0ULL;
    uint32_t m7 __attribute__((unused)) = 0ULL;
    uint32_t m8 __attribute__((unused)) = 0ULL;
    uint32_t m9 __attribute__((unused)) = 0ULL;
    uint32_t m10 __attribute__((unused)) = 0ULL;
    uint32_t m11 __attribute__((unused)) = 0ULL;
    uint32_t m12 __attribute__((unused)) = 0ULL;
    uint32_t m13 __attribute__((unused)) = 0ULL;
    uint32_t m14 __attribute__((unused)) = 0ULL;
    uint32_t m15 __attribute__((unused)) = 0ULL;
    uint32_t h0 __attribute__((unused)) = (iv0() ^ 16842784ULL);
    uint32_t h1 __attribute__((unused)) = iv1();
    uint32_t h2 __attribute__((unused)) = iv2();
    uint32_t h3 __attribute__((unused)) = iv3();
    uint32_t h4 __attribute__((unused)) = iv4();
    uint32_t h5 __attribute__((unused)) = iv5();
    uint32_t h6 __attribute__((unused)) = iv6();
    uint32_t h7 __attribute__((unused)) = iv7();
    uint32_t v0 __attribute__((unused)) = h0;
    uint32_t v1 __attribute__((unused)) = h1;
    uint32_t v2 __attribute__((unused)) = h2;
    uint32_t v3 __attribute__((unused)) = h3;
    uint32_t v4 __attribute__((unused)) = h4;
    uint32_t v5 __attribute__((unused)) = h5;
    uint32_t v6 __attribute__((unused)) = h6;
    uint32_t v7 __attribute__((unused)) = h7;
    uint32_t v8 __attribute__((unused)) = iv0();
    uint32_t v9 __attribute__((unused)) = iv1();
    uint32_t v10 __attribute__((unused)) = iv2();
    uint32_t v11 __attribute__((unused)) = iv3();
    uint32_t v12 __attribute__((unused)) = (iv4() ^ 16ULL);
    uint32_t v13 __attribute__((unused)) = iv5();
    uint32_t v14 __attribute__((unused)) = (iv6() ^ 4294967295ULL);
    uint32_t v15 __attribute__((unused)) = iv7();
    __forge_tuple_u32_u32_u32_u32_t __tup_350_8 __attribute__((unused)) = g_mix(v0, v4, v8, v12, m0, m1);
    uint32_t a0 __attribute__((unused)) = (__tup_350_8)._0;
    uint32_t b0 __attribute__((unused)) = (__tup_350_8)._1;
    uint32_t c0 __attribute__((unused)) = (__tup_350_8)._2;
    uint32_t d0 __attribute__((unused)) = (__tup_350_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_351_8 __attribute__((unused)) = g_mix(v1, v5, v9, v13, m2, m3);
    uint32_t a1 __attribute__((unused)) = (__tup_351_8)._0;
    uint32_t b1 __attribute__((unused)) = (__tup_351_8)._1;
    uint32_t c1 __attribute__((unused)) = (__tup_351_8)._2;
    uint32_t d1 __attribute__((unused)) = (__tup_351_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_352_8 __attribute__((unused)) = g_mix(v2, v6, v10, v14, m4, m5);
    uint32_t a2 __attribute__((unused)) = (__tup_352_8)._0;
    uint32_t b2 __attribute__((unused)) = (__tup_352_8)._1;
    uint32_t c2 __attribute__((unused)) = (__tup_352_8)._2;
    uint32_t d2 __attribute__((unused)) = (__tup_352_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_353_8 __attribute__((unused)) = g_mix(v3, v7, v11, v15, m6, m7);
    uint32_t a3 __attribute__((unused)) = (__tup_353_8)._0;
    uint32_t b3 __attribute__((unused)) = (__tup_353_8)._1;
    uint32_t c3 __attribute__((unused)) = (__tup_353_8)._2;
    uint32_t d3 __attribute__((unused)) = (__tup_353_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_354_8 __attribute__((unused)) = g_mix(a0, b1, c2, d3, m8, m9);
    uint32_t a4 __attribute__((unused)) = (__tup_354_8)._0;
    uint32_t b4 __attribute__((unused)) = (__tup_354_8)._1;
    uint32_t c4 __attribute__((unused)) = (__tup_354_8)._2;
    uint32_t d4 __attribute__((unused)) = (__tup_354_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_355_8 __attribute__((unused)) = g_mix(a1, b2, c3, d0, m10, m11);
    uint32_t a5 __attribute__((unused)) = (__tup_355_8)._0;
    uint32_t b5 __attribute__((unused)) = (__tup_355_8)._1;
    uint32_t c5 __attribute__((unused)) = (__tup_355_8)._2;
    uint32_t d5 __attribute__((unused)) = (__tup_355_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_356_8 __attribute__((unused)) = g_mix(a2, b3, c0, d1, m12, m13);
    uint32_t a6 __attribute__((unused)) = (__tup_356_8)._0;
    uint32_t b6 __attribute__((unused)) = (__tup_356_8)._1;
    uint32_t c6 __attribute__((unused)) = (__tup_356_8)._2;
    uint32_t d6 __attribute__((unused)) = (__tup_356_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_357_8 __attribute__((unused)) = g_mix(a3, b0, c1, d2, m14, m15);
    uint32_t a7 __attribute__((unused)) = (__tup_357_8)._0;
    uint32_t b7 __attribute__((unused)) = (__tup_357_8)._1;
    uint32_t c7 __attribute__((unused)) = (__tup_357_8)._2;
    uint32_t d7 __attribute__((unused)) = (__tup_357_8)._3;
    uint32_t r0_0 __attribute__((unused)) = a4;
    uint32_t r0_1 __attribute__((unused)) = a5;
    uint32_t r0_2 __attribute__((unused)) = a6;
    uint32_t r0_3 __attribute__((unused)) = a7;
    uint32_t r0_4 __attribute__((unused)) = b7;
    uint32_t r0_5 __attribute__((unused)) = b4;
    uint32_t r0_6 __attribute__((unused)) = b5;
    uint32_t r0_7 __attribute__((unused)) = b6;
    uint32_t r0_8 __attribute__((unused)) = c6;
    uint32_t r0_9 __attribute__((unused)) = c7;
    uint32_t r0_10 __attribute__((unused)) = c4;
    uint32_t r0_11 __attribute__((unused)) = c5;
    uint32_t r0_12 __attribute__((unused)) = d5;
    uint32_t r0_13 __attribute__((unused)) = d6;
    uint32_t r0_14 __attribute__((unused)) = d7;
    uint32_t r0_15 __attribute__((unused)) = d4;
    __forge_tuple_u32_u32_u32_u32_t __tup_366_8 __attribute__((unused)) = g_mix(r0_0, r0_4, r0_8, r0_12, m14, m10);
    uint32_t a0b __attribute__((unused)) = (__tup_366_8)._0;
    uint32_t b0b __attribute__((unused)) = (__tup_366_8)._1;
    uint32_t c0b __attribute__((unused)) = (__tup_366_8)._2;
    uint32_t d0b __attribute__((unused)) = (__tup_366_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_367_8 __attribute__((unused)) = g_mix(r0_1, r0_5, r0_9, r0_13, m4, m8);
    uint32_t a1b __attribute__((unused)) = (__tup_367_8)._0;
    uint32_t b1b __attribute__((unused)) = (__tup_367_8)._1;
    uint32_t c1b __attribute__((unused)) = (__tup_367_8)._2;
    uint32_t d1b __attribute__((unused)) = (__tup_367_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_368_8 __attribute__((unused)) = g_mix(r0_2, r0_6, r0_10, r0_14, m9, m15);
    uint32_t a2b __attribute__((unused)) = (__tup_368_8)._0;
    uint32_t b2b __attribute__((unused)) = (__tup_368_8)._1;
    uint32_t c2b __attribute__((unused)) = (__tup_368_8)._2;
    uint32_t d2b __attribute__((unused)) = (__tup_368_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_369_8 __attribute__((unused)) = g_mix(r0_3, r0_7, r0_11, r0_15, m13, m6);
    uint32_t a3b __attribute__((unused)) = (__tup_369_8)._0;
    uint32_t b3b __attribute__((unused)) = (__tup_369_8)._1;
    uint32_t c3b __attribute__((unused)) = (__tup_369_8)._2;
    uint32_t d3b __attribute__((unused)) = (__tup_369_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_370_8 __attribute__((unused)) = g_mix(a0b, b1b, c2b, d3b, m1, m12);
    uint32_t a4b __attribute__((unused)) = (__tup_370_8)._0;
    uint32_t b4b __attribute__((unused)) = (__tup_370_8)._1;
    uint32_t c4b __attribute__((unused)) = (__tup_370_8)._2;
    uint32_t d4b __attribute__((unused)) = (__tup_370_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_371_8 __attribute__((unused)) = g_mix(a1b, b2b, c3b, d0b, m0, m2);
    uint32_t a5b __attribute__((unused)) = (__tup_371_8)._0;
    uint32_t b5b __attribute__((unused)) = (__tup_371_8)._1;
    uint32_t c5b __attribute__((unused)) = (__tup_371_8)._2;
    uint32_t d5b __attribute__((unused)) = (__tup_371_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_372_8 __attribute__((unused)) = g_mix(a2b, b3b, c0b, d1b, m11, m7);
    uint32_t a6b __attribute__((unused)) = (__tup_372_8)._0;
    uint32_t b6b __attribute__((unused)) = (__tup_372_8)._1;
    uint32_t c6b __attribute__((unused)) = (__tup_372_8)._2;
    uint32_t d6b __attribute__((unused)) = (__tup_372_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_373_8 __attribute__((unused)) = g_mix(a3b, b0b, c1b, d2b, m5, m3);
    uint32_t a7b __attribute__((unused)) = (__tup_373_8)._0;
    uint32_t b7b __attribute__((unused)) = (__tup_373_8)._1;
    uint32_t c7b __attribute__((unused)) = (__tup_373_8)._2;
    uint32_t d7b __attribute__((unused)) = (__tup_373_8)._3;
    uint32_t r1_0 __attribute__((unused)) = a4b;
    uint32_t r1_1 __attribute__((unused)) = a5b;
    uint32_t r1_2 __attribute__((unused)) = a6b;
    uint32_t r1_3 __attribute__((unused)) = a7b;
    uint32_t r1_4 __attribute__((unused)) = b7b;
    uint32_t r1_5 __attribute__((unused)) = b4b;
    uint32_t r1_6 __attribute__((unused)) = b5b;
    uint32_t r1_7 __attribute__((unused)) = b6b;
    uint32_t r1_8 __attribute__((unused)) = c6b;
    uint32_t r1_9 __attribute__((unused)) = c7b;
    uint32_t r1_10 __attribute__((unused)) = c4b;
    uint32_t r1_11 __attribute__((unused)) = c5b;
    uint32_t r1_12 __attribute__((unused)) = d5b;
    uint32_t r1_13 __attribute__((unused)) = d6b;
    uint32_t r1_14 __attribute__((unused)) = d7b;
    uint32_t r1_15 __attribute__((unused)) = d4b;
    __forge_tuple_u32_u32_u32_u32_t __tup_380_8 __attribute__((unused)) = g_mix(r1_0, r1_4, r1_8, r1_12, m11, m8);
    uint32_t a0c __attribute__((unused)) = (__tup_380_8)._0;
    uint32_t b0c __attribute__((unused)) = (__tup_380_8)._1;
    uint32_t c0c __attribute__((unused)) = (__tup_380_8)._2;
    uint32_t d0c __attribute__((unused)) = (__tup_380_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_381_8 __attribute__((unused)) = g_mix(r1_1, r1_5, r1_9, r1_13, m12, m0);
    uint32_t a1c __attribute__((unused)) = (__tup_381_8)._0;
    uint32_t b1c __attribute__((unused)) = (__tup_381_8)._1;
    uint32_t c1c __attribute__((unused)) = (__tup_381_8)._2;
    uint32_t d1c __attribute__((unused)) = (__tup_381_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_382_8 __attribute__((unused)) = g_mix(r1_2, r1_6, r1_10, r1_14, m5, m2);
    uint32_t a2c __attribute__((unused)) = (__tup_382_8)._0;
    uint32_t b2c __attribute__((unused)) = (__tup_382_8)._1;
    uint32_t c2c __attribute__((unused)) = (__tup_382_8)._2;
    uint32_t d2c __attribute__((unused)) = (__tup_382_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_383_8 __attribute__((unused)) = g_mix(r1_3, r1_7, r1_11, r1_15, m15, m13);
    uint32_t a3c __attribute__((unused)) = (__tup_383_8)._0;
    uint32_t b3c __attribute__((unused)) = (__tup_383_8)._1;
    uint32_t c3c __attribute__((unused)) = (__tup_383_8)._2;
    uint32_t d3c __attribute__((unused)) = (__tup_383_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_384_8 __attribute__((unused)) = g_mix(a0c, b1c, c2c, d3c, m10, m14);
    uint32_t a4c __attribute__((unused)) = (__tup_384_8)._0;
    uint32_t b4c __attribute__((unused)) = (__tup_384_8)._1;
    uint32_t c4c __attribute__((unused)) = (__tup_384_8)._2;
    uint32_t d4c __attribute__((unused)) = (__tup_384_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_385_8 __attribute__((unused)) = g_mix(a1c, b2c, c3c, d0c, m3, m6);
    uint32_t a5c __attribute__((unused)) = (__tup_385_8)._0;
    uint32_t b5c __attribute__((unused)) = (__tup_385_8)._1;
    uint32_t c5c __attribute__((unused)) = (__tup_385_8)._2;
    uint32_t d5c __attribute__((unused)) = (__tup_385_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_386_8 __attribute__((unused)) = g_mix(a2c, b3c, c0c, d1c, m7, m1);
    uint32_t a6c __attribute__((unused)) = (__tup_386_8)._0;
    uint32_t b6c __attribute__((unused)) = (__tup_386_8)._1;
    uint32_t c6c __attribute__((unused)) = (__tup_386_8)._2;
    uint32_t d6c __attribute__((unused)) = (__tup_386_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_387_8 __attribute__((unused)) = g_mix(a3c, b0c, c1c, d2c, m9, m4);
    uint32_t a7c __attribute__((unused)) = (__tup_387_8)._0;
    uint32_t b7c __attribute__((unused)) = (__tup_387_8)._1;
    uint32_t c7c __attribute__((unused)) = (__tup_387_8)._2;
    uint32_t d7c __attribute__((unused)) = (__tup_387_8)._3;
    uint32_t r2_0 __attribute__((unused)) = a4c;
    uint32_t r2_1 __attribute__((unused)) = a5c;
    uint32_t r2_2 __attribute__((unused)) = a6c;
    uint32_t r2_3 __attribute__((unused)) = a7c;
    uint32_t r2_4 __attribute__((unused)) = b7c;
    uint32_t r2_5 __attribute__((unused)) = b4c;
    uint32_t r2_6 __attribute__((unused)) = b5c;
    uint32_t r2_7 __attribute__((unused)) = b6c;
    uint32_t r2_8 __attribute__((unused)) = c6c;
    uint32_t r2_9 __attribute__((unused)) = c7c;
    uint32_t r2_10 __attribute__((unused)) = c4c;
    uint32_t r2_11 __attribute__((unused)) = c5c;
    uint32_t r2_12 __attribute__((unused)) = d5c;
    uint32_t r2_13 __attribute__((unused)) = d6c;
    uint32_t r2_14 __attribute__((unused)) = d7c;
    uint32_t r2_15 __attribute__((unused)) = d4c;
    __forge_tuple_u32_u32_u32_u32_t __tup_394_8 __attribute__((unused)) = g_mix(r2_0, r2_4, r2_8, r2_12, m7, m9);
    uint32_t a0d __attribute__((unused)) = (__tup_394_8)._0;
    uint32_t b0d __attribute__((unused)) = (__tup_394_8)._1;
    uint32_t c0d __attribute__((unused)) = (__tup_394_8)._2;
    uint32_t d0d __attribute__((unused)) = (__tup_394_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_395_8 __attribute__((unused)) = g_mix(r2_1, r2_5, r2_9, r2_13, m3, m1);
    uint32_t a1d __attribute__((unused)) = (__tup_395_8)._0;
    uint32_t b1d __attribute__((unused)) = (__tup_395_8)._1;
    uint32_t c1d __attribute__((unused)) = (__tup_395_8)._2;
    uint32_t d1d __attribute__((unused)) = (__tup_395_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_396_8 __attribute__((unused)) = g_mix(r2_2, r2_6, r2_10, r2_14, m13, m12);
    uint32_t a2d __attribute__((unused)) = (__tup_396_8)._0;
    uint32_t b2d __attribute__((unused)) = (__tup_396_8)._1;
    uint32_t c2d __attribute__((unused)) = (__tup_396_8)._2;
    uint32_t d2d __attribute__((unused)) = (__tup_396_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_397_8 __attribute__((unused)) = g_mix(r2_3, r2_7, r2_11, r2_15, m11, m14);
    uint32_t a3d __attribute__((unused)) = (__tup_397_8)._0;
    uint32_t b3d __attribute__((unused)) = (__tup_397_8)._1;
    uint32_t c3d __attribute__((unused)) = (__tup_397_8)._2;
    uint32_t d3d __attribute__((unused)) = (__tup_397_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_398_8 __attribute__((unused)) = g_mix(a0d, b1d, c2d, d3d, m2, m6);
    uint32_t a4d __attribute__((unused)) = (__tup_398_8)._0;
    uint32_t b4d __attribute__((unused)) = (__tup_398_8)._1;
    uint32_t c4d __attribute__((unused)) = (__tup_398_8)._2;
    uint32_t d4d __attribute__((unused)) = (__tup_398_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_399_8 __attribute__((unused)) = g_mix(a1d, b2d, c3d, d0d, m5, m10);
    uint32_t a5d __attribute__((unused)) = (__tup_399_8)._0;
    uint32_t b5d __attribute__((unused)) = (__tup_399_8)._1;
    uint32_t c5d __attribute__((unused)) = (__tup_399_8)._2;
    uint32_t d5d __attribute__((unused)) = (__tup_399_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_400_8 __attribute__((unused)) = g_mix(a2d, b3d, c0d, d1d, m4, m0);
    uint32_t a6d __attribute__((unused)) = (__tup_400_8)._0;
    uint32_t b6d __attribute__((unused)) = (__tup_400_8)._1;
    uint32_t c6d __attribute__((unused)) = (__tup_400_8)._2;
    uint32_t d6d __attribute__((unused)) = (__tup_400_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_401_8 __attribute__((unused)) = g_mix(a3d, b0d, c1d, d2d, m15, m8);
    uint32_t a7d __attribute__((unused)) = (__tup_401_8)._0;
    uint32_t b7d __attribute__((unused)) = (__tup_401_8)._1;
    uint32_t c7d __attribute__((unused)) = (__tup_401_8)._2;
    uint32_t d7d __attribute__((unused)) = (__tup_401_8)._3;
    uint32_t r3_0 __attribute__((unused)) = a4d;
    uint32_t r3_1 __attribute__((unused)) = a5d;
    uint32_t r3_2 __attribute__((unused)) = a6d;
    uint32_t r3_3 __attribute__((unused)) = a7d;
    uint32_t r3_4 __attribute__((unused)) = b7d;
    uint32_t r3_5 __attribute__((unused)) = b4d;
    uint32_t r3_6 __attribute__((unused)) = b5d;
    uint32_t r3_7 __attribute__((unused)) = b6d;
    uint32_t r3_8 __attribute__((unused)) = c6d;
    uint32_t r3_9 __attribute__((unused)) = c7d;
    uint32_t r3_10 __attribute__((unused)) = c4d;
    uint32_t r3_11 __attribute__((unused)) = c5d;
    uint32_t r3_12 __attribute__((unused)) = d5d;
    uint32_t r3_13 __attribute__((unused)) = d6d;
    uint32_t r3_14 __attribute__((unused)) = d7d;
    uint32_t r3_15 __attribute__((unused)) = d4d;
    __forge_tuple_u32_u32_u32_u32_t __tup_408_8 __attribute__((unused)) = g_mix(r3_0, r3_4, r3_8, r3_12, m9, m0);
    uint32_t a0e __attribute__((unused)) = (__tup_408_8)._0;
    uint32_t b0e __attribute__((unused)) = (__tup_408_8)._1;
    uint32_t c0e __attribute__((unused)) = (__tup_408_8)._2;
    uint32_t d0e __attribute__((unused)) = (__tup_408_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_409_8 __attribute__((unused)) = g_mix(r3_1, r3_5, r3_9, r3_13, m5, m7);
    uint32_t a1e __attribute__((unused)) = (__tup_409_8)._0;
    uint32_t b1e __attribute__((unused)) = (__tup_409_8)._1;
    uint32_t c1e __attribute__((unused)) = (__tup_409_8)._2;
    uint32_t d1e __attribute__((unused)) = (__tup_409_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_410_8 __attribute__((unused)) = g_mix(r3_2, r3_6, r3_10, r3_14, m2, m4);
    uint32_t a2e __attribute__((unused)) = (__tup_410_8)._0;
    uint32_t b2e __attribute__((unused)) = (__tup_410_8)._1;
    uint32_t c2e __attribute__((unused)) = (__tup_410_8)._2;
    uint32_t d2e __attribute__((unused)) = (__tup_410_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_411_8 __attribute__((unused)) = g_mix(r3_3, r3_7, r3_11, r3_15, m10, m15);
    uint32_t a3e __attribute__((unused)) = (__tup_411_8)._0;
    uint32_t b3e __attribute__((unused)) = (__tup_411_8)._1;
    uint32_t c3e __attribute__((unused)) = (__tup_411_8)._2;
    uint32_t d3e __attribute__((unused)) = (__tup_411_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_412_8 __attribute__((unused)) = g_mix(a0e, b1e, c2e, d3e, m14, m1);
    uint32_t a4e __attribute__((unused)) = (__tup_412_8)._0;
    uint32_t b4e __attribute__((unused)) = (__tup_412_8)._1;
    uint32_t c4e __attribute__((unused)) = (__tup_412_8)._2;
    uint32_t d4e __attribute__((unused)) = (__tup_412_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_413_8 __attribute__((unused)) = g_mix(a1e, b2e, c3e, d0e, m11, m12);
    uint32_t a5e __attribute__((unused)) = (__tup_413_8)._0;
    uint32_t b5e __attribute__((unused)) = (__tup_413_8)._1;
    uint32_t c5e __attribute__((unused)) = (__tup_413_8)._2;
    uint32_t d5e __attribute__((unused)) = (__tup_413_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_414_8 __attribute__((unused)) = g_mix(a2e, b3e, c0e, d1e, m6, m8);
    uint32_t a6e __attribute__((unused)) = (__tup_414_8)._0;
    uint32_t b6e __attribute__((unused)) = (__tup_414_8)._1;
    uint32_t c6e __attribute__((unused)) = (__tup_414_8)._2;
    uint32_t d6e __attribute__((unused)) = (__tup_414_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_415_8 __attribute__((unused)) = g_mix(a3e, b0e, c1e, d2e, m3, m13);
    uint32_t a7e __attribute__((unused)) = (__tup_415_8)._0;
    uint32_t b7e __attribute__((unused)) = (__tup_415_8)._1;
    uint32_t c7e __attribute__((unused)) = (__tup_415_8)._2;
    uint32_t d7e __attribute__((unused)) = (__tup_415_8)._3;
    uint32_t r4_0 __attribute__((unused)) = a4e;
    uint32_t r4_1 __attribute__((unused)) = a5e;
    uint32_t r4_2 __attribute__((unused)) = a6e;
    uint32_t r4_3 __attribute__((unused)) = a7e;
    uint32_t r4_4 __attribute__((unused)) = b7e;
    uint32_t r4_5 __attribute__((unused)) = b4e;
    uint32_t r4_6 __attribute__((unused)) = b5e;
    uint32_t r4_7 __attribute__((unused)) = b6e;
    uint32_t r4_8 __attribute__((unused)) = c6e;
    uint32_t r4_9 __attribute__((unused)) = c7e;
    uint32_t r4_10 __attribute__((unused)) = c4e;
    uint32_t r4_11 __attribute__((unused)) = c5e;
    uint32_t r4_12 __attribute__((unused)) = d5e;
    uint32_t r4_13 __attribute__((unused)) = d6e;
    uint32_t r4_14 __attribute__((unused)) = d7e;
    uint32_t r4_15 __attribute__((unused)) = d4e;
    __forge_tuple_u32_u32_u32_u32_t __tup_422_8 __attribute__((unused)) = g_mix(r4_0, r4_4, r4_8, r4_12, m2, m12);
    uint32_t a0f __attribute__((unused)) = (__tup_422_8)._0;
    uint32_t b0f __attribute__((unused)) = (__tup_422_8)._1;
    uint32_t c0f __attribute__((unused)) = (__tup_422_8)._2;
    uint32_t d0f __attribute__((unused)) = (__tup_422_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_423_8 __attribute__((unused)) = g_mix(r4_1, r4_5, r4_9, r4_13, m6, m10);
    uint32_t a1f __attribute__((unused)) = (__tup_423_8)._0;
    uint32_t b1f __attribute__((unused)) = (__tup_423_8)._1;
    uint32_t c1f __attribute__((unused)) = (__tup_423_8)._2;
    uint32_t d1f __attribute__((unused)) = (__tup_423_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_424_8 __attribute__((unused)) = g_mix(r4_2, r4_6, r4_10, r4_14, m0, m11);
    uint32_t a2f __attribute__((unused)) = (__tup_424_8)._0;
    uint32_t b2f __attribute__((unused)) = (__tup_424_8)._1;
    uint32_t c2f __attribute__((unused)) = (__tup_424_8)._2;
    uint32_t d2f __attribute__((unused)) = (__tup_424_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_425_8 __attribute__((unused)) = g_mix(r4_3, r4_7, r4_11, r4_15, m8, m3);
    uint32_t a3f __attribute__((unused)) = (__tup_425_8)._0;
    uint32_t b3f __attribute__((unused)) = (__tup_425_8)._1;
    uint32_t c3f __attribute__((unused)) = (__tup_425_8)._2;
    uint32_t d3f __attribute__((unused)) = (__tup_425_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_426_8 __attribute__((unused)) = g_mix(a0f, b1f, c2f, d3f, m4, m13);
    uint32_t a4f __attribute__((unused)) = (__tup_426_8)._0;
    uint32_t b4f __attribute__((unused)) = (__tup_426_8)._1;
    uint32_t c4f __attribute__((unused)) = (__tup_426_8)._2;
    uint32_t d4f __attribute__((unused)) = (__tup_426_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_427_8 __attribute__((unused)) = g_mix(a1f, b2f, c3f, d0f, m7, m5);
    uint32_t a5f __attribute__((unused)) = (__tup_427_8)._0;
    uint32_t b5f __attribute__((unused)) = (__tup_427_8)._1;
    uint32_t c5f __attribute__((unused)) = (__tup_427_8)._2;
    uint32_t d5f __attribute__((unused)) = (__tup_427_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_428_8 __attribute__((unused)) = g_mix(a2f, b3f, c0f, d1f, m15, m14);
    uint32_t a6f __attribute__((unused)) = (__tup_428_8)._0;
    uint32_t b6f __attribute__((unused)) = (__tup_428_8)._1;
    uint32_t c6f __attribute__((unused)) = (__tup_428_8)._2;
    uint32_t d6f __attribute__((unused)) = (__tup_428_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_429_8 __attribute__((unused)) = g_mix(a3f, b0f, c1f, d2f, m1, m9);
    uint32_t a7f __attribute__((unused)) = (__tup_429_8)._0;
    uint32_t b7f __attribute__((unused)) = (__tup_429_8)._1;
    uint32_t c7f __attribute__((unused)) = (__tup_429_8)._2;
    uint32_t d7f __attribute__((unused)) = (__tup_429_8)._3;
    uint32_t r5_0 __attribute__((unused)) = a4f;
    uint32_t r5_1 __attribute__((unused)) = a5f;
    uint32_t r5_2 __attribute__((unused)) = a6f;
    uint32_t r5_3 __attribute__((unused)) = a7f;
    uint32_t r5_4 __attribute__((unused)) = b7f;
    uint32_t r5_5 __attribute__((unused)) = b4f;
    uint32_t r5_6 __attribute__((unused)) = b5f;
    uint32_t r5_7 __attribute__((unused)) = b6f;
    uint32_t r5_8 __attribute__((unused)) = c6f;
    uint32_t r5_9 __attribute__((unused)) = c7f;
    uint32_t r5_10 __attribute__((unused)) = c4f;
    uint32_t r5_11 __attribute__((unused)) = c5f;
    uint32_t r5_12 __attribute__((unused)) = d5f;
    uint32_t r5_13 __attribute__((unused)) = d6f;
    uint32_t r5_14 __attribute__((unused)) = d7f;
    uint32_t r5_15 __attribute__((unused)) = d4f;
    __forge_tuple_u32_u32_u32_u32_t __tup_436_8 __attribute__((unused)) = g_mix(r5_0, r5_4, r5_8, r5_12, m12, m5);
    uint32_t a0g __attribute__((unused)) = (__tup_436_8)._0;
    uint32_t b0g __attribute__((unused)) = (__tup_436_8)._1;
    uint32_t c0g __attribute__((unused)) = (__tup_436_8)._2;
    uint32_t d0g __attribute__((unused)) = (__tup_436_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_437_8 __attribute__((unused)) = g_mix(r5_1, r5_5, r5_9, r5_13, m1, m15);
    uint32_t a1g __attribute__((unused)) = (__tup_437_8)._0;
    uint32_t b1g __attribute__((unused)) = (__tup_437_8)._1;
    uint32_t c1g __attribute__((unused)) = (__tup_437_8)._2;
    uint32_t d1g __attribute__((unused)) = (__tup_437_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_438_8 __attribute__((unused)) = g_mix(r5_2, r5_6, r5_10, r5_14, m14, m13);
    uint32_t a2g __attribute__((unused)) = (__tup_438_8)._0;
    uint32_t b2g __attribute__((unused)) = (__tup_438_8)._1;
    uint32_t c2g __attribute__((unused)) = (__tup_438_8)._2;
    uint32_t d2g __attribute__((unused)) = (__tup_438_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_439_8 __attribute__((unused)) = g_mix(r5_3, r5_7, r5_11, r5_15, m4, m10);
    uint32_t a3g __attribute__((unused)) = (__tup_439_8)._0;
    uint32_t b3g __attribute__((unused)) = (__tup_439_8)._1;
    uint32_t c3g __attribute__((unused)) = (__tup_439_8)._2;
    uint32_t d3g __attribute__((unused)) = (__tup_439_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_440_8 __attribute__((unused)) = g_mix(a0g, b1g, c2g, d3g, m0, m7);
    uint32_t a4g __attribute__((unused)) = (__tup_440_8)._0;
    uint32_t b4g __attribute__((unused)) = (__tup_440_8)._1;
    uint32_t c4g __attribute__((unused)) = (__tup_440_8)._2;
    uint32_t d4g __attribute__((unused)) = (__tup_440_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_441_8 __attribute__((unused)) = g_mix(a1g, b2g, c3g, d0g, m6, m3);
    uint32_t a5g __attribute__((unused)) = (__tup_441_8)._0;
    uint32_t b5g __attribute__((unused)) = (__tup_441_8)._1;
    uint32_t c5g __attribute__((unused)) = (__tup_441_8)._2;
    uint32_t d5g __attribute__((unused)) = (__tup_441_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_442_8 __attribute__((unused)) = g_mix(a2g, b3g, c0g, d1g, m9, m2);
    uint32_t a6g __attribute__((unused)) = (__tup_442_8)._0;
    uint32_t b6g __attribute__((unused)) = (__tup_442_8)._1;
    uint32_t c6g __attribute__((unused)) = (__tup_442_8)._2;
    uint32_t d6g __attribute__((unused)) = (__tup_442_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_443_8 __attribute__((unused)) = g_mix(a3g, b0g, c1g, d2g, m8, m11);
    uint32_t a7g __attribute__((unused)) = (__tup_443_8)._0;
    uint32_t b7g __attribute__((unused)) = (__tup_443_8)._1;
    uint32_t c7g __attribute__((unused)) = (__tup_443_8)._2;
    uint32_t d7g __attribute__((unused)) = (__tup_443_8)._3;
    uint32_t r6_0 __attribute__((unused)) = a4g;
    uint32_t r6_1 __attribute__((unused)) = a5g;
    uint32_t r6_2 __attribute__((unused)) = a6g;
    uint32_t r6_3 __attribute__((unused)) = a7g;
    uint32_t r6_4 __attribute__((unused)) = b7g;
    uint32_t r6_5 __attribute__((unused)) = b4g;
    uint32_t r6_6 __attribute__((unused)) = b5g;
    uint32_t r6_7 __attribute__((unused)) = b6g;
    uint32_t r6_8 __attribute__((unused)) = c6g;
    uint32_t r6_9 __attribute__((unused)) = c7g;
    uint32_t r6_10 __attribute__((unused)) = c4g;
    uint32_t r6_11 __attribute__((unused)) = c5g;
    uint32_t r6_12 __attribute__((unused)) = d5g;
    uint32_t r6_13 __attribute__((unused)) = d6g;
    uint32_t r6_14 __attribute__((unused)) = d7g;
    uint32_t r6_15 __attribute__((unused)) = d4g;
    __forge_tuple_u32_u32_u32_u32_t __tup_450_8 __attribute__((unused)) = g_mix(r6_0, r6_4, r6_8, r6_12, m13, m11);
    uint32_t a0h __attribute__((unused)) = (__tup_450_8)._0;
    uint32_t b0h __attribute__((unused)) = (__tup_450_8)._1;
    uint32_t c0h __attribute__((unused)) = (__tup_450_8)._2;
    uint32_t d0h __attribute__((unused)) = (__tup_450_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_451_8 __attribute__((unused)) = g_mix(r6_1, r6_5, r6_9, r6_13, m7, m14);
    uint32_t a1h __attribute__((unused)) = (__tup_451_8)._0;
    uint32_t b1h __attribute__((unused)) = (__tup_451_8)._1;
    uint32_t c1h __attribute__((unused)) = (__tup_451_8)._2;
    uint32_t d1h __attribute__((unused)) = (__tup_451_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_452_8 __attribute__((unused)) = g_mix(r6_2, r6_6, r6_10, r6_14, m12, m1);
    uint32_t a2h __attribute__((unused)) = (__tup_452_8)._0;
    uint32_t b2h __attribute__((unused)) = (__tup_452_8)._1;
    uint32_t c2h __attribute__((unused)) = (__tup_452_8)._2;
    uint32_t d2h __attribute__((unused)) = (__tup_452_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_453_8 __attribute__((unused)) = g_mix(r6_3, r6_7, r6_11, r6_15, m3, m9);
    uint32_t a3h __attribute__((unused)) = (__tup_453_8)._0;
    uint32_t b3h __attribute__((unused)) = (__tup_453_8)._1;
    uint32_t c3h __attribute__((unused)) = (__tup_453_8)._2;
    uint32_t d3h __attribute__((unused)) = (__tup_453_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_454_8 __attribute__((unused)) = g_mix(a0h, b1h, c2h, d3h, m5, m0);
    uint32_t a4h __attribute__((unused)) = (__tup_454_8)._0;
    uint32_t b4h __attribute__((unused)) = (__tup_454_8)._1;
    uint32_t c4h __attribute__((unused)) = (__tup_454_8)._2;
    uint32_t d4h __attribute__((unused)) = (__tup_454_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_455_8 __attribute__((unused)) = g_mix(a1h, b2h, c3h, d0h, m15, m4);
    uint32_t a5h __attribute__((unused)) = (__tup_455_8)._0;
    uint32_t b5h __attribute__((unused)) = (__tup_455_8)._1;
    uint32_t c5h __attribute__((unused)) = (__tup_455_8)._2;
    uint32_t d5h __attribute__((unused)) = (__tup_455_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_456_8 __attribute__((unused)) = g_mix(a2h, b3h, c0h, d1h, m8, m6);
    uint32_t a6h __attribute__((unused)) = (__tup_456_8)._0;
    uint32_t b6h __attribute__((unused)) = (__tup_456_8)._1;
    uint32_t c6h __attribute__((unused)) = (__tup_456_8)._2;
    uint32_t d6h __attribute__((unused)) = (__tup_456_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_457_8 __attribute__((unused)) = g_mix(a3h, b0h, c1h, d2h, m2, m10);
    uint32_t a7h __attribute__((unused)) = (__tup_457_8)._0;
    uint32_t b7h __attribute__((unused)) = (__tup_457_8)._1;
    uint32_t c7h __attribute__((unused)) = (__tup_457_8)._2;
    uint32_t d7h __attribute__((unused)) = (__tup_457_8)._3;
    uint32_t r7_0 __attribute__((unused)) = a4h;
    uint32_t r7_1 __attribute__((unused)) = a5h;
    uint32_t r7_2 __attribute__((unused)) = a6h;
    uint32_t r7_3 __attribute__((unused)) = a7h;
    uint32_t r7_4 __attribute__((unused)) = b7h;
    uint32_t r7_5 __attribute__((unused)) = b4h;
    uint32_t r7_6 __attribute__((unused)) = b5h;
    uint32_t r7_7 __attribute__((unused)) = b6h;
    uint32_t r7_8 __attribute__((unused)) = c6h;
    uint32_t r7_9 __attribute__((unused)) = c7h;
    uint32_t r7_10 __attribute__((unused)) = c4h;
    uint32_t r7_11 __attribute__((unused)) = c5h;
    uint32_t r7_12 __attribute__((unused)) = d5h;
    uint32_t r7_13 __attribute__((unused)) = d6h;
    uint32_t r7_14 __attribute__((unused)) = d7h;
    uint32_t r7_15 __attribute__((unused)) = d4h;
    __forge_tuple_u32_u32_u32_u32_t __tup_464_8 __attribute__((unused)) = g_mix(r7_0, r7_4, r7_8, r7_12, m6, m15);
    uint32_t a0i __attribute__((unused)) = (__tup_464_8)._0;
    uint32_t b0i __attribute__((unused)) = (__tup_464_8)._1;
    uint32_t c0i __attribute__((unused)) = (__tup_464_8)._2;
    uint32_t d0i __attribute__((unused)) = (__tup_464_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_465_8 __attribute__((unused)) = g_mix(r7_1, r7_5, r7_9, r7_13, m14, m9);
    uint32_t a1i __attribute__((unused)) = (__tup_465_8)._0;
    uint32_t b1i __attribute__((unused)) = (__tup_465_8)._1;
    uint32_t c1i __attribute__((unused)) = (__tup_465_8)._2;
    uint32_t d1i __attribute__((unused)) = (__tup_465_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_466_8 __attribute__((unused)) = g_mix(r7_2, r7_6, r7_10, r7_14, m11, m3);
    uint32_t a2i __attribute__((unused)) = (__tup_466_8)._0;
    uint32_t b2i __attribute__((unused)) = (__tup_466_8)._1;
    uint32_t c2i __attribute__((unused)) = (__tup_466_8)._2;
    uint32_t d2i __attribute__((unused)) = (__tup_466_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_467_8 __attribute__((unused)) = g_mix(r7_3, r7_7, r7_11, r7_15, m0, m8);
    uint32_t a3i __attribute__((unused)) = (__tup_467_8)._0;
    uint32_t b3i __attribute__((unused)) = (__tup_467_8)._1;
    uint32_t c3i __attribute__((unused)) = (__tup_467_8)._2;
    uint32_t d3i __attribute__((unused)) = (__tup_467_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_468_8 __attribute__((unused)) = g_mix(a0i, b1i, c2i, d3i, m12, m2);
    uint32_t a4i __attribute__((unused)) = (__tup_468_8)._0;
    uint32_t b4i __attribute__((unused)) = (__tup_468_8)._1;
    uint32_t c4i __attribute__((unused)) = (__tup_468_8)._2;
    uint32_t d4i __attribute__((unused)) = (__tup_468_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_469_8 __attribute__((unused)) = g_mix(a1i, b2i, c3i, d0i, m13, m7);
    uint32_t a5i __attribute__((unused)) = (__tup_469_8)._0;
    uint32_t b5i __attribute__((unused)) = (__tup_469_8)._1;
    uint32_t c5i __attribute__((unused)) = (__tup_469_8)._2;
    uint32_t d5i __attribute__((unused)) = (__tup_469_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_470_8 __attribute__((unused)) = g_mix(a2i, b3i, c0i, d1i, m1, m4);
    uint32_t a6i __attribute__((unused)) = (__tup_470_8)._0;
    uint32_t b6i __attribute__((unused)) = (__tup_470_8)._1;
    uint32_t c6i __attribute__((unused)) = (__tup_470_8)._2;
    uint32_t d6i __attribute__((unused)) = (__tup_470_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_471_8 __attribute__((unused)) = g_mix(a3i, b0i, c1i, d2i, m10, m5);
    uint32_t a7i __attribute__((unused)) = (__tup_471_8)._0;
    uint32_t b7i __attribute__((unused)) = (__tup_471_8)._1;
    uint32_t c7i __attribute__((unused)) = (__tup_471_8)._2;
    uint32_t d7i __attribute__((unused)) = (__tup_471_8)._3;
    uint32_t r8_0 __attribute__((unused)) = a4i;
    uint32_t r8_1 __attribute__((unused)) = a5i;
    uint32_t r8_2 __attribute__((unused)) = a6i;
    uint32_t r8_3 __attribute__((unused)) = a7i;
    uint32_t r8_4 __attribute__((unused)) = b7i;
    uint32_t r8_5 __attribute__((unused)) = b4i;
    uint32_t r8_6 __attribute__((unused)) = b5i;
    uint32_t r8_7 __attribute__((unused)) = b6i;
    uint32_t r8_8 __attribute__((unused)) = c6i;
    uint32_t r8_9 __attribute__((unused)) = c7i;
    uint32_t r8_10 __attribute__((unused)) = c4i;
    uint32_t r8_11 __attribute__((unused)) = c5i;
    uint32_t r8_12 __attribute__((unused)) = d5i;
    uint32_t r8_13 __attribute__((unused)) = d6i;
    uint32_t r8_14 __attribute__((unused)) = d7i;
    uint32_t r8_15 __attribute__((unused)) = d4i;
    __forge_tuple_u32_u32_u32_u32_t __tup_478_8 __attribute__((unused)) = g_mix(r8_0, r8_4, r8_8, r8_12, m10, m2);
    uint32_t a0j __attribute__((unused)) = (__tup_478_8)._0;
    uint32_t b0j __attribute__((unused)) = (__tup_478_8)._1;
    uint32_t c0j __attribute__((unused)) = (__tup_478_8)._2;
    uint32_t d0j __attribute__((unused)) = (__tup_478_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_479_8 __attribute__((unused)) = g_mix(r8_1, r8_5, r8_9, r8_13, m8, m4);
    uint32_t a1j __attribute__((unused)) = (__tup_479_8)._0;
    uint32_t b1j __attribute__((unused)) = (__tup_479_8)._1;
    uint32_t c1j __attribute__((unused)) = (__tup_479_8)._2;
    uint32_t d1j __attribute__((unused)) = (__tup_479_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_480_8 __attribute__((unused)) = g_mix(r8_2, r8_6, r8_10, r8_14, m7, m6);
    uint32_t a2j __attribute__((unused)) = (__tup_480_8)._0;
    uint32_t b2j __attribute__((unused)) = (__tup_480_8)._1;
    uint32_t c2j __attribute__((unused)) = (__tup_480_8)._2;
    uint32_t d2j __attribute__((unused)) = (__tup_480_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_481_8 __attribute__((unused)) = g_mix(r8_3, r8_7, r8_11, r8_15, m1, m5);
    uint32_t a3j __attribute__((unused)) = (__tup_481_8)._0;
    uint32_t b3j __attribute__((unused)) = (__tup_481_8)._1;
    uint32_t c3j __attribute__((unused)) = (__tup_481_8)._2;
    uint32_t d3j __attribute__((unused)) = (__tup_481_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_482_8 __attribute__((unused)) = g_mix(a0j, b1j, c2j, d3j, m15, m11);
    uint32_t a4j __attribute__((unused)) = (__tup_482_8)._0;
    uint32_t b4j __attribute__((unused)) = (__tup_482_8)._1;
    uint32_t c4j __attribute__((unused)) = (__tup_482_8)._2;
    uint32_t d4j __attribute__((unused)) = (__tup_482_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_483_8 __attribute__((unused)) = g_mix(a1j, b2j, c3j, d0j, m9, m14);
    uint32_t a5j __attribute__((unused)) = (__tup_483_8)._0;
    uint32_t b5j __attribute__((unused)) = (__tup_483_8)._1;
    uint32_t c5j __attribute__((unused)) = (__tup_483_8)._2;
    uint32_t d5j __attribute__((unused)) = (__tup_483_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_484_8 __attribute__((unused)) = g_mix(a2j, b3j, c0j, d1j, m3, m12);
    uint32_t a6j __attribute__((unused)) = (__tup_484_8)._0;
    uint32_t b6j __attribute__((unused)) = (__tup_484_8)._1;
    uint32_t c6j __attribute__((unused)) = (__tup_484_8)._2;
    uint32_t d6j __attribute__((unused)) = (__tup_484_8)._3;
    __forge_tuple_u32_u32_u32_u32_t __tup_485_8 __attribute__((unused)) = g_mix(a3j, b0j, c1j, d2j, m13, m0);
    uint32_t a7j __attribute__((unused)) = (__tup_485_8)._0;
    uint32_t b7j __attribute__((unused)) = (__tup_485_8)._1;
    uint32_t c7j __attribute__((unused)) = (__tup_485_8)._2;
    uint32_t d7j __attribute__((unused)) = (__tup_485_8)._3;
    uint32_t f0 __attribute__((unused)) = a4j;
    uint32_t f1 __attribute__((unused)) = a5j;
    uint32_t f2 __attribute__((unused)) = a6j;
    uint32_t f3 __attribute__((unused)) = a7j;
    uint32_t f4 __attribute__((unused)) = b7j;
    uint32_t f5 __attribute__((unused)) = b4j;
    uint32_t f6 __attribute__((unused)) = b5j;
    uint32_t f7 __attribute__((unused)) = b6j;
    uint32_t f8 __attribute__((unused)) = c6j;
    uint32_t f9 __attribute__((unused)) = c7j;
    uint32_t f10 __attribute__((unused)) = c4j;
    uint32_t f11 __attribute__((unused)) = c5j;
    uint32_t f12 __attribute__((unused)) = d5j;
    uint32_t f13 __attribute__((unused)) = d6j;
    uint32_t f14 __attribute__((unused)) = d7j;
    uint32_t f15 __attribute__((unused)) = d4j;
    uint32_t out0 __attribute__((unused)) = ((h0 ^ f0) ^ f8);
    uint32_t out1 __attribute__((unused)) = ((h1 ^ f1) ^ f9);
    uint32_t out2 __attribute__((unused)) = ((h2 ^ f2) ^ f10);
    uint32_t out3 __attribute__((unused)) = ((h3 ^ f3) ^ f11);
    uint32_t out4 __attribute__((unused)) = ((h4 ^ f4) ^ f12);
    uint32_t out5 __attribute__((unused)) = ((h5 ^ f5) ^ f13);
    uint32_t out6 __attribute__((unused)) = ((h6 ^ f6) ^ f14);
    uint32_t out7 __attribute__((unused)) = ((h7 ^ f7) ^ f15);
    uint64_t base __attribute__((unused)) = (leaf * 8ULL);
    if (((base + 7ULL) < hashes.len)) {
      hashes.data[base] = reduce_word(out0);
      hashes.data[(base + 1ULL)] = reduce_word(out1);
      hashes.data[(base + 2ULL)] = reduce_word(out2);
      hashes.data[(base + 3ULL)] = reduce_word(out3);
      hashes.data[(base + 4ULL)] = reduce_word(out4);
      hashes.data[(base + 5ULL)] = reduce_word(out5);
      hashes.data[(base + 6ULL)] = reduce_word(out6);
      hashes.data[(base + 7ULL)] = reduce_word(out7);

    }

  }
}

